### ISSUE TITLE
Pastefromword: intermittently get popup alert '2'

### ISSUE THREAD

**Issue by britishmonkey** [ckeditor/ckeditor-dev#1001]
## Provide detailed reproduction steps (if any)

Paste text from MS Word

### Expected result

Text is pasted into editor

### Actual result

Randomly get popup alert with value '2' for every line break in the pasted text. After all popups the text is pasted ok.

## Other details

IE, Chrome definitely
Win 7/10
CKEditor 4.5.7
Installed CKEditor plugins: pastefromword,doksoft,onclick

**Comment by mlewand** [comment]
Our Paste from Word plugin does not use alerts at all. It sounds to me that it's one of external plugins to put this alert.

The best way to troubleshoot that is to disable third party plugins one by one, and see if the problem is gone. Once you know what plugin is this, you can report the issue to a relevant plugin author.

In case you did all the troubleshooting and you believe that it's still a CKEditor issue itself, try to reproduce this issue with any of our [nightly builds](nightly.ckeditor.com). And if you're able to do so provide us with steps to reproduce and reopen this issue.

**Comment by britishmonkey** [comment]
Thanks for the prompt response. We've had to modify the javascript slightly but this happens even when reverting to the default.,js. Sadly, as usual, it's intermittent so we'll try to narrow down the cause. Since no alerts in pastefromword it does seem that an add-on is causing a conflict.

**Comment by mlewand** [comment]
Most likely. I'd just suggest that, whenever possible, you should try to add your code in a separate plugin and hook to events that CKE fires. When editing our files you might save some time, but you'll have problems with updating CKE to the latest version.

Good luck with the troubleshooting!
