### ISSUE TITLE
forcePasteAsPlainText doesn't filter text pasted from word

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1013]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Set CKEditor configuration to:
```
var editor = CKEDITOR.replace( 'editor1', {
	forcePasteAsPlainText : true, 
	enterMode : CKEDITOR.ENTER_BR
});
```
2. Load CKEditor sample in a browser and clear it contents.
3. Paste contents of attached Word file
[test.docx](https://github.com/ckeditor/ckeditor-dev/files/1359540/test.docx)

### Expected result

Only text divided by BR tags gets pasted .

### Actual result

Starting from CKEditor 4.5.0 tags like lists, tables or spans are no longer removed.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.5.0+
* Installed CKEditor plugins: N/A

**NOTE:** The documentation for `forcePasteAsplainText` - https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.config-cfg-forcePasteAsPlainText still mentions PFW dialog which we have removed in version 4.7.0. If we are not going to bring it back (unless there is no other solution for mobiles), shouldn't we remove that information?

**Comment by mlewand** [comment]
Yes, we need definitely update the docs referenced by @jswiderski.

The problem is that before 4.7.x we had this quirk that `forcePasteAsPlainText` would not have an effect if the content was pasted through the dialog.

Since 4.7.x we're very good at detecting content from MS Word on data-transfer enabled browsers. Thus we could provide a way to paste rich text (ignoring `forcePasteAsPlainText`) to people who enjoyed this function in pre-4.7.x releases.

We could do that with `forcePasteAsPlainText` accepting following vals:
* `false` - editor allows for rich text pasting (though one needs to remember about paste filter)
* `true` - no matter what, only plain text should be pasted as the config implies
* `'allow-office'` or `'ignore-office'` (or replace "office" with "word")  that settings works as `true` except it allows rich content pastes from Microsoft Office.

**Comment by mlewand** [comment]
Unfortunately we won't be able to fix this regression in this major release.

The good news is that it should not be very risky/API breaking change, so we should be able to include it in next minor release. So it will not be delayed by a long time.

Sorry for inconvenience.
