### ISSUE TITLE
Can not save custom toolbars changes

### ISSUE THREAD

**Issue by camism** [ckeditor/ckeditor-dev#1018]
My Custom Editor Options on a DNN site are set as Basic (like in image below).
I want to set them as Standard. If I choose Standard and click on the Save button, nothing happens. How can I fix this problem because my editor tools is very poor? Can anybody help me?

Thanks a lot,
Camelia
![ckeditor settings](https://user-images.githubusercontent.com/16599925/31280776-252c8ca0-aab6-11e7-92db-ccb0379ded16.png)

**Comment by msamsel** [comment]
Hi @camism,
unfortunately DNN is not officially supported platform by CKEditor Team. Please contact with support dedicated for DNN (or team who prepare such integration). Here we can help you with problem detected in CKEditor, which usually are possible to reproduce with pure HTML and JS without 3rd party tools. More information about support you can find [here](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/SUPPORT.md).

**Comment by msamsel** [comment]
Just to be a little bit more precise.
From technical point of view CKEditor of course might be used by DNN and if it's integrate well, it will be work nicely with it. 
We're not support it from Licensing point of view, that's why in such case like here, you should contact with DNN directly. This company prepare integration of CKEditor with their system, so all issues like that should be resolve by their support team.
I hope it make more clear entire situation.
