### ISSUE TITLE
ckeditor not support Arabic number

### ISSUE THREAD

**Issue by ahmedramzy86** [ckeditor/ckeditor-dev#1021]
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
[اعلان  جريدة  ام القرى1439.docx](https://github.com/ckeditor/ckeditor-dev/files/1379815/1439.docx)

* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by beatadelura** [comment]
@ahmedramzy86 I need more details to understand this issue. Could you please provide more information: [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with configuration and exact steps to reproduce? Please fill template issue above with proper information.

**Comment by ahmedramzy86** [comment]
i past from word with Arabic number but it convert to English number
there is test work document
i want to add Arabic font
also when i copy and past from the word the sizes, space between the lines,
all my Coordinate is different

**Comment by beatadelura** [comment]
@ahmedramzy86 May I ask you to provide word document with numbers/text which you are pasting?

**Comment by ahmedramzy86** [comment]
this is the word that i am pasting

**Comment by ahmedramzy86** [comment]
i want to purchase editor for Arabic users;
those users want to copy from old word documents to the editor with  Arabic
fonts and Arabic numbers
and the same Coordinate

**Comment by beatadelura** [comment]
@ahmedramzy86 I can't see any attachment here. Could you please attach **`MS Word` document (`.doc` filename extension)** with text/numbers you trying to paste, **directly by GitHub** (not by email)?

I also kindly ask you to fill our template issue:

## Are you reporting a feature request or a bug?



## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by ahmedramzy86** [comment]
[اعلان  جريدة  ام القرى1439.docx](https://github.com/ckeditor/ckeditor-dev/files/1379819/1439.docx)

**Comment by ahmedramzy86** [comment]
this is my word

**Comment by beatadelura** [comment]
@ahmedramzy86 I'm sorry but I can't reproduce this issue. Your `.doc` file already contains `latin` numerals, so I can't see the difference after the paste. I created my own [arabic_numerals.docx](https://github.com/ckeditor/ckeditor-dev/files/1386666/arabic_numerals.docx) with Arabic numerals and test it with CKEditor version 4.7.3 on Chrome 61, Firefox, IE11. It works fine.
