### ISSUE TITLE
JAWS keystrokes don't work in empty table cells

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1035]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

0. **AUTO FORMS MODE** - According to this link - https://tink.uk/understanding-screen-reader-interaction-modes/, forms mode is being activated automatically whenever you enter a form filed. It is done automatically and signalized with a beep.
**MANUAL FORMS MODE** - According to this link http://doccenter.freedomscientific.com/doccenter/doccenter/rs11f929e9c511/2014-12-02_webpagetesting-l1/02_JAWS-Settings.htm you can enable Manual Forms Mode by pressing `INSERT+F2`, selecting Settings Center, typing Forms Mode and switching from Auto to Manual. To enable Forms mode when on page, you need to press Enter. To disable it, you need to press `Esc`.

1. Enable JAWS
2. Open CKEditor sample, clear editor contents and insert **empty** table
3. Try using JAWS table shortcuts to navigate through the table: http://doccenter.freedomscientific.com/doccenter/archives/training/jawskeystrokes.htm (**Tables in HTML** section).
4. Next fill table cells with text and try using keystrokes again.

Keystrokes which definitely work in native contenteditable element (can be checked here: https://codepen.io/j_swiderski/pen/NvOdWz) as well as editor (provided that cells aren't empty): `Ctrl+Alt+(End|Home|Left Arrow|Right Arrow|Up Arrow|Down Arrow)`.

### Expected result

JAWS key shortcuts should work in empty and non-empty table cells.

### Actual result

JAWS key shortcuts work only in non-empty table cells.

## Other details

* Browser: Firefox
* OS: Windows
* CKEditor version: 4.0+
* Installed CKEditor plugins: table

**Comment by mlewand** [comment]
This isAfter an investigation this case turned to be an upstream issue (either JAWS or FF).

The problem is that JAWS in FF does not seem to be able to recognize selected (empty) table in a contenteditable nested within an iframe.

You can check it for yourself at https://codepen.io/mlewand/pen/WzQLZQ

There is an "add table to the frame" button, which replaces editable content with an empty table, puts the selection in the first column and focuses the editable. And this is where JAWS wrongly states that the selection is not in table, while it clearly is in the cell.

Interestingly, on Chrome, JAWS recognizes that it is in table, so it _might_ be an issue in Firefox.

Used FF 52.6.0 (ESR), JAWS 2018.1802.78, Chrome 64.0.3282.186 on Win7 for testing.
