### ISSUE TITLE
Extra paragraph added.

### ISSUE THREAD

**Issue by georgeLoney** [ckeditor/ckeditor-dev#1051]
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)
Checked
*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …At the end of a line, when the enter key is pressed, an extra <p>&nbsp;</p> is added.  This also happens at the end of a <li></li> line.  Instead of starting a new list line, it adds a paragraph and then starts a new paragraph.
2. …
3. …

### Expected result
If the html code is <p>line</p> and I press enter I would expect that the editor would start a new paragraph.

### Actual result
The actual result is <p>line</p><p>&nbsp;</p><p>cursor here</p>

## Other details

* Browser: …Firefox and Chrome
* OS: … Mac OS 10.10.5
* CKEditor version: … 4.7.2
* Installed CKEditor plugins: …panelbutton,floatpanel,bootstrapGrid,doksoft_table_new,
doksoft_table_conf,doksoft_table_row_conf,doksoft_table_col_conf,doksoft_table_cell_conf,
doksoft_table_row_move_up,doksoft_table_row_move_down,doksoft_table_col_move_left,
doksoft_table_col_move_right,doksoft_table_add_row_up,doksoft_table_add_row_down,
doksoft_table_add_col_left,doksoft_table_add_col_right,doksoft_table_add_cell_left,
doksoft_table_add_cell_right,doksoft_table_delete_col,doksoft_table_delete_row,
doksoft_table_delete_cell,doksoft_table_merge_cells,doksoft_table_merge_cell_right,
doksoft_table_merge_cell_down,doksoft_table_split_cell_hor,doksoft_table_split_cell_vert

**Comment by georgeLoney** [comment]
A follow-up.  I removed all the plugins except panelbutton and floatpanel and the problem goes away.

**Comment by beatadelura** [comment]
@georgeLoney I'm not sure what is your issue about and it seems to me that you are using third-party CKEditor plugins which are not supported by CKEditor. Could you please provide [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with **configuration** and **exact steps to reproduce**?

Please also check whether this issue is not related to third-party CKEditor plugins. If yes, you should report it straight to author.
