### ISSUE TITLE
Failing test /tests/core/ckeditor/basepathglobal on Safari

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1061]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. run test `/tests/core/ckeditor/basepathglobal`

### Expected result

Test pass

### Actual result
Below 2 test cases fails:
- test full BASEPATH
- test protocol relative BASEPATH

## Other details

* Browser: Safari Version 11.0 (12604.1.38.1.7), Safari Version 11.0 (13604.1.38.1.6)
* OS: MacOS
* CKEditor version: major (but also stable releases has those problem)
* Installed CKEditor plugins: …

**Comment by beatadelura** [comment]
This test fails if there is no `sub.ckeditor.dev` hostname specified in `/etc/hosts`. So it's a local configuration issue rather than a test.

I'm going to create a new task with regard to this. It would be nice to make this test more flexible and work for custom aliases. See comment [here](https://github.com/ckeditor/ckeditor-dev/pull/1082#pullrequestreview-71501634).

**Comment by f1ames** [comment]
As I took another look on those tests, it looks there is an issue on Safari, more details here https://github.com/ckeditor/ckeditor-dev/pull/1090#discussion_r148548901.
