### ISSUE TITLE
CKEDITOR not working with field name description

### ISSUE THREAD

**Issue by zu007** [ckeditor/ckeditor-dev#1135]
## CKEDITOR - Uncaught Error: The specified element mode is not supported on element: “meta”

```
<textarea class="form-control" name="description">
 </textarea>
<script>
     CKEDITOR.replace( 'description' );
</script>
```
if i use attribue name value **description** then ckeditor stop working
## Other details

* Browser: Google Chrome Version 61.0.3163.100
* OS: Window 10
* CKEditor version: 4.7.3

**Comment by msamsel** [comment]
Hi,

from what I see we find first element in document with given name and attach editor to it.
https://github.com/ckeditor/ckeditor-dev/blob/e72835fa036f35a4c5657665b4a70e19ca278efc/core/dom/element.js#L52-L56
I suspect that on your page exists meta tag with 'description' name and this is place where our script try to attach editor.

I suggest to either:
- change name of textarea to something else more uniq on page.
- use id attribute
- provide html element directly instead of its name.

More information how to initialise editor: https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR-method-replace
