### ISSUE TITLE
Edge get frozen after paste content repeatedly

### ISSUE THREAD

**Issue by eherreraUZ** [ckeditor/ckeditor-dev#1159]
## Are you reporting a feature request or a bug?

BUG

## Provide detailed reproduction steps (if any)

1. Open the next link on Edge: https://sdk.ckeditor.com/samples/size.html
2. Paste some text block several times with Ctrl + V
3. Type something or select some text

### Expected result
It is possible to type something or select text (edit content)

### Actual result
The browser get frozen and only is possible to scroll. After a while (minutes) the browser works again.

![ckeditor](https://user-images.githubusercontent.com/29234201/32781787-8f07bb14-c946-11e7-9837-045d1cfc2433.gif)

## Other details

* Browser: Microsoft Edge
* OS: Window 10
* CKEditor version: 4.7.2
* Installed CKEditor plugins: tableselection, contextmenu, elementspath, link, magicline, paste, tabletools, autogrow, colorbutton, font, indentblock, justify, panelbutton, pastefromword, sharedspace, uzuploader, clipboard, lineutils, uz-video-embed, widget, widgetselection, floatingspace (uz-* plugins are custom plugins)

**Comment by Mgsy** [comment]
This bug is reproducible in our `SDK` samples, but it doesn't occur in local builds or manual tests (even with the same HTML). I've checked this scenario in `Edge 16` and I wasn't able to reproduce the issue, so probably it won't be valid after official `Edge 16` release.

@eherreraUZ, can I ask you to provide us some details about your MS Edge version?

**Comment by mlewand** [comment]
I think I also randomly experienced issue described by @eherreraUZ - checking now on linked SDK page I can no longer reproduce it.

Checked with `Microsoft Edge 41.16299.15.0`.

**Comment by eherreraUZ** [comment]
We are experiencing this issue on Microsoft Edge 40.15063.0.0

**Comment by jswiderski** [comment]
I'm using Edge 40.15063.674.0 and was only able to reproduce this problem in that particular SDK sample and it didn't happen on regular basis. Sometimes I was able to paste large amount of text and sometimes after single paste and attempt to select text I was getting browser freeze.

**Comment by mlewand** [comment]
@Mgsy could you check if this is reproducible with the latest edge?

**Comment by Mgsy** [comment]
>@Mgsy could you check if this is reproducible with the latest edge?

I'm not able to reproduce it in the latest Edge 17 (42.17134.1.0).

**Comment by mlewand** [comment]
Looks like this issue is no longer reproducible, in case you can still reproduce this issue feel free to reopen the issue/create a follow-up.

**Comment by jswiderski** [comment]
While I could not reproduce the exact problem in Microsoft Edge 42.17134.1.0, I have experienced the frezzing effect in CKEditor SDK. It seems that copying sample text, pressing enter before horizontal line and then trying to paste the sample text results in error. Please see attached screen cast -[scree-cast.zip](https://github.com/ckeditor/ckeditor-dev/files/2282067/scree-cast.zip).  

In order to be able to paste and type again, I needed to copy sample text once more.

Please note however that I have tried reproducing this problem in nightly version as well as in local build but in all cases it was possible to paste and type without problems.

**Comment by mlewand** [comment]
I won't check again for it as my assumption is that It most likely is related to SDK itself, which is going to be ported soon to Umberto ckeditor/ckeditor-sdk#259 - so if that's the case it will get fixed.

I'd be concerned if it happened in a regular editor.
