### ISSUE TITLE
Make notification optionable on failed embed

### ISSUE THREAD

**Issue by terrapop** [ckeditor/ckeditor-dev#1182]
When embedding of an asset fails a notification info is shown:

"This URL could not be automatically embedded."

by this function:

editor.showNotification( lang.embeddingFailed, 'info' );

Would it be possible to make this configurable? I found this message irrelevant and annoying for the user.

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

---

Such notifications are not configurable at the moment, you may issue a new Feature request. **Please remember to follow issue template next time**.
