### ISSUE TITLE
Paste few lists from word broken in edge

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#1244]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Paste a list from word(Sample list in my doc) in ck editor(Edge)

### Expected result
The list is pasted as list.
### Actual result
The list is pasted in p tags. Look at the innerHTML

## Other details

* Browser: Edge
* OS: Windows 10
* CKEditor version: CKEditor 4.7.0

**Comment by zoarif** [comment]
[sample list.docx](https://github.com/ckeditor/ckeditor-dev/files/1507877/sample.list.docx)

**Comment by zoarif** [comment]
![innerhtml](https://user-images.githubusercontent.com/18426614/33293919-4de4c68a-d383-11e7-8633-ae2315cdd7c6.PNG)

**Comment by mlewand** [comment]
You'll be pleased to learn that it's fixed in upcoming 4.8.0 release (you can check it out on our [nightly standard/full builds](http://nightly.ckeditor.com/)).

Your example abow, just shows what Edge was pasting to the `contenteditable` since its launch. Luckily recently Edge team partially implemented Cliboard API which allowed us to align PFW experience with Chrome and Firefox. We have integrated it in #468.
