### ISSUE TITLE
CK-Editor: Button tags are not working in CKEditor 4

### ISSUE THREAD

**Issue by pradeepgoud1210** [ckeditor/ckeditor-dev#1297]
Hi,

We have button tags `<button type="button">Edit</button>` almost in all our forms, this tag looks fine when i use CK-Editor version 3, but now we want to upgrade to version 4.7.3. When we use our existing forms with newer version of ck-editor, button tags are displaying as plain text instead of button control. But this is working fine when i use input type button`<input type="button" />`.

Please do the needful.

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

---

In the meantime you may take a look on [Advanced Content Filter docs](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_advanced_content_filter) to see how to allow additional HTML elements in CKEditor.
