### ISSUE TITLE
Bug: sign + removed

### ISSUE THREAD

**Issue by Ange7** [ckeditor/ckeditor-dev#1314]
## Are you reporting a feature request or a bug? 

When i type sign "+" in ckeditor and send data to POST http request in PHP, my sign is removed

## Provide detailed reproduction steps (if any)

1. Just type "+"

### Expected result

"+" is keep

### Actual result

"+" is remove

## Other details

* Browser: Google Chrome
* OS: Windows 7
* CKEditor version: 4.7.3
* Installed CKEditor plugins: see my config here : https://pastebin.com/xHMwxB2X

**Comment by Comandeer** [comment]
I can't reproduce issue in CKEditor. It seems that bug is located in your custom code:

```javascript
form_data = form_data+"&"+encodeURIComponent(elmnt.name)+"="+elmnt.getData();
```

As you're creating form data manually, you should escape data from the editor. You could do this by using `encodeURIComponent`, like you've already done for editor's name.

Without escaping, `+` is treated as space and that's probably the source of the issue.
