### ISSUE TITLE
CKEditor paste event not firing in Chrome

### ISSUE THREAD

**Issue by rohityadav225** [ckeditor/ckeditor-dev#1324]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Copy text/html.
2. Paste it in CKEditor.

### Expected result

No paste event in Chrome.

### Actual result

Paste event should be fired.

## Other details

It does work OK with Firefox.

* Browser: Chrome
* OS:Chrome OS,Mac,Windows
* CKEditor version:4.4.3
* Installed CKEditor plugins:matheditor,divarea,tab

**Comment by mlewand** [comment]
Improved the initial report description.

**Comment by mlewand** [comment]
The `paste` event works perfectly fine on Chrome. Verified with:

* `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36`
* `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3291.0 Safari/537.36`

TC:

1. Open https://codepen.io/mlewand/pen/rpBpjV
1. Open developer console
1. Copy any rich text
1. Paste into the editor

## Actual & expected

Console logs paste event.

**Comment by rohityadav225** [comment]
It happens mostly on chrome packaged apps and chrome browser running on chromeOS (Chromebooks).

**Comment by mlewand** [comment]
@rohityadav225 In this case it might be very tricky for us to reproduce it as don't have a setup for that in place.

However I can suggest something that will help track this down, because if the issue exists, it does sound to me like a Chrome upstream issue.

1. Open [plain contenteditable paste listner demo](https://codepen.io/mlewand/pen/xqwRJb).
1. Open a dev console.
1. Perform a paste into the box with a green border.
1. See if console logged 'paste'.

Another test is to use:

1. Open [CKEditor classic paste demo](https://codepen.io/mlewand/pen/rpBpjV).
1. Open a dev console.
1. Perform a paste into the editor's editable area.
1. See if console logged 'paste event'.

Please share your results, based on that we might be able to help you.
