### ISSUE TITLE
BUG: Cannot bock ALT +A in configuration

### ISSUE THREAD

**Issue by mjenso** [ckeditor/ckeditor-dev#1361]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

I'm using XWiki with CKEditor. Currently ALT + A in WYSIWYG "selects all" in the edited page. The problem is that, in Poland, we use ALT + A to create a fancy "ą" symbol so when I'm trying to write "ą" I'm selecting everything and also getting "ą" symbol.  I tried to block this bind with such command in "Advanced configuration". Any other commands like "config.toolbarCanCollapse = true;" work fine.

I 'm trying to block the key with this command:

```js
config.keystrokes = [
	[ CKEDITOR.ALT + 65, null ],
	[ CKEDITOR.ALT + 97, null ],
];
```

...but it doesn't work.

### Expected result

With `[ CKEDITOR.ALT + 65, null ]` working I should get only "ą" (without "select all").

### Actual result

ALT + A creates "ą" symbol and selects all text :(

## Other details

* Browser: Chrome ENG
* OS: Windows 7 ENG
* CKEditor version: No info, XWiki 9.11
* Installed CKEditor plugins: No info, default to XWiki 9.11

**Comment by mlewand** [comment]
Actually what you're pressing isn't technically an alt key, but it's [altGr](https://en.wikipedia.org/wiki/AltGr_key). There's a slight difference between the two, let's just say that altGr acts as ctrl+alt pressed together - that's why as a workaround you should look to disable `CKEDITOR.ALT + CKEDITOR.CTRL + x` keys.

If you have ability to execute JS code, you could mitigate this with the following:

```js
CKEDITOR.instances.editor.setKeystroke( CKEDITOR.ALT + CKEDITOR.CTRL + 65, false );
```

Above will disable hotkey for a given combination.

Nonetheless it's just a workaround, and you should report it to the upstream (XWiki) so that they change the default key binginds in a way it plays well with Polish keyboard.

As for CKEditor AFAICT there is no way for us to detect diacritic key combinations. This is something that should be done by one who sets the hotkeys.
