### ISSUE TITLE
The number 7 within the ck editor is not getting formatted with Bold

### ISSUE THREAD

**Issue by Sathishjayabal** [ckeditor/ckeditor-dev#1393]
When we have the number 7 in the ck editor and when we use the font, "Times New Roman", and font size as "11" or "12", on applying the bold and Italics, the number 7 is not getting formatted.  It works for all other fonts.

Steps to reproduce
1) Open the CK editor
2) Enter Oct. 6, 2017
3) Select the entire text, (i.e, Oct. 6, 2017)
5) Select Bold, Italics, Underlined
6) Select Times New Roman
7) Select size 11 or 12 font

Observe that the 7 is no longer bold.

![ck editor](https://user-images.githubusercontent.com/35054211/34508987-579b47e4-f06b-11e7-888d-933c76e7e959.png)

**Comment by f1ames** [comment]
Tried to reproduce on https://sdk.ckeditor.com/samples/fullpreset.html, but it works fine there:
![jan-03-2018 10-24-17](https://user-images.githubusercontent.com/1061942/34515010-692f2fb6-f070-11e7-9c2d-d6d7357db6df.gif)

Please provide more details on your environment (Browser version, OS, CKEditor version, active CKEditor plugins).

**Also it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem. Please follow the template next time.**

**Comment by Sathishjayabal** [comment]
Even in our case, In the source, the value is getting saved as strong, but still the number 7 is not getting formatted.

In your video as well, though strong is getting set, still the number 7 do not seem to be formatted.

Here are the details that you requested

CKeditor version no : 4.4
Browser version : Google chrome : Version 63.0.3239.84
OS : Windows 7
Active ck editor plugins :  (Please refer the below screen)
![image](https://user-images.githubusercontent.com/35054211/34714588-e307ba5e-f54f-11e7-8f86-38193f23e6da.png)

**Comment by f1ames** [comment]
> Even in our case, In the source, the value is getting saved as strong, but still the number 7 is not getting formatted.

This means that editor works correctly, applying proper tags. The issue here is probably how the browsers renders such characters (on which editor does not have any impact), if you look closely, you will see slight difference between bolded and unbolded `7`:

![image](https://user-images.githubusercontent.com/1061942/34724399-f9167d14-f54d-11e7-8b68-fb020cb33b16.png)

![image](https://user-images.githubusercontent.com/1061942/34724412-04d8fcd0-f54e-11e7-852b-886e6ed4c1df.png)

but the difference is very subtle so it may seem `7` is not bolded.
