### ISSUE TITLE
Make magic line line element identifiable using attribute

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1441]
## Are you reporting a feature request or a bug?

Feature request 

## Provide detailed reproduction steps (if any)

The magic line as well as drop line, showing up when block widget is being dragged, could use a CSS class or data attribute that could help identifying them as well as adding additional styling.

In fact Line Utils plugin elements are marked with `data-cke-lineutils-line` attribute, so it would make sense to mark it with `data-cke-magic-line` for consistency.

**Comment by mlewand** [comment]
Interestingly magicline has nothing to identify it, so in fact it would be nice to have it explicitly marked. It could be either class or data attribute. Id is not a good idea, due to mentioned fact that it could be within the same document which would violate HTML (thus I'll remove this proposal from original description).

**Comment by jswiderski** [comment]
As discussed with @mlewand the drop line is controlled by `lineutils` plugin and the line has the `data-cke-lineutils-line` which can give same level of flexibility as CSS class thus it doesn't make sense to add anything new to it but only focusing on magic-line.
