### ISSUE TITLE
pasting from libreoffice adds extra paragraph

### ISSUE THREAD

**Issue by LiamDawe** [ckeditor/ckeditor-dev#1480]
## Are you reporting a feature request or a bug?

Bug.

## Provide detailed reproduction steps (if any)

1) Write content in libreoffice (free and open source document suit)
2) Paste into ckeditor 4
3) Get an extra paragraph tags in between paragraphs

### Expected result

Don't give an extra paragraph tag in between them

### Actual result

Get extra paragraphs

## Other details

* Browser: Chrome & Firefox (both latest stable)
* OS: Ubuntu Linux 17.10 64bit
* CKEditor version: latest 4.x

**Comment by f1ames** [comment]
Thanks for reporting @LiamDawe. When it comes to pasting content from document suits, only Microsoft Office is supported (Word and partially Excel, Outlook and others). While in many cases it will work with others like Libre Office (due to similar markup and some browser native support) there might be some issues like the one above.

**Comment by bluegroper** [comment]
I'm having exactly the same problem.  Pasting text from LibreOffice into ckeditor is seriously sub-optimal.
