### ISSUE TITLE
SCRIPT70: Permission denied on Edge

### ISSUE THREAD

**Issue by siulca** [ckeditor/ckeditor-dev#1503]
Potential Bug!

We're running CKEditor 4.4.7, it has worked flawlessly for about half a year but recently we noticed it has stopped working on Microsoft Edge with the runtime error:

`SCRIPT70: Permission denied`

This seems to occur when the editor is initialized so completely making our application unusable on Edge. 

We're under pressure to get this fixed but can't seem to find any useful info. I found a few older bug reports which seem to indicate that this has been fixed in previous versions of the editor so I'm puzzled as to why we're experiencing it!

Can someone please help?

**Comment by msamsel** [comment]
Hi @siulca,
there was quite lot patches and bugfixes since 4.4.7, https://github.com/ckeditor/ckeditor-dev/blob/stable/CHANGES.md
Please check if issue exists on current stable version (4.8.0). From out test everything is fine: https://cdn.ckeditor.com/4.8.0/full-all/samples/.

Also I checked that I don't see any troubles even with old version:
http://cdn.ckeditor.com/4.4.7/full-all/samples/replacebycode.html

I used Windows 10 x64 with Edge 16.16299 / 41.16299.15.0 for testing and everything is working nicely for me.

**Comment by msamsel** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
