### ISSUE TITLE
CKeditor

### ISSUE THREAD

**Issue by christianwinters** [ckeditor/ckeditor-dev#1520]
## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. I have downloaded the CKeditor.NET.dll.
2. I have downloaded the CKfinder.NET.dll.
3. I have added the control to the Toolbox in visual studio.

### Expected result

*What is the expected result of the above steps?*

### HTML page works, but the .aspx pages does not.

*What is the actual result of the above steps?*

## Other details

* Browser: I/E 7, google chrome.
* OS: …
* CKEditor version: ….4.8.0
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
ASP.NET integration has not been developed since CKEditor 3.6.6.2, therefore newer CKEditor versions are not supported. It might be possible to customise it on your side to support newer CKEditor, but it will require some code changes.

You can download CKEditor for .NET at http://download.cksource.com/CKEditor/CKEditor.NET/ however this is legacy software and we’re not encouraging to use it.

**Comment by christianwinters** [comment]
Thank you,

Best Regards,
Christian

Christian Winters
Software Engineer
1705 Desales Street NW, STE 400 | Washington, DC 20036
D 615-872-6855 | C 615-393-3627 | M 202-470-4806
www.analytica.net | GSA IT 70 (GS-35F-0622Y)
[1490210485819_EmailSignatureNew.png]
________________________________
