### ISSUE TITLE
Improve styling of the progress bar in Easy Image

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1533]
## Are you reporting a feature request or a bug?

feature

## Description

Upload process _might_ be improved. We have heard some people complying that it's not obvious what the progress bar is used for, what's the meaning of it.

First of, our goal with EI was so that the experience is as simple as it could be, we don't want to trouble end user with all the technical details.

At the same time it would make sense not to take away information about the upload from power users - hence upload progress.

**Comment by RyszardB** [comment]
new icon:
<img width="80" alt="screen shot 2018-02-01 at 10 27 06" src="https://user-images.githubusercontent.com/17498197/35671178-ddced336-073a-11e8-8934-96d2329b1b16.png">

v1
<img width="982" alt="screen shot 2018-02-01 at 10 27 13" src="https://user-images.githubusercontent.com/17498197/35671198-ebadb274-073a-11e8-978e-7df57bce9425.png">

v2
<img width="80" alt="screen shot 2018-02-01 at 10 27 06" src="https://user-images.githubusercontent.com/17498197/35671217-f866e4fe-073a-11e8-8703-e8149f753186.png">

upload:
<img width="978" alt="screen shot 2018-02-01 at 10 27 36" src="https://user-images.githubusercontent.com/17498197/35671238-0a361240-073b-11e8-90e0-e2586e292ac5.png">

alerts? (shows up for one second and then disappears (fade)
<img width="987" alt="screen shot 2018-02-01 at 10 28 07" src="https://user-images.githubusercontent.com/17498197/35671303-4473289e-073b-11e8-9f0d-4078f4a7ff7d.png">

**Comment by mlewand** [comment]
@RyszardB I find above proposition are a bit too aggressive in a sense that they focus user attention to the upload process too hard - while it should be something that just happens on a background.

I remember us also talking about gentle opacity change, in a sense that image that is uploaded would be a little transparent. I have prepared an example for that:

https://ckeditor4-preview.ckeditor.com/t/932-3180/plugins/easyimage/samples/easyimage.html

What do you think about that?

**Comment by msamsel** [comment]
@mlewand it's hard for me to see progressbar as the uploading is too fast. Is it possible to give some screenshot to analyse it more precisely?

**Comment by mlewand** [comment]
@msamsel use a big big image, or use network throttling in your dev tools 😛

![image](https://user-images.githubusercontent.com/5353898/35689504-f68b9df8-0773-11e8-8a0a-53fd9ba157e3.png)

At the same time it just shows that the issue might not affect most of users.

**Comment by f1ames** [comment]
I have mixed feelings. @RyszardB proposals looks very nice and smooth, but as @mlewand said they may be somehow distracting for the user in some cases. The advantage here is that user will always notice when the upload completes (or fails) and will be sure what's happening.

As for more subtle forms (like @mlewand proposal), it draws less attention so editing content during upload is more friendly. The problem here is that in many cases changes of upload status will go unnoticed, confusing the user.

When talking about subtle forms, maybe we should just drop progressbar entirely (I mean not showing it be default - I know significant amount of time was spent on creating it). Why bother the user, when in most cases the progress bar just blinks as the upload is quite fast. And show only errors when something fails? With such behaviour user just drops the image and may edit the content without wondering if he can do it while image is still being uploaded.

**Comment by wwalc** [comment]
> When talking about subtle forms, maybe we should just drop progressbar entirely (I mean not showing it be default - I know significant amount of time was spent on creating it). Why bother the user, when in most cases the progress bar just blinks as the upload is quite fast. And show only errors when something fails? With such behaviour user just drops the image and may edit the content without wondering if he can do it while image is still being uploaded.

It looks like this discussion is going into the wrong direction :D

We already spend a significant time on the progress bar so dropping it would mean that we did not think before at all.

If you are on a bad connection and upload an image, then you must know whether it has been uploaded or not, before you e.g. save the content and exit the editor. This is where the progress bar comes handy. If someone is not able to understand what the progress bar is for, then sorry. He will get it after uploading the second or third image. Or he will understand it if he hovers his mouse over it and we will display something like "Uploading image in progress (80% complete)". Tooltip on hover will help us deal with small images where we cannot put such a long text directly on the image.

Letting the user know if an image is in the middle of uploading or if it has been already uploaded is important. But this is what the progress bar is saying already. We indeed can make it even more obvious by reducing the opacity of an image that hasn't been uploaded yet or by making it in a way that @RyszardB proposed. But we shouldn't do more than that. 

I'd either wait for users feedback or implement the most trivial enhancement here that wouldn't cost us more than minutes. Therefore I'm more leaning towards @mlewand proposal because it's "cheap" and will fit also small images. If people will not like it, we may dig further.

**Comment by mlewand** [comment]
I did some additional hallway testing of this proposal and the reception was positive. Let's start with this subtle mark on upload progress.

We'll keep an eye on issues if our users find it too little readable, if so wel'll think about more straight-forward ways to express it.

At the same time remember that progress reporter type is totally customizable so people are able to implement anything, like the designs suggested by @RyszardB.

**Comment by mlewand** [comment]
Fixed with #1588.
