### ISSUE TITLE
Paragraph element text changes selected font-family to the default.

### ISSUE THREAD

**Issue by rkarina94** [ckeditor/ckeditor-dev#1590]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Open CKEDITOR 4 (using version 4.6.2) with a default font (Verdana in my case) set in the editor configurations.
2. Create a paragraph with a block of text in it.
3. Select all of the paragraph element and choose a different font (e.g. Calibri).
4. Select all of the paragraph element and change the content of the paragraph.

### Expected result

*What is the expected result of the above steps?*
The previously selected font (Calibri from step 3 above) is retained and should not be replaced with the default font (Verdana) when editing the paragraph, after selecting all of the paragraph element. 

### Actual result

*What is the actual result of the above steps?*
The previously selected font is replaced with the default font when editing the paragraph, after selecting all of the paragraph element. 

## Other details

* Browser: Google Chrome
* OS: Microsoft Windows 8
* CKEditor version: 4.6.2
* Installed CKEditor plugins: Default plugins for documentation editor, dragresize and tableresize.

**Comment by mlewand** [comment]
@rkarina94 how exactly are you setting the default font (which config you use and what exactly is the value)? Also note that we provide bug fixes only to the latest version, we're not backporting fixes to previous versions.

**Comment by rkarina94** [comment]
Hi @mlewand , 

I'm setting the default font in the config.js file:

CKEDITOR.editorConfig = function (config) {
...
  config.font_defaultLabel = 'Verdana';
};

**Comment by mlewand** [comment]
@rkarina94 I have tried this case and I'm unable to reproduce the issue. To make things easier I made it available online:

1. Open https://codepen.io/mlewand/pen/NBawJo
1. Focus the editor.
1. Select all (`ctrl/cmd+a`).
1. Pick a different font, e.g. "Comic Sans MS".
1. Select entire "Second." line.
1. Press backspace/delete.
1. Type "foo".

The typed text is formatted with "Comic Sans MS" font, so that's what you assumed in the _expected_ section.

It was working also with 4.6.2.

Can you check it?

**Comment by mlewand** [comment]
Actually I have been mislead by the fact that the font was in fact Comic Sans, but the dropdown did not reflect this. Reason why it does not is that chrome is putting `font` element instead of a `span` (you could see it in the elements path).

This is an issue in Chrome itself, you can find it being tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=742896

Please feel free to star it to get updates as it gets fixed.
