### ISSUE TITLE
type:bug plugin tableselection cannot apply rules to tr

### ISSUE THREAD

**Issue by bit-fan** [ckeditor/ckeditor-dev#1629]
It is a general problem that when I apply background-color to selected tr, it always apply to each individual td/th in that row, instead of the whole row.

Is there any way that I can apply to tr?

**Comment by msamsel** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
