### ISSUE TITLE
parse ckeditor content and apply tags instead of displaying them on the screen

### ISSUE THREAD

**Issue by shoudou** [ckeditor/ckeditor-dev#1642]
I have a problem parsing the content of CKEditor. I have saved the data into mongoDB but when I retrieve the content to display, it shows the tags instead of parsing them.

<p>The <strong>content had thi</strong>s formatting <em>when I saved it. This is how</em> I want it to display <strong><em>when I retrieve it from the database</em></strong>.</p>

But this is the content I am getting when I retrieve from the database. I want it to apply the tags but not displaying them. so I can have the same formatting as I entered.

`<p>The <strong>content had thi</strong>s formatting <em>when I saved it. This is how</em> I want it to display <strong><em>when I retrieve it from the database</em></strong>.</p>`

My html page is the following when I tried to display the content:

```
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>

</head>

<body>    
    <div id="pgContent">
        <div class="container">
            <span class="line"></span>
            <div id="msgContent" style="max-width:800px; font-size:16px;">&lt;p&gt;The &lt;strong&gt;content had thi&lt;/strong&gt;s formatting &lt;em&gt;when I saved it. This is how&lt;/em&gt; I want it to display &lt;strong&gt;&lt;em&gt;when I retrieve it from the database&lt;/em&gt;&lt;/strong&gt;.&lt;/p&gt;</div></div></div>

</body>
```
There is not jquery/javascript added to it. I added javascript but it is transforming the div into an editor again:

```
         CKEDITOR.replace('msgContent',
{
    entities: false,
    basicEntities: false,
    entities_greek: false,
    entities_latin: false,
    htmlDecodeOutput:true,
}
```
I used the following when writing the message:'

     `    CKEDITOR.replace('msgEditor')`
Thank you for now

**Comment by msamsel** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
