### ISSUE TITLE
Uncaught TypeError: n.listSelections is not a function

### ISSUE THREAD

**Issue by bspsz** [ckeditor/ckeditor-dev#1675]
Hi.
I'm using CodeMirror plugin in CKEditor 4.8.0, and after switching editor to code edit mode I get an error: 

> Uncaught TypeError: n.listSelections is not a function

and I can't switch back to wysiwyg mode. This problem occurs in Firefox 58 and Chrome 64. In config.js I have just: 
`config.extraPlugins = 'codemirror';`

Does anyone had that problem too? I reported this issue to authors of this plugin, but they sent me here ;)

**Comment by mlewand** [comment]
CKEditor does not feature any member such as `listSelections` (you could check it using our search box in [API docs](https://docs.ckeditor.com/ckeditor4/latest/api/index.html)).

If you're able to reproduce this issue with plain CKEditor 4 instance, without 3rd party plugin, then ofc this bug report is welcome.

@bspsz I'm sorry to bounce you back to CodeMirror team but the API causing the issue is probably the one from CodeMirror.
