### ISSUE TITLE
Move objToArray function to bender tools

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1690]
## Are you reporting a feature request or a bug?

Feature request

### Expected result

New function `bender.tools.objToArray`.

### Actual result

`objToArray` private function exists inside `imagebase/features/_helpers/tools.js`.

## Other details

The main reason for this change is the `objToArray` function could be used in many unit tests because when we are using the same editor for single test file `editor.widgets.instances` are removed and added for each test case. Editor instance is not destroyed between tests so widget instances have different ids. With this function it's easy to write unit tests using `editor.widgets.instances` regardless of other tests.

**Comment by Comandeer** [comment]
We already have `obj2Array` implementation inside our widget testing tools → https://github.com/ckeditor/ckeditor-dev/blob/9409e28dadf1564ec35987bcd888dfe6df23ef0d/tests/plugins/widget/_helpers/tools.js#L146-L152

Instead of moving it to `bender.tools`, I'd rather update old implementation with the new one as we don't use it anywhere outside widgets.

**Comment by jacekbogdanski** [comment]
After our talk F2F we decided to move `objToArray` to `bender.tools` and refactor widget tools to use new function because we cannot import modules between `_helpers/tools.js`.
