### ISSUE TITLE
UploadImage plugin copy/paste image from another source

### ISSUE THREAD

**Issue by ildmth** [ckeditor/ckeditor-dev#1708]
I am using UploadImage plugin, it works if i am copying pic's from PC, or from MS Paint.

If i copy image from some secure src, e.g. Facebook: right click on image, 'Copy Image'.
Then paste it to CK Editor like ctrl+V
It pastes img src instead of image itself. 
When i open ckeditor in without logging in to FB, i obviously dont see image in CK Editor.
How can i force editor always upload images as base64string on my server, to avoid such cases.

**Comment by msamsel** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
