### ISSUE TITLE
Problems Using Basic Features

### ISSUE THREAD

**Issue by gustavo-barros** [ckeditor/ckeditor-dev#1717]
I'm having some problems when trying to use some basic features of ckeditor. I'm creating a application that simulate some key presses by a keyboard rendered on browser screen, and I noted that there is no available option within the API that allow me to delete a already inserted character. Like for example when simulating a backspace key.

So, my doubts are mainly:

1- How can I delete characters in editor textarea? I tryed to use setData() with new fresh data, but the cursor is always reseted to the position 0

2- How can I select text from cursor position 'x' to 'y', for example 0 to 3?

3- How can I simulate the keys like, Enter, Space, Backspace, and other special keys?

4- How can I set the cursor position to position 'x'? Like for example, postion 4? Assuming that 0 is the beginning?

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.8.0

**Comment by msamsel** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
