### ISSUE TITLE
 editor.contextMenu.open();

### ISSUE THREAD

**Issue by MoatazGitHub** [ckeditor/ckeditor-dev#1723]
Hello Please help me using this function

 editor.contextMenu.open();
in documentation
it take this params
open( offsetParent, [ corner ], [ offsetX ], [ offsetY ] )

https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_plugins_contextMenu.html

so please provide example how can I use it ?

**Comment by engineering-this** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
