### ISSUE TITLE
image2 plugin: el.getFirst( 'a' ) is null in upcastWidgetElement()

### ISSUE THREAD

**Issue by damien-git** [ckeditor/ckeditor-dev#1731]
The image2 plugin crashes with HTML code like
```
<div style="text-align:center">
    <figure class="image">
        <div><img ...></div>
        <figcaption>
            ...
        </figcaption>
    </figure>
</div>
```

`el.getFirst( 'img' ) || el.getFirst( 'a' ).getFirst( 'img' )` fails if the img is inside a div (which is valid markup).

The crash can cause all content to be lost.

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

I tried to use this markup here: https://cdn.ckeditor.com/4.8.0/full-all/samples/old/image2/image2.html And it worked fine for me. Please provide better description.
```
<div style="text-align:center">
<figure class="image" style="display:inline-block"><img alt="Saturn V" src="assets/image1.jpg" width="200" />
<figcaption>Roll out of Saturn V on launch pad</figcaption>
</figure>
</div>
```

**Comment by damien-git** [comment]
Sorry about the template. As I wrote, the img has to be inside a div. Please try:
```
<div style="text-align:center">
<figure class="image" style="display:inline-block">
<div><img alt="Saturn V" src="assets/image1.jpg" width="200" /></div>
<figcaption>Roll out of Saturn V on launch pad</figcaption>
</figure>
</div>

```

**Comment by msamsel** [comment]
I'm sorry but this kind of markup wasn't considered to be supported by `image2` plugin. That's why there is no logic which would be able to support embedding this kind of markup by default.

Option which I see for handling this error is to create listener catching [`paste` event](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#event-paste). Inside this listener, you could process inserted data and remove superfluous `<div>`. This will give you markup coherent with markup expected by image2 plugin.

**Comment by seliver** [comment]
I'm having the same issue, but this time instead of a <div> there's a <p>.
I think that it doesn't make sense for CKeditor to crash because of a markup incoherency with image2. It should probably give a warning, but never crash.

About the solution @msamsel gave, I don't see the connection of "catching paste event" with this problem.
