### ISSUE TITLE
Toolbar options in ckeditor loaded on a jquery shadowbox closes the shadowbox on click 

### ISSUE THREAD

**Issue by aakashhs** [ckeditor/ckeditor-dev#1768]
Hi,

I am working on an application that uses ckeditor 3.4.1. I am loading ckeditor on a jquery shadowbox. On clicking of any of the toolbar options, the shadowbox closes ! 

Please, upgrading verisons of either shadowbox or ckeditor is not an option for me.

Thanks & regards, 

Aakash

**Comment by engineering-this** [comment]
CKEditor 3 is not being developed anymore. If you can't upgrade to new version is not an option CKEditor team is not being able to help you.

However if you decide to upgrade to CKE4 and problem is still existing please provide information on how to reproduce your issue. Also when reporting issues in future please be more specific with issue details. The more detailed you are when describing issue the more likely we will be able to reproduce and fix problem.

**Comment by aakashhs** [comment]
Apologies! I have updated to version 4. 
alert(CKEDITOR.version) shows "4.4.6 DEV".
However the issue persists.

![screenshot](https://user-images.githubusercontent.com/21873849/37269796-290ccec2-25f2-11e8-8ab8-4985fc1b84b3.png)

The screenshot above shows the ckeditor loaded on a jquery shadowbox. 

On click of any of the toolbar options, the entire shadowbox closes!

below is the code for initializing ckeditor. May be some extra code to be added or i have missed something? Thankyou! 

`function initializeCkeditor(selector) {
        var editor_config = {
            skin: 'cgp',
            resize_enabled: true,
            height: 290,
            removePlugins: 'elementspath,image,forms,flash,styles,htmldataprocessor',
            toolbarCanCollapse: false,
            toolbar:
                [[ 'Italic', '-', 'NumberedList', 'BulletedList', 'Link', 'Unlink', 'Paste' ]]
        };
        if(typeof CKEDITOR != 'undefined') {
            $.each(selector, function(idx, data){
                CKEDITOR.replace(this.id, editor_config);
            });
        }
    }

initializeCkeditor($("textarea#content"));`

**Comment by engineering-this** [comment]
I'm assuming this shadowbox (as most of lightboxes) has some event listener `onClick` that will fire whenever you click outside of shadowbox and close the shadowbox. It is very likely that the CKEeditor is not recognized as part of the shadowbox, hence clicking on the Editor closes the shadowbox. My suggestion would be to try stopping [event propagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) on some wrapping element that contains CKEeditor. But I can't guarantee it will work.

This is not a technical bug, so please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
