### ISSUE TITLE
Bug: "View Source" button not working after pasting content

### ISSUE THREAD

**Issue by jgibba** [ckeditor/ckeditor-dev#1775]
-- ckeditor v4.5.3 -- When pasting and saving lots of html content with images in the editor in view source mode and reopening the editor, the View Source button becomes disabled and can no longer view source. The editor successfully renders html that is editable but can no longer view source to make any additional changes. Attached are the only ckeditor errors found - this has been a recurring issue, does anyone have a solution?

<img width="1271" alt="ckeditor_viewsource_error" src="https://user-images.githubusercontent.com/5321848/37228275-0d1e378c-23ae-11e8-818d-1c027bad3531.png">

* Browser: Chrome latest
* OS: MAC OS
* CKEditor version: 4.5.3
* Installed CKEditor plugins: none

**Comment by msamsel** [comment]
Hi,
we're fixing bugs by launching updated version of CKEditor, that's why please check if the exists with current version of CKEditor (4.8.0).

**Comment by amanvishnani** [comment]
Hi,

We have tested this issue on latest Google Chrome browser with CKEditor (4.8.0). The problem seems to persist. The HTML code has an image tag with base64 data as it's source and it freezes when we try to select all (Ctrl + A) and copy it.

I checked developer console and didn't found any logged JS errors. It would be helpful if you guys can help me on the same.

- Browser: Chrome Latest
- OS: Windows
- CKEditor: 4.8.0

**Comment by jgibba** [comment]
@msamsel Is there a temporary patch fix for this as issue was able to be reproduced?

Thanks,
Jon

**Comment by mlewand** [comment]
@amanvishnani @jgibba could you guys provide more information on the content? How much bytes is this? It would help if you could post the content to gist/jsfiddle or alike.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
