### ISSUE TITLE
Empty #text " " node after <ul>-tag

### ISSUE THREAD

**Issue by akzeitlos** [ckeditor/ckeditor-dev#1779]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Making a list (ul)
2. Output in Frontend is 
" "
<ul><li>...</li></ul>
" "
3. Thte " " is an empty #text node and produces an empty line!

### Expected result

Without the empty lines

### Actual result

There are empty lines

**Comment by akzeitlos** [comment]
Found out that I have to use fillEmptyBlocks = false. But where to put it?!? There is no config.js

**Comment by jacekbogdanski** [comment]
Hello,

You can learn how to configure CKEditor from [Setting CKEditor Configuration](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_configuration.html) guide. 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore if my answer doesn't solve your problem leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
