### ISSUE TITLE
Issue in Ordered List or Unordered List (Ckeditor 4.8.0)

### ISSUE THREAD

**Issue by lakhanOpen** [ckeditor/ckeditor-dev#1783]
Hey
       We are facing an issue on version 4.8.0 when ever we put Ordered List or Unordered List in editor and put a break point in between and then try to style that it style (H1, H2 or <i>..) complete element (**LI**) rather than selected text or good to say preferred part  of element

**Comment by jacekbogdanski** [comment]
Hello,
I'm not sure what do you mean about adding break point between List elements. Could you give more information about the issue? You could paste HTML markup from `Source` or use [Codepen](https://codepen.io) to reproduce the issue.

**Comment by lakhanOpen** [comment]
Hello,
Let me explain by exapmle

I want below Ordered List or Unordered List dynamic using editor
<ol>
	<li>
		<h1>Title 1</h1>
		<p>Some text</p>
	</li>
	<li>
		<h2>Title 2</h2>
		<p>Some text</p>
	</li>
</ol>

I want to apply heading text or normal text on select word in <li> but right now if i apply heading text then it will be applied to whole <li> tag instead of selected word in <li>
![ckeditor](https://user-images.githubusercontent.com/914436/37341841-e34ebb78-26e8-11e8-85cb-f798559a1216.jpg)

**Comment by jacekbogdanski** [comment]
Hello again,

you have to distinguish `block level` styles and `inline level` styles. In short, you can say that block level styles are applied to whole element content and inline level styles changes selection. You can find more about differences in our [style types guide](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_styles.html#style-types).

Coming back to your issue, you could use `inline styles` from `Styles` drop-down to change the appearance of your selection.

If it doesn't resolve your problem and you think it's CKEditor issue feel free to provide a feedback so we will investigate it deeper. Don't forget to enclose reproduction steps and some code sample with the issue e.g. using [Codepen](https://codepen.io) or pasting a plain code here. 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. If you need help with CKEditor configuration please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
