### ISSUE TITLE
autogrow resizeEditor costs 6 seconds during a 11 seconds fast key stroke period

### ISSUE THREAD

**Issue by XipanXiao** [ckeditor/ckeditor-dev#1798]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)
1. Load a large text document (86K in my case) with a Chrome browser.
2. Press F12 to open the Developer Tools, click the 'Performance' tab.
3. Click 'Record' (the most left round button).
4. Start type random characters into the CKEditor, for about 10 seconds.
5. Stop recording. 

### Expected result
The typing should be smooth.

### Actual result
Key strokes are laggy.

Check the 'Button-Up' view of function calls:
resizeEdtior appears at No. 3 in the total time list. See the attached screen shot.

* Browser: Google Chrome Version 65.0.3325.162 (Official Build) (64-bit)
* OS: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
* CKEditor version: 4.5.4
* Installed CKEditor plugins: autogrow, etc.
![resizeeditor](https://user-images.githubusercontent.com/3975622/37435341-2196198c-27a0-11e8-9519-e1cc8b8cd910.png)

**Comment by msamsel** [comment]
I was able to confirm the issue. [This page](https://cdn.ckeditor.com/4.9.0/full-all/samples/old/autogrow/autogrow.html) was used for testing. 
1. Paste a lot of text (I used sth lik 100 paragraphs)
2. Start typing at the end

Actual:
- typing is pretty laggy. It's visible jumps of editor size

**Comment by engineering-this** [comment]
This issue is upstream.

Any html element with `contenteditable="true"` e.g. `textarea` filled with very long text will make Chrome very laggy. Here is issue from chromium issue tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=582844

If that is problematic for users I'd suggest setting [`config.autoGrow_maxHeight`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-autoGrow_maxHeight) to some reasonable value until it is fixed in Chrome.

After some testing I found that Safari seems to be working ok. Only huge amounts of text makes it laggy, and it is few times more lines of text than in Chrome. Also lags in Safari seems to be not significant in comparisement to Chrome.

Firefox is dealing even better with lengthy texts and I don't see any lags at all.
