### ISSUE TITLE
Copy text from PDF not retaining formatting 

### ISSUE THREAD

**Issue by ratneshoza** [ckeditor/ckeditor-dev#1847]
Step to reproduce 

1. Copy content from pdf
2. Past content into editor
3. Content which is past should show the formatting.

### Expected result

*What is the expected result of the above steps?*

Copy content from pdf should carry css fromatting to editor 

*What is the actual result of the above steps?*

copy content from pdf not carry css formatting to editor

* Browser: chrome
* CKEditor version: 4.7.2
* Installed CKEditor plugins: attached list of plugin (i.e. plugin_list.png)

**Comment by ratneshoza** [comment]
We are using this window OS and using adobe PDF viewer.

**Comment by ratneshoza** [comment]
We are usind Window OS and abode as pdf viewer. please find the attached pdf

**Comment by mlewand** [comment]
@ratneshoza I'm sorry, I don't see any attached pdf file. Please try once again.

**Comment by ratneshoza** [comment]
srry no able to attache, but please find the test pdf download link https://dev.ckeditor.com/raw-attachment/ticket/10726/html_export.pdf

**Comment by ratneshoza** [comment]
Hi @mlewand are you able to download pdf link for testing the issue?

**Comment by mlewand** [comment]
Yes thanks @ratneshoza now we can have a full picture. Unfortunately we're _unable_ to retain any formatting from that.

The reason for this is that neither Adobe PDF Reader DC nor Chrome/Edge bundled PDF readers provide HTML representation of copied content. So we have no information on formatting at all - it's just plain text.

To explain more why is that happening: as the app puts something into your OS clipboard, it can put the same content in multiple representations. For instance when copying content from MS Word it might put selected content in following representations:

*  MS Word OOXML - their native format, that retains all the (meta)information - but very little apps support it
* HTML Format - requires conversion, and some compromises (due to HTML limitations) but is understood by much, much more apps - including CKEditor 4
* Plain text format - the most basic format, does not allow you to put any semantic value but unserstand by the most apps (starting from rich text editors ending on simple notepads, code editors)

It can provide much more, for instance it could also provide a bitmap (image) representation, so that you can paste it into your graphic app like an image.

In this case PDF readers save only plain text format, so we have no way on retaining additional formatting.

It should be reported to upstream app author (for instance Adobe) as a feature request, and I find it to be a valuable feature, as many other apps would benefit from that.

On a side note, Firefox implements a different PDF viewer which is the only one to put HTML format into the clipboard! But that's representation is… well it's not the best 🙂

**Comment by ratneshoza** [comment]
Thanks @mlewand for detail explanation :)

**Comment by mdabidali9** [comment]
Hi All
I copied content from adobe pdf reader and pasted in CKEditor but I didn't get the same format and styles which I have copied from that pdf file. 
Why it's having that issues in Pega and CKEditor.
[sampleresponseletters.pdf](https://github.com/ckeditor/ckeditor4/files/4493668/sampleresponseletters.pdf)

Anyone would you help me to solve these issues. 
If I open same pdf file with WPS and copied from it and paste in Document Editor of CKEditor then I'm getting the same format and styles which I have copied from that pdf file.
