### ISSUE TITLE
Not able to open the CK editor on my local desktop

### ISSUE THREAD

**Issue by syedyasser** [ckeditor/ckeditor-dev#1854]
## Are you reporting a feature request or a bug?
Request
 I am Not able to open the CK editor after downloading it on my local destop 

* CKEditor version: … New
* Installed CKEditor plugins: … All

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
