### ISSUE TITLE
Autogrow doesn't work on hidden editors

### ISSUE THREAD

**Issue by leealexey** [ckeditor/ckeditor-dev#1862]
## Are you reporting a feature request or a bug?

 Bug

## Provide detailed reproduction steps (if any)

I have an editor inside of a hidden div, so I show it to the user on demand, but when user reveals the editor with predefined content, Autogrow doesn't resize the window until user clicks inside of it

### Expected result

I expected that the editor will be resized after it shows up.

### Actual result

The editor is not resized after it was revealed

## Other details

* Browser: Chrome 65.0.3325.181
* OS: MacOs 10.13.3
* CKEditor version: 4.7.3
* Installed CKEditor plugins: autolink,basicstyles,dialogui,dialog,image,autogrow

**Comment by jacekbogdanski** [comment]
Hello,

with default settings `autogrow` plugin will resize your editor only when you start editing editor's content. You can change this behavior by setting [`autoGrow_onStartup`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-autoGrow_onStartup) option. 

If it doesn't resolve your problem and you think it's CKEditor issue feel free to provide a feedback so we will investigate it deeper. Don't forget to enclose reproduction steps and some code sample with the issue e.g. using [Codepen](https://codepen.io) or pasting a plain code here. 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. If you need help with CKEditor configuration please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
