### ISSUE TITLE
Preview While in Source Edit Mode Triggers Injected Scripts

### ISSUE THREAD

**Issue by johnkevincheng** [ckeditor/ckeditor-dev#1876]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)
1. Open an editor with both Source and Preview buttons are enabled. For example here: https://sdk.ckeditor.com/samples/fullpreset.html
2. Click on Source to open the source editing pane.
3. Insert the script below (from double-quote to the ">") in any blank line:
`"><img src=x onerror=alert(7)>`
4. While still in the Source mode, click on Preview.

### Expected result
Script will not run.

### Actual result
Alert box with "7" displayed.

## Other details
* CKEditor version: 4.x

Current workaround is to disable Preview during Source mode https://stackoverflow.com/questions/47786039/how-can-i-disable-the-preview-button-while-in-source-mode-with-ckeditor-4, but our security team does not fully accept this at the moment.

**Comment by wwalc** [comment]
Please do not report security issues in a public issue tracker. It is unethical/irresponsible as potentially you are exposing all end users on a huge risk, in case you found a real 0-day vulnerability.

The correct way of reporting security issues is mentioned in the issue template:

> Please **do not report security issues here**, use the contact form at https://ckeditor.com/contact/ instead.

and it's done this way not to "hide" potential issues, but to give us time to fix the issue, release it to the community and then disclose it.

---

Now, regarding the issue. What you are observing is not a security issue. Entering the XSS vector by yourself into the editor can be compared to executing JavaScript using console in web browser developer tools.

Additionally, the mentioned preview plugin exposes the [contentPreview](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR.html#event-contentPreview) event that you can use to eventually strip such self-XSS attacks.

The most important thing to understand here is that you cannot expect CKEditor to provide a complete anti-XSS defence system for your application. At any moment the attacker may destroy the editor using the dev console, getting access a plain textarea instead or can intercept the POST request and send any malicious data with XSS he wants to your application. Even with most sophisticated anti-XSS systems, CKEditor could not protect you in such cases.

That's why the right place to implement the anti-XSS filters is the "server side" part of your application. Now, suppose that we have an application where the user did not enter the XSS vector in the source mode, but the XSS vector was already in the HTML content when the editor has been started (because some previous user entered it already). It would mean that the application is vulnerable, because it renders content (either for reading or for editing) without proper data sanitisation.

If anything is still unclear, or you would like to report a different security issue, please use the contact form at https://ckeditor.com/contact/.
