### ISSUE TITLE
paste from word when the page has pictures

### ISSUE THREAD

**Issue by yiqianglin** [ckeditor/ckeditor-dev#1886]
I try to parse from Microsoft word, when it has a picture,  the source code become:
![image](https://user-images.githubusercontent.com/15794229/38685499-a6e4906c-3ea4-11e8-814a-600cf54d013d.png)

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.
