### ISSUE TITLE
Improve visibility on npm

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-dev#1903]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

On https://www.npmjs.com/package/ckeditor I can see that we have a "richtext" keyword. From what I saw, it's not going to match with "rich-text editor" phrase because npm does a rather bad job at fuzzy matching them. It's good to be explicit. We have both "rich-text" and "richtext" in CKEditor 5, but I'm thinking now that perhaps it'd be even better to have "rich", "text", "editor" – all separate. Although... if "rich-text" query will be treated as a single word then it may not match "rich" + "text"... :D

**Comment by Reinmar** [comment]
One more thing, in fact. Check out the quality and maintenance indexes:

![image](https://user-images.githubusercontent.com/156149/38981032-a5d9eb26-43be-11e8-888a-f81d4845c8d3.png)

Why does `ckeditor-dev` gets more? Because its `repository` points to this repo. And `ckeditor`'s to the `ckeditor-releases` in which there are barely any issues.

I think that it'd be good to point to this repository from both packages. Regardless of the fact from where the release really happen.

**Comment by wwalc** [comment]
CC @wojtekidd

**Comment by wojtekidd** [comment]
Do whatever you feel is suitable for npm.

**Comment by mlewand** [comment]
It make sense to switch to a common repo. As for keywords "rich text" seems to match "rich-text", "rich text" but not "richtext" - so thinking like that we would need `rich text` and `richtext`.

**Comment by wwalc** [comment]
> As for keywords "rich text" seems to match "rich-text", "rich text" but not "richtext" - so thinking like that we would need rich text and richtext.

Unfortunately yes, that's why in case of CKEditor 5 we need to use "ckeditor", "ckeditor 5" and "ckeditor5" keywords together.

If not the issue title, I'd report it as a separate ticket, but since it's about Improving the visibility on npm...

I believe **the scope of this ticket is much wider** than correcting keywords, it should include:

 - Creating separate readmes for NPM, that focus more on selling the product (using keywords that we want to promote on @wojtekidd) and on developer experience installing the editor from NPM, than about the structure of the GitHub repository. For example one does not know exactly what will be installed by `npm i ckeditor` - the readme is completely confusing there. The copies of GitHub readme do not fit there completely. In other projects we decided to start using `README.release.md`  to be used during deployment to npm and it seems like the right strategy here.
 - Updating release scripts to make sure the correct readme is deployed.
 - Using the right keywords.

**Comment by wwalc** [comment]
Dooh. This is bad: https://www.npmjs.com/package/ckeditor-releases We need to take it over.

**Comment by Reinmar** [comment]
DO READ https://npms.io/about

**Comment by mlewand** [comment]
I have pushed the draft to https://github.com/ckeditor/ckeditor-dev/blob/t/1903/.npm/README.md

Must haves:

* We need a screenshot. The question here is what toolbar should we use. I'd go with the _default_, as if we go with customized/reduced people might get confused after installation that this is a completely different thing. 
![image](https://user-images.githubusercontent.com/5353898/43321937-99ca040a-91ad-11e8-992b-250f8388a3a2.png)

* The text needs to be reviewed.
* Keywords checked.
* Checking on how to change the `README.md` for npm alone. If not possible, then we need adjust building scripts.

Nice to haves:

* I was thinking that it could be nice to mention, and link to CKEditor 5.

And here's how it would look like today:

![image](https://user-images.githubusercontent.com/5353898/43322315-6e36fe28-91ae-11e8-95aa-5b9db967f44d.png)

**Comment by wojtekidd** [comment]
I've added some minor changes.

**Comment by wojtekidd** [comment]
> I was thinking that it could be nice to mention, and link to CKEditor 5.

Actually we might do reference CKE4 in CKE5 npm readme to decrease any possible confusion. 

Just a simple line like:

If you are looking for CKEditor 5, here's a link to the relevant npm package: [https://www.npmjs.com/package/ckeditor5](https://www.npmjs.com/package/ckeditor5)

[Find out more about differences between CKEditor 4 and CKEditor 5.](https://support.ckeditor.com/hc/en-us/sections/115001489149-The-CKEditor-4-and-CKEditor-5-Comparison)

**Comment by mlewand** [comment]
I added these last modifications to the readme:

* Added CKE5 link, @wojtekidd please verify that I decided to put just a link to CKE5 npm package. I think second link is redundant here and if anything, it should be mentioned in CKE5 readme for the time being.
* Changed the preset information (for dev it's full preset).
* Removed stray Keywords section - npm adds it automatically

Now the only thing that we're missing here is the image. @RyszardB could you create one?

Also @wwalc asked me whether there's a different version for the CKE4 release pacakge (as opposed to dev). I find we need only one difference there: the preset that is provided by package. For dev version it's full-all for release version that's standard-all.

Other than that installation steps and any other points are the same, so let's keep it simple.

**Comment by mlewand** [comment]
@wojtekidd please have a final look at the readme, and confirm that everything looks good.

**Comment by wwalc** [comment]
It is really important to explain what one in ckeditor-dev gets, because this distribution is in fact a bit useless (unless one really knows what he is doing). Accidentally, by making a nice readme for it and posting a screenshot of a full preset, we may cause that it will have a larger number of accidental downloads than today, just because one will start thinking that in this package he will get color buttons and stuff like that.

As a consequence, some unaware people may download it "to have more buttons" and then complain that it is very slow or just stop using it because of the slowness.

So ckeditor-dev should have some text explaining what's the purpose of this package and for who it's targeted. Also the user should be linked to other places where he can find "build" distributions of CKEditor, especially where one can find builds with "more buttons" and/or hints/links on how to create one.

**Comment by RyszardB** [comment]
full preset??? where can I find an example of the full preset and moono-lisa skin? 

my proposition:
![1](https://user-images.githubusercontent.com/17498197/43948618-9690d79e-9c8b-11e8-8a8a-aac9cb564786.png)

**Comment by mlewand** [comment]
@RyszardB it's http://cdn.ckeditor.com/4.10.0/full/samples/

**Comment by RyszardB** [comment]
![2](https://user-images.githubusercontent.com/17498197/43949579-39a34fa0-9c8e-11e8-8d6d-eb9d32a292f3.png)

**Comment by AnnaTomanek** [comment]
The screenshot content is confusing - I understand the intentions, but in fact, none of it is included in the `ckeditor-dev` package. Hundreds of add-ons are in the add-ons repo, unavailable on npm, and both EI and CKF are paid products.

@RyszardB 
Please use the content from one of the existing demos, with an image etc. Something that would simply look good, like https://ckeditor.com/ckeditor-4/#article

**Comment by RyszardB** [comment]
![artboard-2](https://user-images.githubusercontent.com/17498197/44386364-9873d800-a522-11e8-8e80-16db167ebe4a.png)

![artboard-1](https://user-images.githubusercontent.com/17498197/44386365-9873d800-a522-11e8-8843-c3258990c662.png)

**Comment by mlewand** [comment]
OK I added the image, slightly adjusted dev readme, and added readme in `ckeditor-releases` repo (on a branch). You can see it here:

* [npm readme for **release** version](https://github.com/ckeditor/ckeditor-releases/blob/t/1903/.npm/README.md)
* [npm readme for **dev** version](https://github.com/ckeditor/ckeditor-dev/blob/t/1903/.npm/README.md)

Now time for scripting, there needs to be a script that puts the file in main directory, as npm does not support pointing to a custom readme file.
