### ISSUE TITLE
Templates -> 'Image and Title' image not visible after save

### ISSUE THREAD

**Issue by roohitgandhi** [ckeditor/ckeditor-dev#1909]
## bug

Pre requirements: 
plugins: base64image, templates

1. Click on 'templates' 
2. Select "Image and title" from the options.
3. Double click on the blank image, this will open a popup with two tabs "General", "advanced".
4. Select "General" tab click "Choose file" and browse to file from there.
 (in networks see there is a call to "ckeditor/plugins/base64image/dialogs/base64image.js?t=G87E")
5. Click "save" button of form to save the form records.

Expected: 
It should set the src of img tag the encoded string.

Actual:
The src of the image is blank, so when try to open the same record, it did not show image.

* Browser: Chrome Version 65.0.3325.181 
* OS: Windows 10
* CKEditor version: 4.5
* Installed CKEditor plugins:base64image, templates

**Comment by engineering-this** [comment]
The plugin you are referring to (`base64image`) is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
