### ISSUE TITLE
`listTypeToStyle` transformation method doesn't exist

### ISSUE THREAD

**Issue by karoltarasiuk** [ckeditor/ckeditor-dev#1939]
## Bug

Added plugin and have this error: `TypeError: c[a] is not a function`. After debugging I narrowed it down to the fact that the code is trying to use `listTypeToStyle` transformation method, which simply doesn't exist: https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_filter_transformationsTools.html

Am I missing something?

### Expected result

Plugin works after adding to CKEditor.

### Actual result

CKEditor simply breaks. Can't recover.

## Other details

* Browser: …
* OS: MacOS High Sierra 10.13.2
* CKEditor version: 4.5.6
* Installed CKEditor plugins:
```
extraPlugins:
            'div,indentblock,sharedspace,magicline,image,div,confighelper,widget,lrn_latex,' +
            'lrn_math,lrn_mathml,lrn_normalize,lrn_simplefeature,pastetext,pastefromword,justify,' +
            'showblocks,colorbutton,panelbutton,floatpanel,blockquote,lrn_datatable,stylescombo,' +
            'lrn_underlinedindicator,lrn_imageresize,liststyle'
```

**Comment by msamsel** [comment]
Hi @karoltarasiuk,

From what I checked, you have right CKEditor 4.5.6 hasn't got `listTypeToStyle` transformation: https://github.com/ckeditor/ckeditor-dev/blob/4.5.6/core/filter.js

Unfortunately you are using 3rd party plugins, which most probably break with this version of editor.  I suspect that one of those addon is using mentioned transformation. I can't help you with those plugins, because CKSource is not author of them.

What I suggest is toupdate CKEditor to current version where `listTypeToStyle` is available or to reach plugin's author to fix them.

**Comment by karoltarasiuk** [comment]
Hmm interesting... the plugin is: https://github.com/ckeditor/ckeditor-dev/tree/master/plugins/liststyle I've originally visited that page and created issue from there, so didn't even give you the name of the plugin as assumed the repo is specific to it. Sorry for that. Updated description now.

So it seems that the plugin is not really 3rd party, unless it's in your repo by mistake :/ Is it possible that some plugins may be outdated? I couldn't find any info about what other stuff this plugin relies on. There is no readme.

**Comment by msamsel** [comment]
@karoltarasiuk `liststyle` plugin, and `listTypeToStyle` transformation are two different things.
CKEditor in version 4.5.6 had `liststyle` plugin which didn't use `listyTypeToStyle` transofrmation, because this transformation wasn't present in the editor back then.
Please take a look at sample with 4.5.6: https://cdn.ckeditor.com/4.5.6/full-all/samples/ it works perfectly fine without errors. :)
That's why I suspect other (3rd party) plugins to generate such error.

I recommend update CKEditor version to current version where this transformation is available.
