### ISSUE TITLE
Simple-Ruler is not working according to Word Ruler

### ISSUE THREAD

**Issue by roshan-patil** [ckeditor/ckeditor-dev#1942]
## Are you reporting a feature request or a bug?

bug

## Provide detailed reproduction steps (if any)

1. We cannot change the margin of selected text using simple-ruler.
2. When we paste from the word, the ruler setting cannot applicable to text or paragraph.

### Expected result

*What is the expected result of the above steps?*

Ruler has to be work according to word ruler and settings of word ruler is automatically applied to the CKeditor ruler.

### Actual result

*What is the actual result of the above steps?*

Word Ruler settings cannot display in CKEditor When we paste from the word which contain paragraph with word ruler settings. 

## Other details

* Browser: Chrome
* OS: Windws 7
* CKEditor version: 4.9.2
* Installed CKEditor plugins: Simple-Ruler

**Comment by roshan-patil** [comment]
Installed CKEditor plugins: Simple-Ruler, Pastefromword

**Comment by Comandeer** [comment]
The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

**Comment by roshan-patil** [comment]
thanks..
