### ISSUE TITLE
JAWS reads some random values along with the name of the control and its instructions inside "Styles" and "Colors" toolbar of CK Editor.

### ISSUE THREAD

**Issue by sagar17sep** [ckeditor/ckeditor-dev#1948]
BUG

## Provide detailed reproduction steps (if any)

1. Bring Focus on CK Editor toolbar and Navigate to CK Editor toolbar using Alt + F10 and navigate to controls inside "Styles" and "Colors" toolbar.
2. Start JAWS.

### Expected result

JAWS should only read the name of the control and its associated instructions.

### Actual result

JAWS reads some random values along with the name of the control and its instructions. It reads javascript....left parent....

## Other details

* Browser:  IE 11.309.16299.0
* OS: Wndows 10
* CKEditor version: 4.6.2
* Installed CKEditor plugins: …

**Comment by sagar17sep** [comment]
Please look to the above mentioned issue.

**Comment by sagar17sep** [comment]
Could you please look to the above mentioned issue on high priority.

**Comment by mlewand** [comment]
We have checked this issue and it clearly looks like a third party issue. Note that we do not have support for IE+JAWS.

I was able to reproduce the problem you're describing on IE+JAWS but the issue did not occur on Firefox+JAWS.

This looks clearly like some browser/screen reader issue since we provide meaningful labels for the buttons. That must stop the screen reader from reading href - but in this particular case it does not.

I'd suggest reporting this issue in the proper 3rd party issue tracker, as it's a moderate accessibility issue.
