### ISSUE TITLE
Names of the CK editor toolbar buttons are missing

### ISSUE THREAD

**Issue by sagar17sep** [ckeditor/ckeditor-dev#1953]
BUG:-

**Provide detailed reproduction steps (if any)**
1. Navigate directly to URL : http://onefarm0990r.onefarm0990rdom.extest.microsoft.com/OneFarm/main.aspx?appid=f659ee53-c243-e811-8135-000d3af9e9d2&pagetype=entityrecord&etn=adx_ad&id=68a12748-8f44-e811-8135-000d3af9e9d2#
or follow below steps:
Navigate to application URL using above credentials.
2. Navigate to Sitemap icon->(...)-> Select Portals.
3. Under heading Ads->"Ads".Select any record from the grid to open the record page.
4. Navigate to CK Editor toolbar using Alt + F10 and navigate to "Insert Toolbar" section.
5. Open Inspect Tool. 
6. Navigate to "Image" and "Table" buttons

**Similar issue is observed in following pages**
1)NewWebFile:Navigate to SiteMap icon->Content->"Web File".Select "New" from command bar.
2)PortalsContentSnippetsRP-->Navigate to SiteMap icon->Content->"Content Snippets". Select any record from the grid to open the record page.
3)PortalsShortcutsRP-->Navigate to SiteMap icon->Content->"Shortcuts". Select any record from the grid to open the record page.
4)PortalsWebFilesRP-->Navigate to SiteMap icon->Content->"Web Files". Select any record from the grid to open the record page. 
5)NewAd:Navigate to SiteMap icon->Ad->"Ads".Select "New" from command bar.
6)NewCommunityIdeaForum:Navigate to SiteMap icon->Community->Ideas->"Idea Forums".Select "New" from command bar.
7) CommIdeaForumsRP: Navigate to SiteMap icon->Community->Ideas->" Idea Forums". Select any record from the grid to open the record page.
8) AddNewBlogPost: Navigate to SiteMap icon->Blogs->"Blogs". Select any record from the grid to open the record page. Navigate to "Blog Posts" Tab from Related. Click on "Add New Blog Post" button
9)CommIdeasRP: Navigate to SiteMap icon->Community->Ideas->" Ideas". Select any record from the grid to open the record page.

**Expected result**
The name of the buttons("Image" and "Table") should be present. 

**Actual result**
The name of the buttons("Image" and "Table") inside "Insert Toolbar" section are missing. Also, help text (value of title attribute) is inappropriate to describe the context.

**Other details**
Browser: … Egde 41.16299.248.0
OS: …Windows 10
CKEditor version: …4.6.2
Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Hello,

provided URL is invalid. Also, we cannot take credit for some custom CKEditor configuration. Please, try to reproduce your issue with clean CKEditor instance and provide some easy reproduction steps so we will be able to investigate it. You could use [codepen](https://www.codepen.io) or similar application to create example editor with existing issue.

If you will be able to reproduce the issue feel free to open a new ticket using our template. Although, I'm closing this one because it doesn't reflect the issue and it's more like support question.

If you need help configuring CKEditor and have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
