### ISSUE TITLE
Unable to add default style to root element/inline of editable

### ISSUE THREAD

**Issue by abhrabhattacharyya** [ckeditor/ckeditor-dev#1955]
## Are you reporting a feature request or a bug?

doubt, may be bug

## Provide detailed reproduction steps (if any)

I'm using ckeditor as a compose e-mail editor tool. As per the requirement the font-family should be 'Verdana'. Now, I can change the style of the editor on browser by changing in the content.css but when I'm sending the html as a mail-body the default style doesn't get added. Only the selected styles from the toolbar gets added as inline style.

*What is the expected result of the above steps?*

So, even if the sender(user) doesn't select any style from the toolbar, the receiver of the mail with html body should have the default style along with the text.

*What is the actual result of the above steps?*

Unable to add style even if we add value as props (only text gets added)

Used in React application with react-ckeditor-wrapper@1.1.2

* Browser: All
* OS: Windows
* CKEditor version: 4.7.3
* Installed CKEditor plugins: basic

**Comment by jacekbogdanski** [comment]
Hello,

If I understand you correctly you would like to force CKEditor to add default styles into DOM HTML. Unfortunately, It's not so easy because with large HTML DOM Tree it could get messy and currently we are not supporting this feature. 

There is some workaround which could help you:
1. Set [`config.font_defaultLabel`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-font_defaultLabel) configuration option. It will preselect required font.
1. Use custom CSS for editor content so it will have default styles on an editor load. You can add custom CSS class using [`CKEDITOR.addCss`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR.html#method-addCss) function or by modifying `contents.css` file. For your email you could enclose css by `style` tag. 

If this feature is essential for your application feel free to request new issue with appropriate feature request. If community will be interested in this feature we will consider implementing it.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, so if you have additional problems with this issue please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
