### ISSUE TITLE
CKEditor - Source doesn't load

### ISSUE THREAD

**Issue by Shashikanth4295** [ckeditor/ckeditor-dev#1978]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to the application page where we need to view source
2. Click source button
3. Doesn't load any content

### Expected result
Need to show the html source code

### Actual result

Doesn't load  the code

## Other details

* Browser: Chrome
* OS: Windows 7
* CKEditor version: 4
* Installed CKEditor plugins: Not sure

Need to show the exact issue. Please let me know when we can have a screen share.

**Comment by jacekbogdanski** [comment]
Hello,

you already reported this issue #1896 #1879.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
