### ISSUE TITLE
Chrome Key event problem when typing Chinese Chuyin(phonetic symbol) in nth-child(2) td 

### ISSUE THREAD

**Issue by jiimmysu** [ckeditor/ckeditor-dev#1981]
I got a problem in CKEditror 4.7.3 ~ 4.9.2
When I typing Chinese(Taiwan's phonetic symbol also calls Chuyin or Zhuyin) in every second table-cell of table, the Chinese words is out of order, just like CKEditor press Enter automatically.

For Example,
Normal typing:[ㄓ][ㄥ][ˋ][Enter]->System show Chinese words "正"
Failed typing: ㄓ->System show Chinese words ㄓ immediately.

This problem is only happened in Google Chrome. (tested on version 66.0.3359.181).
ONLY in second table-cell of table and 1st Chinese Words.
https://imgur.com/a/2R1tgcN

**Comment by msamsel** [comment]
Hi @jiimmysu,
it seems that your issue is quite similar to those issues:
* https://github.com/ckeditor/ckeditor-dev/issues/1799
* https://github.com/ckeditor/ckeditor-dev/issues/1848

what is related to native bug of Chrome browser (not related to CKEditor).
* https://bugs.chromium.org/p/chromium/issues/detail?id=826686

I close issue as upstream. If you feel that source of the issue is different, then please provide wider description to the issue.

**Comment by jiimmysu** [comment]
OK, I found there is no problem in Chrome Canary version 68. Thank you.
