### ISSUE TITLE
Unexpectedly a command is disabled with obligatory prefix(!) of filtering

### ISSUE THREAD

**Issue by sunnyone** [ckeditor/ckeditor-dev#1985]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a command that have a requiredContent with a obligadory prefix (like div(!my-class))
2. Add a allowedContent that is specified in 1. to the editor 

Use the attached file (example) to reproduce.
[cksample.html.txt](https://github.com/ckeditor/ckeditor-dev/files/2015408/cksample.html.txt)

### Expected result

The command is enabled (the button is clickable in the example)

### Actual result

The command is disabled (the button is hidden in the example)

## Other details

* Browser: Firefox 60
* OS: Ubuntu 16.04
* CKEditor version: 4.9.2
* Installed CKEditor plugins: standard plugins

**Comment by engineering-this** [comment]
Hello,

We need more detailed informations about this issue. Could you please provide us an example of CKEditor configuration on a page like codepen.io or jsfiddle.net? This would help us a lot to track and fix this bug.

**Comment by sunnyone** [comment]
@engineering-this 
I created an example on a codepen: https://codepen.io/anon/pen/PerQJd

**Comment by engineering-this** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

In addition I can give you some hints:
1. You shouldn't add '!' for requiredContent, you are already requiring something, so every param is required not optional.
2. Visit following links for more detailed informations about filtering content:
https://docs.ckeditor.com/ckeditor4/latest/guide/plugin_sdk_integration_with_acf.html#integrating-with-acf-to-activate-editor-features
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_acf.html

**Comment by sunnyone** [comment]
Okay, I now understood this is an expected behavior. Thanks for hints. My intension is not a question but a bug report. Ordinal users should think an expression specified in allowedContent can be copied to requiredContent even if they read the guide.

If this is design, it is friendly for users if CKEditor treats '!' in requiredContent as an error.
