### ISSUE TITLE
Ckeditor is disabled when WindowsDefaultUriPrefix is used as ms-appx:// 

### ISSUE THREAD

**Issue by ramana1240** [ckeditor/ckeditor-dev#2009]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a Ionic project & add platform for windows
2. Edit the config.xml to load from local as 
    <preference name="WindowsDefaultUriPrefix" value="ms-appx://" />
3. Build and deploy the app

### Expected result

*Ckeditor should work for editing the content 

### Actual result

*Ckeditor is in disabled state unable to enter the content or click events for buttons in toolbar

## Other details

 
* OS: Windows
* CKEditor version:  4.9.2
* Installed CKEditor plugins: https://github.com/lemonde/angular-ckeditor 

Ckeditor is disabled due to  **CS
![ckeditor issue](https://user-images.githubusercontent.com/11884422/40541908-618a7528-603b-11e8-8c94-2ca04bb9a728.PNG)
P14312: Resource violated directive 'script-src ms-appx: 'unsafe-eval' blob:' in Host Defined Policy: inline script. Resource will be blocked.**

**Comment by jacekbogdanski** [comment]
Hello,

CKEditor is a javascript library and we cannot fix problems with backend application configuration.

Also, the plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
