### ISSUE TITLE
Block use of 'position' style rule

### ISSUE THREAD

**Issue by lffg** [ckeditor/ckeditor-dev#2011]
Hi,

How can I block the use of `position` CSS property in my editor?
My configuration:

```js
config.allowedContent = {
    $1: {
      styles: ['!position'],
      classes: false
    },
  };
```

But does not work... :/
The version is 4 LTS.

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
