### ISSUE TITLE
wsc_customLoaderScript is not a member of CKEditorConfig

### ISSUE THREAD

**Issue by mtabares3** [ckeditor/ckeditor-dev#2034]
When trying to set the values for these two attributes in code behind (ASP .NET)

With txtWYSIWYGEditor being the name of our CKEditor

txtWYSIWYGEditor.config.wsc_customLoaderScript = WebSpellCheckerURL
txtWYSIWYGEditor.config.wsc_cmd = "spell"

I keep getting the following exceptions:

Error		'wsc_customLoaderScript' is not a member of 'CKEditor.NET.CKEditorConfig'.	
Error		'wsc_cmd' is not a member of 'CKEditor.NET.CKEditorConfig'.

We are already setting values for other attributes in code behind with no issues, example:

txtWYSIWYGEditor.config.height = EditorHeight
txtWYSIWYGEditor.config.width = EditorWidth

These two work without issues.

If I look at the medata file created, in fact, wsc_customLoaderScript  and wsc_cmd are not listed available properties.

What do I need to do in order to these two items to be added to the metadata file?

**Comment by jacekbogdanski** [comment]
Hello,

ASP.NET integration has not been developed since CKEditor 3.6.6.2, therefore newer CKEditor versions are not supported. It might be possible to customise it on your side to support newer CKEditor, but it will require some code changes.

Please note that CKEditor is a pure JavaScript application that can be integrated with any other web application (including ASP.NET applications) using a very simple JavaScript API. This is one of the reasons why we stopped maintaining server side integrations. To learn how to integrate CKEditor using JavaScript API, check the quick start guide: https://docs.ckeditor.com/ckeditor4/latest/guide/dev_installation.html

Apart from the official download page [https://ckeditor.com/ckeditor-4/download/](https://ckeditor.com/ckeditor-4/download/) and CDN [https://cdn.ckeditor.com/](https://cdn.ckeditor.com/) The editor (the JavaScript library) is available also as Nuget packages:
* https://www.nuget.org/packages/ckeditor-full/
* https://www.nuget.org/packages/ckeditor-standard/
* https://www.nuget.org/packages/ckeditor-standard-all/
* https://www.nuget.org/packages/ckeditor-basic/
