### ISSUE TITLE
Image2 could have limiter for resizing image to specified maximum

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2048]
## Type of report

Feature request

## Provide description of the new feature

Originally reported here: https://dev.ckeditor.com/ticket/12701

Image2 could have an extra setting or field in dialog for defining maximum resize size. If doing that inside the dialog, we could have a checkbox (Limit resizer to current image size) or 2 fields for entering max width/height manually. We could also have a configuration option with predefined values e.g. `image_size`, `image_size+20`, `200x300`.

**Comment by mlewand** [comment]
It make sense to put it as a config option.

Rather than string format with `<width>x<height>` it should accept an object, like:

```javascript
{
	width: 400,
	height: 300
}
```

There should be one special case, if you pass values as strings:

```javascript
{
	width: 'naturalWidth',
	height: 'naturalHeight'
}
```

It will retain proper values from img.naturalHeight / width.

There's no need for supporting mixing something like `'naturalWidth+20'` if ever anyone will need that kind of stuff we'd make a callback for it. But I don't think there's a need for that.
