### ISSUE TITLE
Not able to Add Ckeditor in asp.net

### ISSUE THREAD

**Issue by ayushrajmishra** [ckeditor/ckeditor-dev#2066]
## Type of report

Not ABle TO Add Ckeditor in Asp.Net Web application

## Provide description of the task

Bin folder is not present while downloading which contains the dll ...
Doesn't get how to add it into our page
It's not any kind of issue just don't know how to add the new version of ckeditor
Previous version are easily added to the website.
Also i am not able to get any kind of solution from StackOverflow

Thannk You
## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
ASP.NET integration has not been developed since CKEditor 3.6.6.2, therefore newer CKEditor versions are not supported. It might be possible to customise it on your side to support newer CKEditor, but it will require some code changes.

You can download CKEditor for .NET at [https://download.cksource.com/CKEditor/CKEditor.NET/](https://download.cksource.com/CKEditor/CKEditor.NET/) however this is legacy software and we’re not encouraging to use it.

Please note that CKEditor is a pure JavaScript application that can be integrated with any other web application (including ASP.NET applications) using a very simple JavaScript API. This is one of the reasons why we stopped maintaining server side integrations. To learn how to integrate CKEditor using JavaScript API, check the quick start guide: https://docs.ckeditor.com/ckeditor4/latest/guide/dev_installation.html

Apart from the official download page [https://ckeditor.com/ckeditor-4/download/](https://ckeditor.com/ckeditor-4/download/) and CDN [https://cdn.ckeditor.com/](https://cdn.ckeditor.com/) The editor (the JavaScript library) is available also as Nuget packages:
* https://www.nuget.org/packages/ckeditor-full/
* https://www.nuget.org/packages/ckeditor-standard/
* https://www.nuget.org/packages/ckeditor-standard-all/
* https://www.nuget.org/packages/ckeditor-basic/
