### ISSUE TITLE
Laravel 5.5, CKEditor and Additional Items

### ISSUE THREAD

**Issue by jim1506** [ckeditor/ckeditor-dev#2067]
I want to use some of the optional extras, specifically video embedding, in CKEditor.

I have downloaded the entire thing to ckeditor in the public area, and in the plugins directory there is the video.

I start with the CDN of CKeditor:

`<script src="//cdn.ckeditor.com/4.7.3/full-all/ckeditor.js"></script>``

and then I add the option for the video plugin:

`<script>
 CKEDITOR.plugins.addExternal( 'video', '{{ public_path('\ckeditor\plugins\video\ ') }}', 'video.js' );
</script>`

(The video.js actually is in a subdirectory dialogs which I have tried as well).

I can see the CKEditor which appears on my page but no video button.

Anyone any ideas please?

**Comment by engineering-this** [comment]
The `video` plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
