### ISSUE TITLE
Not able to configure Ckeditor 5

### ISSUE THREAD

**Issue by sibasishpalo** [ckeditor/ckeditor-dev#2076]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
Followed the steps to configure CKEditor 5 given in below URL but getting errors.

https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/installation.html

![image](https://user-images.githubusercontent.com/30113621/41274431-fb6b6afa-6e3a-11e8-9ca5-743dbac917f1.png)

Am i doing something wrong or am i missing something.
Is there any pre-requisites to use CKEditor 5.

Attached the sample page and the classic editor folder.

[ckeditor5_POC.zip](https://github.com/ckeditor/ckeditor-dev/files/2092869/ckeditor5_POC.zip)

Also tried with CDN URL getting the same error.

Please help.

Also i see there is a change in folders/files what we were getting in CKEditor4 as compare to CKEditor5.

Thanks in Advance.

**Comment by jacekbogdanski** [comment]
Hello,

It's CKEditor4 issue tracker, you should open a ticket on [CKEditor 5 issue tracker](https://github.com/ckeditor/ckeditor5/issues) if you would like to report a bug or a feature request.

However, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
