### ISSUE TITLE
add a 5th style type that applies inline styles directly to the selected elements. 

### ISSUE THREAD

**Issue by deevolutionism** [ckeditor/ckeditor-dev#2095]
## Type of report

Feature request

## Provide description of the new feature
This feature will allow plugin developers to have more control over how they can style elements. There are many uses for Ckeditor, one of them being for creating email templates. Currently there are a few [style types](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_styles.html#style-types) that exist. However, these create span elements which are not always rendered correctly or at all in email clients. One such example is line height. Line height must be applied directly as an inline-style to a block element such as a p or h1. 
*What is the expected behavior of the proposed feature?*
A user selects a few blocks of text which they want to change the line height of:

```
[<p>hello this</p>
<h1>is a bunch of</h1>
<p><span style="font-family: verdana;">random text</span></p>]
```

normally a plugin might use the editor.applyStyle method and provide a style definition that is one of the above types (1-3, widget). This type would allow a plugin developer to declare a style definition such as this: 
```
new CKEDITOR.style({ name: line_height,  styles: {line-height: '200%'}})
```
 
using the editor.applyStyle method, the selected text would have the line-height value applied.
```
[<p style="line-height: 300%;">hello this</p>
<p style="line-height: 300%;"> is a bunch of</p>
<p style="line-height: 300%;"><span style="font-family: verdana;">random text</span></p>]
```

Currently this doesn't seem possible as ckeditor inserts an inline element such as a span with a style attribute (which will not render some styles in email clients such as microsoft outlook). If it is possible to do what I just described, Its not immediately clear how to define a block-style-definition based on reading the docs.

I have submitted an [issue ](https://github.com/lotusgodkk/lineheight/issues/8) with the maintainer of the lineheight plugin and provided a [gist](https://gist.github.com/deevolutionism/6ccefd2b0ac18225926faead28307663) of a mod I wrote of his plugin where I attempt to do the things I describe here, but run into bugs, specifically in IE/Edge browser.

**Comment by engineering-this** [comment]
Hi,

I have suggestion that might help you to solve your problem.
When creating style, you can specify element tag name in style definition.

Example:
```
new CKEDITOR.style( {
  element: 'p',
  name: 'line_height',
  styles: {
    'line-height': '200%'
  }
}
```

When applying such style to your example the output would be just like your expected.
If you need more control on how style is created and applied to editor then check [`CKEDITOR.style.addCustomHandler` ](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_style.html#static-method-addCustomHandler).

For now I'm closing this issue, as I believe CKEditor have all the tools you need. However if you find them insufficient for your needs you can edit this issue with more detailed informations on what improvements to Editor can help you and other users.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. If you need more help on how to make things work please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
