### ISSUE TITLE
Issues with cursor movement in RTL mode

### ISSUE THREAD

**Issue by WrathOfZombies** [ckeditor/ckeditor-dev#2104]
We're having some trouble with our integration with CKEditor. We have followed the documentation to set the CKEditor language type and also the content direction to `rtl`. Due to reasons known, our cursor keeps getting stuck at the end of the input and refuses to go back.

The same behavior is not seen on the demo page on CKEditor. Hence what we are looking for is a starting point, where we should start looking into so that we can diagnose the problem further and post back with our findings.

**Repro steps**

1. In RTL mode, type some characters and then start to use the cursor to move backwards (right arrow)
2. Cursor gets stuck at the end of input and doesn't proceed backwards.

What is the expected result of the above steps?
1. Cursor should move backwards towards the start of the input

**Other details**

* Browser: Chrome (latest) & Edge 17
* OS: Windows 10 - 1803
* CKEditor version: 4.7.2

**Comment by WrathOfZombies** [comment]
FYI @jurokapsiar @weiluen

**Comment by msamsel** [comment]
Hi @WrathOfZombies,
please provide sample with CKEditor where problem occurs. 
I checked it here: http://cdn.ckeditor.com/4.9.2/full-all/samples/old/uilanguages.html with setting `Arabic` language and cursors seems to work fine for this configuration.

**Comment by weiluen** [comment]
Hi @msamsel I've got a test tenant and user up for you, now. If you provide me /w an email I can get that information setup for you.

**Comment by weiluen** [comment]
Just a friendly ping on this. Let me know if there's anything we can do to clarify.

**Comment by jswiderski** [comment]
Hi @WrathOfZombies & @weiluen,

Could you provide a screen cast showing this problem (in form of a link to online screen cast or attached as zip)? 

To my understanding you are setting RTL language in CKEditor as shown below: 
```
var editor = CKEDITOR.replace( 'editor1', {
	language: 'he',
	contentsLangDirection : 'rtl'
}); 
```
Please tell me what language is set on your operating system? Is it RTL language like Arabic, Hebrew, Persian etc. or LTR language like English, German etc.

**Comment by weiluen** [comment]
[Video of Typing Indicator Issue](aka.ms/typingIndicatorForCkEditor)

We are setting the RTL language as follows:

`    defaultLanguage: 'en',
      contentsLangDirection: this.localizationService.langDirection,
      language: 'en'
 `
Where localizationService.langDirection returns either 'rtl' or 'ltr' based on whether the language selected in the Microsoft Teams app is hebrew or arabic (ar/he).

The OS language is set to English (en-us).

**Comment by jswiderski** [comment]
@weiluen, any news on that screen cast access rights? I still can't access the video. I'm getting 404.

**Comment by weiluen** [comment]
@jswiderski  sorry I missed your comment. Please try this copy pasted in your browser. http://aka.ms/typingIndicatorForCkEditor

**Comment by jswiderski** [comment]
Hi @weiluen,

The original ticket report said about problem in Windows. From what I can see you are testing your CKEditor in Mac. Please tell me the following:

1.	Are you having same problem on Windows and Mac? 
2.	What is that virtual keyboard (I’m not familiar with it)? Is it a built-in feature of Mac or some custom plugin? Can you reproduce this problem without that keyboard?
3.	Can you reproduce same problem in native iframe or native editable element depending which CKEditor you use - https://codepen.io/j_swiderski/pen/PBwZbb?
4.	 Which type of editor you use – inline or classic with contents in iframe?
5.	If you are using inline editor, have you tried setting `lang="he" dir="rtl"` for editable element? Did it help?
6.	If you are using inline editor why there is no toolbar shown for your editor instance? Have you customized it so that toolbar is not available? If that is the case are you able to reproduce this problem in default CKEditor with `lang="he" dir="rtl"` attached to editable div and settings which you use (please try attached sample)?
7.	How much is the editor customized (if you did any customizations at all)? Have you changed editor core code, created your own language direction plugins etc. ?
8.	Are you able to provide online simplified sample with type of editor you use which shows this problem in code?

[inlinebycode.zip](https://github.com/ckeditor/ckeditor-dev/files/2183642/inlinebycode.zip)

**Comment by weiluen** [comment]
This issue has been resolved. We found an internal fix.  Thanks @jswiderski !

**Comment by jswiderski** [comment]
@weiluen thank you for letting us know. I'm closing the ticket.
