### ISSUE TITLE
span in span

### ISSUE THREAD

**Issue by yiqianglin** [ckeditor/ckeditor-dev#2124]
## Type of report

Feature request

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*

I has inserted dom like `<div><span class='text'>111111</span><span class="icon"></span></div>`, and when i use 'backSpace' on  keyboard to delete '11111'，it will delete <span class="icon"></span>, why?  i  has set config.allowedContent = true;  CKEDITOR.dtd.$removeEmpty['span'] = 0;  but it seems no useful.

ckeditor version: 4.6+

**Comment by yiqianglin** [comment]
how can i keep <span class="icon"></span> and empty <span class='text'> when '11111' is deleted?

**Comment by jacekbogdanski** [comment]
Hello,

CKEditor is a WYSIWYG rich text editor which enables writing content directly inside of web pages or online applications. Deleting content using a keyboard is expected behavior and won't change. `CKEDITOR.dtd.$removeEmpty` configuration indicates that element will or won't be removed content when setting element explicitly, but it can be modified with user interaction.
