### ISSUE TITLE
How to detect if image upload is started or success

### ISSUE THREAD

**Issue by macray125** [ckeditor/ckeditor-dev#2178]
## Type of report

Task

## Provide description of the task

*How to detect if image upload is started or success I'm using extraPlugins easyimage*

`var editor = CKEDITOR.replace( 'news_description', {
                extraPlugins: 'easyimage',
                removePlugins: 'image',
                removeButtons: 'CopyFormatting,Subscript,Superscript,RemoveFormat,About,Anchor,Maximize,ShowBlocks,BidiLtr,BidiRtl,Language,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,Source,Save,NewPage,Preview,Print,Templates,Cut,Copy,Paste,PasteText,PasteFromWord,Undo,Redo,find,selection,spellchecker,Find,Replace,SelectAll,Scayt,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,CreateDiv',
                cloudServices_tokenUrl: 'url-here',
                cloudServices_uploadUrl: 'url-here'
            } );`

## Other details

* Browser: Google Chrome
* OS: Windows
* CKEditor version: 4
* Installed CKEditor plugins: easyimage

**Comment by jacekbogdanski** [comment]
Hello,

you will have to listen on [File Loader](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_fileTools_fileLoader.html) events.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
