### ISSUE TITLE
Drag Drop and Paste Image functionalities are not working with Track changes on mode

### ISSUE THREAD

**Issue by gsinha** [ckeditor/ckeditor-dev#2203]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a CKEditor with 'Upload Image' (which support dropping and pasting images) and track changes plugin and configure it.
2. Turn on track changes functionality of editor.
3. Drag drop image into editor.

### Expected result

Image should be shown properly in editor.

### Actual result

A black square is shown in the editor.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: uploadimage, image2, lite(track changes)

**Comment by jacekbogdanski** [comment]
Hello,

I cannot reproduce your issue with minimal CKEditor configuration, it seems like `lite` plugin is causing the issue.

The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
