### ISSUE TITLE
Widgets not initialised after calling setHtml on an element

### ISSUE THREAD

**Issue by gfox1984** [ckeditor/ckeditor-dev#2204]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I have created a simple CKEditor widget that highlights the elements that have the class "pink".
I have also added a "Pinkify" button to the toolbar, which replaces the HTML of the selected element with some other elements that have the class "pink".

See the [jsfiddle](https://jsfiddle.net/gfox1984/a6qyn2hL/) and its code:

```
CKEDITOR.replace('ck', {
  allowedContent: true,
  extraPlugins: 'pink'
});

CKEDITOR.plugins.add('pink', {
  requires: 'widget',
  init: function(editor) {
    editor.widgets.add('pinkwidget', {
      upcast: function(element) {
        return element.hasClass('pink');
      }
    });

    editor.addCommand('pinkify', {
      editorFocus: 1,
      exec: function(editor) {
        var selection = editor.getSelection(),
          selectedElement = selection.getStartElement();
        if (selectedElement) {
          selectedElement.setHtml("Let's have some <span class=\"pink\">pink</span> widget here!");
          editor.widgets.checkWidgets(); // needed?
        }
      }
    });

    editor.ui.addButton('pinkify', {
      label: 'Pinkify',
      command: 'pinkify'
    });
  },
  onLoad: function() {
    CKEDITOR.addCss('.cke_widget_pinkwidget { background: pink; }');
  }
});
```

Set the text cursor inside the second paragraph on jsFiddle, then click the "Pinkify" button in the toolbar and observe that the inserted text has no widgets (it should).

### Expected result

The widgets get created as soon as the new HTML is inserted.

### Actual result

The widgets are not created for the freshly inserted elements. However, when you toggle between Source mode and WYSISYG mode, the widgets get created.

## Other details

* Browser: Edge 42.17134.1.0 with EdgeHTML 17.17134 (not tested on other browsers)
* OS: Windows 10 Pro 1803
* CKEditor version: 4.9.2
* Installed CKEditor plugins: full-all

**Comment by engineering-this** [comment]
Hi there,

`CKEDITOR.dom.element.setHtml` doesn't trigger widgets upcasts. The least effort changes to your code would be this:

``` 
if (selectedElement) {
	selectedElement.setHtml("");
	editor.insertHtml("Let's have some <span class=\"pink\">pink</span> widget here!");
}
```

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by gfox1984** [comment]
Is it not an issue that `CKEDITOR.dom.element.setHtml` doesn't trigger widgets upcasts? The proposed workaround is not valid as it does not achieve the same behaviour (only the HTML of the selected element must be replaced). I'm sorry but this means I'm either reporting a bug (it doesn't work while it should), or I'm requesting a feature (I need a way for it to work). You choose.

I have already posted the question on StackOverflow, see [How to force CKEditor to process widgets when setting the HTML of an element](https://stackoverflow.com/questions/51078154/how-to-force-ckeditor-to-process-widgets-when-setting-the-html-of-an-element).

I'll be happy to share the solution once I have one :)
