### ISSUE TITLE
Image in table cell has an empty URL field when edited from context menu opened by right-click

### ISSUE THREAD

**Issue by a-hecht** [ckeditor/ckeditor-dev#2235]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a new table in ckeditor.
2. Put a single image in one of the cells.
3. Right click the image to open context menu.
4. Choose "Image Properties" from context menu to open the "Image Properties" dialog.

### Expected result

The fields of the "Image Properties" dialog should be populated with the corresponding properties of the image that was right-clicked.

### Actual result

The fields of the "Image Properties" dialog remain empty.

## Other details
Browsers: Current versions of Chrome/Chromium and Firefox under Linux and Windows 7/10.
CKEditor versions tested: 4.10.0 and 4.9.2
The issue only occurs if "Image Properties" was called via context menu and the image is the sole content of a table cell. Double clicking the image or selecting it and calling the dialog via tool bar operates as expected.
A possible cause of this bug maybe located in the selection range handling of the function isTableSelection (in core/selection.js)

**Comment by engineering-this** [comment]
Confirmed with `image` plugin. Not reproducible with `image2`.

**Comment by dwahlqvist** [comment]
Unfortunately `image2` lacks functionality we need e.g. link tab, i.e. changing to it is not a valid work around for us.
Looking forward to a bug fix :)

**Comment by f1ames** [comment]
This issue is caused by `tableselection` plugin which was introduced in `4.7.0`. While using right mouse button to open context menu (by clicking on image) the whole table cell gets selected instead of an image and the properties are not correctly propagated to the dialog (because selection points to table cell not an image).

Bug was introduced in `4.7.0` and is still reproducible in `4.11.3`.

**Comment by f1ames** [comment]
Since the issue is caused by `tableselection` plugin, disabling it resolves the issue which may work as a workaround.

Another workaround is to use keyboard (instead of mouse) to open context menu while the image is selected. The [context menu keyboard shortcut](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_shortcuts.html#working-with-a-document) is <kbd>Shift</kbd> + <kbd>F10</kbd>. Also `Image Properties` dialog can be opened via double-clicking on the image instead of opening it via context menu which also works correctly in the above scenario.
