### ISSUE TITLE
Add "Minimize" button to a more convenient place

### ISSUE THREAD

**Issue by AnrDaemon** [ckeditor/ckeditor-dev#2324]
## Type of report

Feature request

## Provide description of the new feature

For a maximized standard editor, it would be convenient to have "minimize" button in a more easily accessible place.
For example, on the bottom panel of the editor, at the right.

**Comment by mlewand** [comment]
It's pretty subjective to tell where the more convenient place would be. For some users the current implementation would be a best fit, as it has good discoverability - it is in the same place where user already clicked to bring maximized version - so user already knows where to find option to minimize.

I can also see how minimize element in a different position would work better, though I'm concerned about bottom toolbar. Think about people using pivot orientation displays, there's a big chance you won't notice the button at all. This is the case with Firefox search component.

I think the best idea to start here is to create a simple plugin for that.

What you want to do is to listen for `maximize` command execution, and check its state (whether it's enabled/maximized or not) - based on this update your component in bottom space of the editor.

You could then add the plugin to [Add-ons Repository](https://ckeditor.com/cke4/addons/plugins/all) so that entire community could benefit from it.

**Comment by AnrDaemon** [comment]
I did not said "move", did I?
