### ISSUE TITLE
chrome browser crashed when paste source code table with -webkit-text-stroke-width

### ISSUE THREAD

**Issue by laomu1988** [ckeditor/ckeditor-dev#2328]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. open page `https://sdk.ckeditor.com/samples/fullpage.html`, click `source code` button
2. paste code `<table style="-webkit-text-stroke-width: 1885px;" width="100%"><tbody><tr><td><p>test</p></td></tr></tbody></table>
`
3. click source code button

### Expected result

*show table*

### Actual result

*chrome browser crashed, editor area blackened*

## Other details

* Browser: 68.0.3440.106
* OS: Mac
* CKEditor version: 4.10.0
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
What is the expected behaviour? If the mentioned style should be deleted, there is already issue for that: #2326.

In case of blackening the editor's content, seems like working as intended – adding 1885px frame for every letter will result in covering the whole editor's content with the frame of the first letter. Only on bigger monitors (bigger than 1885px) there will be enough space to display anything else.

As for browser crashing, I can't reproduce it.

**Comment by AnrDaemon** [comment]
More interesting, why did he report a browser crash to the JS project?
By definition, JS should NEV ER crash the host app.
