### ISSUE TITLE
Alternative text is not mandatory while uploading an image.

### ISSUE THREAD

**Issue by anjiv** [ckeditor/ckeditor-dev#2386]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. In the editor panel there is an option to upload an image. Try to upload an image.
2. Upload an image. Now, without entering the alternative text, save the content.
3. Run the WAVE tool to check the accessibility.

### Expected result

It throws an accessibility error showing that alt text must be added.

### Actual result

Accessibility error must be resolved.

## Other details

* CKEditor version: 4.8.0

**Comment by anjiv** [comment]
Hi @mlewand ,

I would like to work on this issue. So, may I please ??

Thanks

**Comment by mlewand** [comment]
The best way to solve it, without degrading the UX, is to hook the [Accessibility Checker](https://ckeditor.com/ckeditor-4/accessibility-checker/) as a validator to your save button (and prevent saving if there are Accessibility Issues found). In case any image is missing alt text it quickly takes you through all of them:

![Accessibility Checker showing missing alt in an image](https://i.imgur.com/YyHMQVf.png)

Adding such feature in image plugins is redundant, but even worse, it would degrade the UX.

Consider [Image](https://sdk.ckeditor.com/samples/image.html) or [Enhanced Image](https://sdk.ckeditor.com/samples/image2.html) plugins - both of them are modal-dialog based, so if we were to expose alt editing control to the user, this means you have to open modal dialog *asynchronously* as the upload ends. Imagine upload hires image, say 4k/8k - because you want to have crystal sharp images on your websites, and your backend does a good job in making multiple res versions and adding a proper `srcset`. On different connections it might take around minute. Getting modal dialog after that kind of time would be really bad.

For [Easy Image](https://sdk.ckeditor.com/samples/easyimage.html) plugin situation will be much better when we add an enhancement to edit alt in a balloon (it's not out yet) - then you can focus the uploaded image and show the balloon with alt.

![Alt text edited in the balloon](https://i.imgur.com/o3Ni1Xj.jpg)

Then again think that it happened in the middle of typing, because you wanted to type something as the image is still uploading.

Finally for all of these plugins, you can upload multiple images at once. Then modal dialogs are completely unfeasible, the only option is to show a balloon with next/prev buttons which is exactly what Accessibility Checker does.
