### ISSUE TITLE
Can't use both "em" and "i" or "strong" and "b" tags

### ISSUE THREAD

**Issue by semiaddict** [ckeditor/ckeditor-dev#2415]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. set coreStyles_bold to  { element: 'strong' };
2. set coreStyles_italic to  { element: 'em' };
3. add i,em,strong and b to the extraAllowedContent
4. enter the following in an editor using the source dialog: 
`<p>test <i>italic</i>, <em>em</em>, <strong>strong</strong>, and <b>bold</b></p>`

### Expected result

All tags should stay the same; no overriding of "b" and "i" tags should occur.

### Actual result

"i" and "b" tags are replaced to "em" and "strong" respectively

## Other details

* Browser: Chrome 69
* OS: Windows 10
* CKEditor version: …
* Installed CKEditor plugins: basicstyles, button, detectConflict, dialog, dialogui, entities, sourcedialog, toolbar, wysiwygarea

This seems to be hard-coded in the contentForms variable of the basicstyles plugin.
We need to be able to use "i" and "em" as well as "b" and "strong" tags for better accessibility.
Is there another way to achieve this ?

**Comment by jacekbogdanski** [comment]
Hello,

unfortunately, we are not going to provide this option thus we don't see it as valuable. Semantically it doesn't seem right to keep both `italic` styles described by different tags.

**Comment by mlewand** [comment]
@semiaddict tags like `<b>` tag has no real meaning in terms of a11y. For visual purposes you want to use CSS instead of HTML4. Note that using CSS has an advantage because you could use many accessibility features in CSS `voice-*`, `cue-*` just to name a few.

So instead of using unambiguous markup (really `b` and `strong` will be confusing if someone browse your HTML) just go with CSS where you need it.

**Comment by semiaddict** [comment]
Thank you @mlewand. That was indeed one of the options I was going to explore, and is most likely what we'll be going for.
