### ISSUE TITLE
Include <small> as basic toolbar item

### ISSUE THREAD

**Issue by olia-bn** [ckeditor/ckeditor-dev#2434]
## Type of report

Feature request

## Provide description of the new feature

`<small>` is a valid HTML5 element assigned a semantic meaning as well as cross-browser default css rule.
As such it should be a toolbar item available in CKEditor without custom code.

**Comment by msamsel** [comment]
Hi @olia-bn,

`<small>` element is possible to obtain with styles combo.
Please take a look on screenshot below. That's why I close the issue. If you feel that it not solve your case, then please provide more details in a comment or description so I could reopen it.
![screen shot 2018-09-26 at 16 30 31](https://user-images.githubusercontent.com/9017322/46087023-b380da00-c1a9-11e8-8504-1440172c05f3.png)
