### ISSUE TITLE
Font size standards are different in CKEditor and when pasting from MS Word 

### ISSUE THREAD

**Issue by lindavik** [ckeditor/ckeditor-dev#2447]
## Type of report

_Feature Request_
Font size standards are different in CKEditor and when pasting from MS Word, for example, a font size of 12 is a different size in MS Word and CKEditor, which can be confusing for users.

## Provide detailed reproduction steps (if any)

1.  Open MS Word and create a sample text, such as "This is a Verdana 12 text". Style the text accordingly - font: Verdana, size 12.
2. Copy and paste this sample text into the CKEditor, eg, https://cdn.ckeditor.com/4.9.2/full-all/samples/.
3. If you now select the pasted text and change the font size in the dropdown to 12, the text will considerably shrink. It looks like when pasting from MS Word the font-size is in pts and when selecting a size from the drop-down it is in px.

_Feature Details_
As a user I would like that `fontsize` plugin will change font's size in `pt` not in `px`, because it's unit added by Microsoft Word during paste operation. Currently pasted unit from Word document is not automatically detected and remain unknown for `fontsize` plugin.
Alternatively there pasted `pt` unit might be transformed to `px` during paste operation.

### Expected result

That both the CKEditor and the MS Word size 12 would be the same/consistent, e.g. 12pts.

### Actual result

The text is considerably smaller in CKEditor, as in the CKEditor the drop-down font size is in px, whereas when pasting from MS Word it is in pts.

## Other details

* Browser: not browser specific
* OS: tested only on Mac but probably same in Windows
* CKEditor version: 4.9, full-all
* Installed CKEditor plugins: all full-all default plugins

**Comment by msamsel** [comment]
Please correct me, if I understand you wrongly.
You style content in MS Word, copy paste it to editor. And Font dropdown does not detect font size?

Those are 2 separate plugins which works independently. You can have neither of those 2 plugins, only one of them or both. And was developed independently in different time frames. Fontsize was created much earlier than paste from word. So from my perspective this issue is rather feature request to:
- improve paste from word plugin to convert `pt` into `px` during paste content
- improve fontsize plugin to react on `pt` not only on `px`

What do you think about it? Does it cover your case here?

PS You can also try to play a little bit with [transformations](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_filter_transformationsTools.html). Those features can automatically transform styles and/or attributes, and might somehow help you, if you decide to fix it by your own.

**Comment by lindavik** [comment]
That does cover our case, yes, thank you!

Best wishes,
Linda Viksne

**Comment by lindavik** [comment]
Can you confirm or keep us updated if/when you choose to work on and
release this feature?
Thank you very much in advance!

Best wishes,
Linda Viksne

**Comment by msamsel** [comment]
Hi @lindavik,

all stuff related to this case should be commented here, so you should get all notification related to this case.
I'll add clear description to your task to have nice overview what is about.

**Comment by mlewand** [comment]
There is already a [`config.fontSize_sizes`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-fontSize_sizes) variable that allows to customize values in font size dropdown.

For example consider following configuration:

```js
let pts = [ 9, 12, 14, 16 ],
	px = [ 16, 24, 48 ];

config.fontSize_sizes = pts.map( ptVal => `${ptVal}/${ptVal}.0pt` ).concat( px.map( pxVal => `${pxVal}px/${pxVal}px` ) ).join( ';' );
```

Here is a sample `.docx` file with few paragraphs, all in different font size (and one unspecified): 
[Different font sizes.docx](https://github.com/ckeditor/ckeditor-dev/files/2580341/Different.font.sizes.docx)

Open it and paste into the editor, then put the selection in paragraph that has the font size explicitly defined. You'll see that the size is matched, since font-size contains matching values.

![A proper font size matched in text pasted from Word](https://user-images.githubusercontent.com/5353898/48477778-c2c3f180-e802-11e8-86ea-4e79dda4df5a.png)
