### ISSUE TITLE
CKEditor removeAllListener breaks decrease indent functionality

### ISSUE THREAD

**Issue by mdineshkumarcs** [ckeditor/ckeditor-dev#2494]
I am using ckeditor version 4x for my application. I am facing strange issue with decrease indent functionality when using below code to increase performance before generating editor in internet explorer. When i have more than 5 editor in single page, page render slowly with some flick. To avoid this i used removeAllListeners() before generating editor to remove all listener which has been attached to it.

 ```
CKEDITOR.removeAllListeners(); // this breaks decrease indent 
 CKEDITOR.replace( 'editor1', {
        extraPlugins: indent,indentblock
    });
```
After commenting removeAllListeners function, Decrease indent working as expected but again performance issue raise and throws ' long running script error' in internet explorer.

When we use removeAllListeners() function, long running error gone and decrease indent not working after increase indent. We have to manually press backspace to enable decrease indent icon.

![untitled](https://user-images.githubusercontent.com/5146521/47200391-9ea3fa80-d393-11e8-8e33-54626219aa81.png)

From above screen, red highlighted box shows decrease indent is still not enable after increase indent the text.This is because of using removeAllListeners() function before generating editor. Green box show it is works fine after removing it but long running error comes which results page frozen.

Please advise.

* Browser: Internet Explorer 11
* OS: Windows
* CKEditor version: 4.5.11

**Comment by jacekbogdanski** [comment]
Hello,

it's not like `CKEDITOR` contains some redundant listeners which may be just dropped for better performance. It's the main module, so `CKEDITOR.removeAllListeners` may break things.

I also wasn't able to reproduce the issue with `long running script` alert, although I can confirm some performance drop on a very slow virtual machine (like 1GB RAM etc) - although it will happen and it's a hardware issue.

Could you try to reproduce the issue with no-responsiveness using the latest `4.10.1` CKEditor? The latest version runs pretty smoothly and it may resolve your issue.

**Comment by mdineshkumarcs** [comment]
Thanks for quick response. I am trying to generate the editor in loop. Long running script occurs only in Internet explorer 11 after remove removeAllListener function. Since i am using backbone for my development and attaching 3 events to editors, page get slow after updating the data to respective editor model in backbone. To prevent this, I tried with removeAllListener. Later it works smoothly but not with decrease indent. I just need to keep performance smoothly even page have more editor. Do we have possible way to remove all attached event when ever needed to keep performance good.

Meantime,I will try to check with 4.10.1

**Comment by jacekbogdanski** [comment]
Currently, I could only recommend to update CKEditor to the latest version and eventually trying to cut some redundant plugins which may slow down the editor.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
