### ISSUE TITLE
Cursor moves to the Top

### ISSUE THREAD

**Issue by snarkhede23** [ckeditor/ckeditor-dev#2563]
## Type of report

Bug - We are trying to insert HTML in the Ckeditor using another ckeditor window, the cursor moves to the Top and the Track Changes is set to ON after the insert is completed.

## Provide detailed reproduction steps (if any)

1. Enter some text in the editor and set the Track changes to OFF.
2. Insert HTML into the editor window using another editor window, we have a tool in the editor which is basically a editor, which let us copy text from one place to another. 

### Expected result
*What is the expected result of the above steps?*
The cursor should be after the new inserted text and if the Track changes are OFF they should remain OFF.

### Actual result
*What is the actual result of the above steps?*
The cursor moves to the top of the page and the track changes is set to ON.

## Other details

* Browser: Chrome
* CKEditor version: 4

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
