### ISSUE TITLE
Paste Popup only shown as text

### ISSUE THREAD

**Issue by rokka** [ckeditor/ckeditor-dev#2567]
I know that some browsers have a problem with pasting content from the clipboard.

When I use the online demo I get this nice little popup:

![image](https://user-images.githubusercontent.com/533290/47921955-26225b00-deb6-11e8-938f-3cd075229af8.png)

But as soon as I use the CKEditor builder I don´t get a popup anymore. Instead I get a text information somewhere on the page:

![image](https://user-images.githubusercontent.com/533290/47922030-54a03600-deb6-11e8-9fc6-c5ff1a3d480a.png)

How can I avoid this?

**Comment by jacekbogdanski** [comment]
Hello,

I look like your CSS styles are properly loaded. Make sure that CKEditor CSS skins are up to date and try to clean old cookies.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by rokka** [comment]
Hey, I am fine with closing this issue.

But I have found out that this only happens when I use the "Office 2013" skin inside the CKEditor Builder.

Maybe this helps someone.
