### ISSUE TITLE
Error in scrolling the editor

### ISSUE THREAD

**Issue by Febnu** [ckeditor/ckeditor-dev#2582]
Hi, 
I'm using ckeditor with smartgwt, but there is a problem with the scrolling. It seems that if I reach the bottom of the editor the scroll stops, so the page in which the editor is embedded doesn't move. I would like the scroll to continue after the bottom of the editor is reached.

is there any config o other parameters I have to change?

Thanks

**Comment by jacekbogdanski** [comment]
Hello,

As I understand, `smartgwt` is some third party framework you are trying to integrate with CKEditor? If so, I'm sorry, but are not able to help you with integration thus the software you are referring is not maintained by CKSource. Please redirect your question to the `smartgwt` author who should be able to review the problem and suggest a solution.

If you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

You can also leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues.
