### ISSUE TITLE
Tables Bug on Invision Power forum

### ISSUE THREAD

**Issue by BaltoDog** [ckeditor/ckeditor-dev#2600]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using Mozilla Firefox, go on any threads of my forum containing a table (example: https://totallympics.com/index.php?/topic/1255-totallympics-open-international-song-contest-2018/ )
2. When I select the cells of the table using mouse selection+CTRL keyboard button , the table is getting distorted (see images attached)
![before](https://user-images.githubusercontent.com/39212775/48367254-69e44400-e6b0-11e8-8ba0-eb4885b51bf2.png)

![after](https://user-images.githubusercontent.com/39212775/48367262-7072bb80-e6b0-11e8-868e-d19d8c891598.png)

### Expected result

*Before the last forum's software update, this was not happening and I was just seeing the selected cells marked as selected. *

### Actual result

*Now the table gets distorted.  This is not happening when I am editing a post, but only when I am surfing the thread from any browser (static mode). If I update the page the table is normal again, because of course I was just in view mode and not in the edit mode. *

## Other details

* Browser: Mozilla Firefox latest version
* OS: Windows
* Installed CKEditor plugins: table

**Comment by Comandeer** [comment]
The software you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the software’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

**Comment by BaltoDog** [comment]
Hello Comandeer, sorry for my ignorance, but who is the software's author ? Here it says the author is "CKSource" ? https://ckeditor.com/cke4/addon/table

Thank you in advance.

**Comment by Comandeer** [comment]
Yes, CKSource is the author of this plugin, however in this case the editor is integrated with the rest of the forum software. I can't reproduce the issue using "clean" CKEditor 4. Please see that the row, which gets distorted, is the same row, in which "quote selection" popup is showed – and it's the element added by IPS software, not our plugin.
