### ISSUE TITLE
addButton function for ng2-ckeditor

### ISSUE THREAD

**Issue by alsvid** [ckeditor/ckeditor-dev#2617]
## Type of report

Feature request

## Provide description of the new feature
ng2-ckeditor calls a function called addButton which is not present here.

**Comment by jacekbogdanski** [comment]
The Angular integration you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the code author who should be able to review the problem and suggest a solution.

If, however, after contacting the maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
