### ISSUE TITLE
upload image/file can't work correctly on IE8/9

### ISSUE THREAD

**Issue by wangyang2010344** [ckeditor/ckeditor-dev#2620]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. click image and select upload tab
2. select an image and click upload to server

### Expected result

it should jump to the first tab of image dialog with the return url
![image](https://user-images.githubusercontent.com/5354225/48967010-72743d00-f015-11e8-86ef-dc97431cff4e.png)

### Actual result

no jump but show the response json string at input place like this
![image](https://user-images.githubusercontent.com/5354225/48966995-45c02580-f015-11e8-92e2-836111ced643.png)

## Other details

* Browser:IE 11 in IE8 Mode or IE9 Mode at windows10(IE10 Mode is OK but still can not paste as IE8/9);IE8 at windows7
* OS: windows 10/window7
* CKEditor version: 4 (just downloaded)
* Installed CKEditor plugins: tableresize,uploadimage,uploadfile(Followed this [document editor](https://github.com/ckeditor/ckeditor-docs-samples/blob/master/editors/document-editor/index.html))

**Comment by wangyang2010344** [comment]
> 1. Open /js/upload.js
> 2. On line 24 change the runtimes order to html5,flash,html4
> 3. On line 37 change flash_swf_url to ‘/wp-includes/js/plupload/plupload.flash.swf’

sorry i don't know what's this mean.can you show a picture for me?thanks very much!

**Comment by wwalc** [comment]
It looks like you used your own or 3rd party feature for uploading images. The issue here has nothing to do with CKEditor 4 but is related to a wrong implementation of a file uploader.

For more information check:
 * https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html
 * https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_upload.html

Alternatively you may give a try to [CKFinder](https://ckeditor.com/ckeditor-4/ckfinder/).

**Comment by lostimever** [comment]
I hava the same question .
How did you solve it?
