### ISSUE TITLE
Import all pages from Word

### ISSUE THREAD

**Issue by JURALOVE** [ckeditor/ckeditor-dev#2632]
Hello people

I'm a begginer with this editor, but I have been tried this editor and I think it's better than others, however I have found an expected result. I have been trying paste one document from Word with 10 pages. Paste isn't giving with headers, footers and only images from first page, from Google Docs lost format too. Are there someone who had that problem??? Is CKeditor need some plugging which is not in this repository???

Thank you for you answer

**Comment by jacekbogdanski** [comment]
Hello,

thanks for kind words! Could you provide an example Word document where the issue occurs?

Paste from Google Docs is not officially supported, we are working on it as a separate feature. You can check its status at https://github.com/ckeditor/ckeditor-dev/issues/835

**Comment by jacekbogdanski** [comment]
You can attach a file here. Just drag and drop a file on the comment text area.

**Comment by JURALOVE** [comment]
Ok, Jacek. I just added, it's an example that isn't running yet. It's a basic example, however not paste some pictures, headers and footer are lost too. Perhaps I am the problem and Ckeditor is not used good by me. Thank you for your time. 

[PRUEBA.docx](https://github.com/ckeditor/ckeditor-dev/files/2648138/PRUEBA.docx)

**Comment by jacekbogdanski** [comment]
I don't see a lot of issues with the enclosed document, actually, there is one with page breaks but this feature has a separate ticket and we are already working on it https://github.com/ckeditor/ckeditor-dev/issues/2598

`pastefromword` plugin is a bit dumb when talking about preserved styles - it will parse clipboard HTML correctly, but they need to be enabled by ACF. The easiest way to do it is just by importing correct plugin into CKEditor. Eg. bold, underline and italic will be preserved if you include [Basic Styles](https://ckeditor.com/cke4/addon/basicstyles) plugin into an editor.

You can also enable additional rules using [ACF](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) but it doesn't make huge sense if your users will be able to paste styled content from Word, but not able to apply them yourself using an editor.

I can recommend adding  `table`, `basicstyles`, `font`, `colorbutton`, `justify` plugins to get the best of the `pastefromword` plugin (sorry if I missed some plugin, but you see the point) - and soon `pagebreak`.

If you have more configuration related questions I can recommend using [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor) because GH tracker is used for issues reports mostly.
