### ISSUE TITLE
No File Browser in Upload Image

### ISSUE THREAD

**Issue by todayzhou** [ckeditor/ckeditor-dev#2677]
I can't find the file browser.
I choose the Standard.

![image](https://user-images.githubusercontent.com/29250391/49995036-06f30f00-ffc6-11e8-8ace-552cc1781484.png)

* Browser: Chrome/IE11
* OS: win10
* CKEditor version: 4.11.1
* Installed CKEditor plugins: Upload Image

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
