### ISSUE TITLE
Firefox 64 and selected images

### ISSUE THREAD

**Issue by divesr69** [ckeditor/ckeditor-dev#2681]
Hello, 
Since the last update of Firefox (64.0), I can not select an image and resize it by moving the corners. By clicking on the image, nothing happens, it is not selected, not visible in any case.
An idea.
Thank you very much

* Browser: Firefox 64.0
* OS: MAC OS X
* CKEditor version:  4.3 (revision d2184ac)

**Comment by Comandeer** [comment]
The issue is not reproducible in the newest version of CKEditor 4. I'd recommend you considering the upgrade, as newer versions of CKEditor 4 include not only various bug fixes, but also new features and higher security.

Alternatively, if upgrade is not an option, you can use [Enhanced Image](https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html) plugin, that includes custom resizer for images.
