### ISSUE TITLE
Paste image function is broken on Safari

### ISSUE THREAD

**Issue by clarence-guo** [ckeditor/ckeditor-dev#2687]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1.  Open an image to App 'Preview'
2.  Select any area of the image then copy it
3.  Paste into the editor

### Expected result

*The selected area of the image can be pasted into the editing area*

### Actual result

*Nothing happen. It's only reproducable on Safari, Chrome, FF, IE don't have the problem*

## Other details

* Browser: Safari 11.0.3
* OS: MAC 10.13.3
* CKEditor version: 4.11
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment]
Almost the same as #2301

You should use image upload plugin otherwise CKEditor won't be able to add image from clipboard, as [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) won't have any `text/html` data with images.

Try sample with uploader, to see that it works on any browser:
https://ckeditor.com/docs/ckeditor4/latest/examples/easyimage.html 

>Nothing happen. It's only reproducable on Safari, Chrome, FF, IE don't have the problem

Actually this can be reproduced on any browser except for Firefox. That is because Firefox natively transforms images pasted from clipboard into base64 encoded `<img>` tag.
