### ISSUE TITLE
CKEditor setData function add tbody tag to tables in HTML

### ISSUE THREAD

**Issue by kkataev** [ckeditor/ckeditor-dev#2696]
Could you please help to understand next issue?
I read attached file BEFORE_IMPORT.html and set it with setData() to CKEditor instance. But as you can see in file AFTER_IMPORT.html, some changes is appeared: tbody tags, and other.
Question is how can I turn off automatic changes with HTMLs in CKEditor when I setData() and toggle source code mode?
[Import ckeditor.zip](https://github.com/ckeditor/ckeditor-dev/files/2698832/Import.ckeditor.zip)
I tried config.allowedContent = true but no changes with this options.

## Other details

* Browser: Chrome
* OS: macos
* CKEditor version: 4.11
* Installed CKEditor plugins: full

Thanks, Kirill

**Comment by jacekbogdanski** [comment]
Hello,

I don't see the visual differences between these two files. On the source level, bear in mind that CKEditor needs to process HTML for editor purposes, so some output content may differ. 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
