### ISSUE TITLE
oembed plugin fetching jQuery from Google

### ISSUE THREAD

**Issue by iwrconsultancy** [ckeditor/ckeditor-dev#2703]
## Type of report
Bug

## Provide detailed reproduction steps (if any)
1. …CK 4.11.1 in Inline mode, with oembed (Auto Embed) plugin and dependencies loaded
2. …Firefox code inspector opened 

### Expected result
Nothing unusual 

### Actual result
Error message regarding failed attempt to load JQuery from Google.
![ckjquery-google](https://user-images.githubusercontent.com/13243881/50478832-5b858980-09cb-11e9-928b-57ffea2b79cf.png)

(Forbidden headers are an old module of ours, must update it when I get a round tuit.)  
 
## Other details
Issue does NOT arise with the oembed plugin for CK 4.9.1 -Looks like it's recent. 
No adverse consequences seen so far, but seems like it's not a good situation that we have a dependency on phoning home.
* Browser: Firefox
* OS: Any 
* CKEditor version: 4.11.1 (Latest as of filing) 
* Installed CKEditor plugins: Full standard set plus htmlwriter, mara,autolink,oembed,notification,widget,uploadwidget,lineutils,texzilla

**Comment by engineering-this** [comment]
The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
