### ISSUE TITLE
Is there any way to use custom plugin multiple times in config?   

### ISSUE THREAD

**Issue by yogita29Sharma** [ckeditor/ckeditor-dev#2704]
I have been created a custom plugin insertDD which will create the DropDown in CKEditor ToolBar.
I want to use this plugin to create two different Dropdown in ToolBar.
How Can i define in CKEditor Config?
Please Help me Out.

**Comment by yogita29Sharma** [comment]
I have been created a custom plugin **insertDD**  which will create the DropDown in CKEditor ToolBar.
I want to use this plugin to create two different Dropdown in ToolBar.

**Comment by mlewand** [comment]
You can't do that this way. Plugin interface is designed in a way that only one plugin instance can be run by a single editor instance at a time.

In that case you'd need to modify your `insertDD` plugin so that it allows for creating multiple entries in the toolbar, which isn't difficult.

At the same time note that this issue tracker is a place for reporting CKEditor bugs and not place for seeking advice or support.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
