### ISSUE TITLE
ckeditor maximize on a modal doesn't work properly.

### ISSUE THREAD

**Issue by rahimnagori** [ckeditor/ckeditor-dev#2725]
I have added ckeditor in a modal popup. When I click on maximize button in ckeditor, modal popup disappears, blur background is displayed and the ckeditor is also gone. Everything is stuck.
![image](https://user-images.githubusercontent.com/42448371/50723670-c723d100-1106-11e9-835b-26cc46f46e00.png)

hey @mlewand , I expect you to answer soon.
I'm doing something like this :
http://jsfiddle.net/8s2ockuw/
but due to multiple modal windows it is not working properly. Could you please help me with this ?

**Comment by rahimnagori** [comment]
hey @mlewand , I expect you to answer soon.
I'm doing something like this :
http://jsfiddle.net/8s2ockuw/
but due to multiple modal windows it is not working properly. Could you please help me with this ?

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
