### ISSUE TITLE
Toolbar button status on Android

### ISSUE THREAD

**Issue by mark-wade** [ckeditor/ckeditor-dev#2749]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-4/demo/ using an Android device (see below for details of device issue was reproduced on)
2. Clear the contents of the editor
3. Press the bold button on the toolbar
4. Type "foo".
5. Press the bold button on the toolbar again
6. Type "bar"

### Expected result

Editor shows "foo**bar**" and the bold button in the toolbar is unselected.

### Actual result

Editor shows "foo**bar**" but the bold button in the toolbar is selected.

![bs_realdroid_mobile_samsung galaxy s9 plus-8 0-1440x2960](https://user-images.githubusercontent.com/1433869/51095286-cde9cc80-1807-11e9-9d2a-1720b9e2b74c.jpg)

## Other details

* Browser: Google Chrome
* OS: Android 8
* CKEditor version: 4 (assumed latest - using https://ckeditor.com/ckeditor-4/demo/ for test)
* Installed CKEditor plugins: Whatever is on https://ckeditor.com/ckeditor-4/demo/

**Comment by engineering-this** [comment]
Hi,

Thank you for your submission. After looking into this issue I found out that it can be reproduced in very simple page without CKEditor. It is a browser bug. It happens when element keeps `:hover` pseudo class despite other element being focused.

Reported upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=924669

Sample to reproduce:
https://codepen.io/anon/pen/ErjZqw
