### ISSUE TITLE
Editor with enterMode set to ENTER_DIV alters content on paste

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2751]
## Type of report

Bug

## Provide detailed reproduction steps (if any). 

1. Open SDK sample: https://ckeditor.com/docs/ckeditor4/latest/examples/enterkey.html
2. Pick `Create a new <div>` from select under `When Enter is pressed:`
3. Focus editor at the end of content, press <kbd>Enter</kbd> and type some text.
4. Select all.
5. Copy.
6. Paste

### Expected result

Editor content looks like:
```
<div>This is some sample text.</div>

<div>New line.</div>
```

### Actual result

There is an extra div wrapping whole editor content:

```
<div>
<div>This is some sample text.</div>

<div>New line.</div>
</div>
```

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
Issue might be reproduce with `insertHtml` method.
1. Use editor in `ENTER_DIV` mode
2. Put selection in new line
3. Use `editor.insertHtml( '<div>one</div><div>two</div>' )`

Source of the problem is how we insert nodes. Wrapping DIV, which allows on writing in editor, remains in editor. When node is added to editor, selection is located directly in this `div`, not under the `body`.
https://github.com/ckeditor/ckeditor-dev/blob/1f365357c043a74e69ad21f32c829929d8610106/core/editable.js#L1899-L1906

This result in situation that we get additional div surrounded inserted content.
