### ISSUE TITLE
Issue with changing format of the texts

### ISSUE THREAD

**Issue by jayendra-sharan** [ckeditor/ckeditor-dev#2759]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

https://ckeditor.com/ckeditor-4/demo/#article

1. Create list elements.
2. Select all list elements.
3. Change the format/style of the text to heading [h1/h2/h3/h4/h5/h6].
4. Change the format/style back to normal.

### Expected result

Changing the style back to normal should revert it to the original state.

### Actual result

A `<p>` tag is added all the list elements. It adds extra space.

## Other details

* Browser: All
* OS: ALL
* CKEditor version: 4
* Installed CKEditor plugins: Not Applicable

**Comment by engineering-this** [comment]
Hi,

Thanks for your report.

This case is tricky. It makes sense that changing style back to normal should revert the change, and content should look the same as before applying heading. 

Currently applying styles transforms content as below:

When applying heading:
`<p>` -> `<h1>`, when `p` is missing, `h1` is created.
When applying normal:
`<h1>` -> `<p>`

Let's say we fixed your issue, and inside lists `<h1>` tag will be removed instead of replaced with `<p>`.

In such case we could create list like below:
```
<ol>
  <li><p>foo</p></li>
  <li><p>bar</p></li>
</ol>
```
Applying heading style, and then setting it back to normal would result in `<p>` tags being missing.

Such solution would just reverse the issue.

I don't think there is an easy way to fix this without creating new issue. Maybe other devs have any ideas?

**Comment by Comandeer** [comment]
Format plugin is used to apply block-level styling, therefore "Normal" option is just an alias for "add paragraph here". Please notice that content inside list item does not have any format applied as there is no block element inside by default.

To revert list item to original state you can just use undo functionality. You can also use [Remove Format](https://ckeditor.com/cke4/addon/removeformat) plugin, that [can be configured to remove also block-level styling](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removeFormatTags) ([demo](https://jsfiddle.net/Comandeer/d07scynj/)).
