### ISSUE TITLE
Set default style to paragraph

### ISSUE THREAD

**Issue by SuperManPHP** [ckeditor/ckeditor-dev#2765]
## Type of report

Task

## Provide description of the task

I'm newer in ckeditor. Help me please to set default style for paragraph ( `<p>`).
The Ckeditor by default put in out: 
- `<p>foo</p>`
How do it like this:
- `<p><span style="font-family: Arial"><span style="font-size: 14pt;">Foo</span></span></p>`

## Other details
Ckeditor version: latest version

**Comment by SuperManPHP** [comment]
Please help with anything, I will be very grateful

**Comment by engineering-this** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
