### ISSUE TITLE
Ckeditor not working

### ISSUE THREAD

**Issue by vikasvyas47** [ckeditor/ckeditor-dev#2785]
Hello

i am not able to make any changes in ckeditor in mobile and sometime desktop as well can you please resolve issue whenever i try to click on ckeditor then it's behave like disabled no focus action work on it i have checked in many mobile browser and sometime in browser as well.

i used ckeditor in angularjs application and following details where it's not work

* Browser: all mobile based chrome
* OS: android, IOS
* CKEditor version: 4.4.6

**Comment by jacekbogdanski** [comment]
My guess is that you are using [inline editing](https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html) but the element used to create CKEditor doesn't have `contenteditable=true` attribute.

However, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
