### ISSUE TITLE
Paste from CKEditor to Microsoft Word

### ISSUE THREAD

**Issue by Kingviech** [ckeditor/ckeditor-dev#2786]
## Type of report

When I copy the contents of a ckeditor with images and paste it into a word document, the images are shown as blank rectangles.

## Provide detailed reproduction steps (if any)

1. Copy contents of the editor instance including an image
2. Paste it inside word

### Expected result

I was expecting to get the images from my CKEditor instance to my word document.

### Actual result

Text contents are pasted correctly, images are shown as empty rectangles with their original size.

## Other details

* Browser: Chrome 71.0.3578.98, Firefox 65.0
* OS: Windows 10 Pro
* CKEditor version: 4.10.1
* Installed CKEditor plugins: simpleuploads, uploadimage, tableresize, autolink, clipboard, print, codesnippet, sourcearea

**Comment by Kingviech** [comment]
Comparing the clipboard contents of copy from ckeditor with copy from the html without activated ckeditor revealed the difference, that ckeditor clipboard contents have no set SourceUrl.

Example clipboard contents:
![image](https://user-images.githubusercontent.com/4802262/52107059-3d77fe00-25f5-11e9-84ac-97ba6465525f.png)

**Comment by mlewand** [comment]
Adding a SourceURL would not be best solution to that as it is Win-specific fix.

The reason for this problem is that most of the times developers use relative paths to the images. If only you force consistent absolute `[src]` attr value for images, then it works correctly.

See the screencast below:

![paste-abs-img-to-word](https://user-images.githubusercontent.com/5353898/52136175-c586f380-2647-11e9-95ab-aa5f578dfa27.gif)


Options are:
* Enforce absolute src to be used in the editor.
* Create a plugin that replaces data in a clipboard so that it always put absolute links. For that you'd have to listen for native `copy` event on the [editable](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editable.html) element. Don't recall it now but probably only recent browsers will provide you means to modify the clipboard there (which Chrome and Firefox will do :+1:). We can't add such thing in core as we can't modify our users markup.

However if you'd be willing to publish it as a plugin in our [Addons Repository](https://ckeditor.com/cke4/addons/plugins/all) that would be just great!
