### ISSUE TITLE
ckeditor custom menu hidden when sub-menu is displayed

### ISSUE THREAD

**Issue by elatedstar** [ckeditor/ckeditor-dev#2804]
Similar to Microsoft word we are developing custom menus like File, Edit, View, Format, Insert etc. 
Few menu items have sub menus. Under Format menu there is menu item Text-size which contains sub-menus options range 10, 50. 
Whenever user mouse over menu item with sub-menus it shows sub-menus properly but actual parent menu get disappear. 
I tried same with upgraded ckeditor but problem is still there. any idea how to solve that.

product version:
Chrome: 68.0.3440.75 
CkEditor: 4.7.2
Menu : 4.11.2
panel: 4.11.1
floatpanel: 4.11.1

**Comment by engineering-this** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
