### ISSUE TITLE
Find/Replace: Replace button doesn't show dialog

### ISSUE THREAD

**Issue by mbomb007** [ckeditor/ckeditor-dev#2825]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. I am using this build: https://ckeditor.com/cke4/builder/b400c11b7a97273b57230e270a5e4ac8
2. I am using the CKEditor module version 7.x-1.18 on Drupal 7, though I don't think this is important for reproducing the bug.
3. Open a page with CKEditor for the first time.
	a. If the first button I click is the Find button, the dialog is created and shows just fine.
    -  If I click Replace after this, the dialog will still not show, even though it was created by clicking Find. The behavior is the same as in 3b.

	b. If the first button I click is the Replace button, the semi-transparent layer that normally shows behind the dialog is created, but the dialog itself isn't and never shows. Using browser devtools, I can see that the dialog HTML was never added to the page.
    -  Once I have clicked Replace, due to the overlay being created/shown without the dialog, it is impossible to click anything else.

### Expected result

I would expect clicking the Replace button to create/show the dialog in the same way that the Find button does.

### Actual result

It doesn't.

## Other details

* Browser: tested on Chrome and Firefox
* OS: Windows 10
* CKEditor version: 4.11.2
* Installed CKEditor plugins: https://ckeditor.com/cke4/builder/b400c11b7a97273b57230e270a5e4ac8

**Comment by jacekbogdanski** [comment]
Removing [codemirror](https://ckeditor.com/cke4/addon/codemirror) plugin from presets fixes the issue, which means that this plugin is responsible for incorrect behavior. 

Codemirror plugin from your preset is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

**Comment by mbomb007** [comment]
Opened an issue: https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/issues/150

**Comment by mbomb007** [comment]
The issue has been fixed in codemirror.
