### ISSUE TITLE
how to pass data to the widget without opening a dialog window?

### ISSUE THREAD

**Issue by zuilafeng** [ckeditor/ckeditor-dev#2853]
Feature Issue

## Provide description of the new feature
I'v run across the situation that i wanna insert the chart widget as the same as the chart which has been rendered out of the ckeditor lately without opening a dialog window, so how can i pass my chart 
data into the widget init?

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
