### ISSUE TITLE
Can't use Mentions-plugin in Vue

### ISSUE THREAD

**Issue by apbln** [ckeditor/ckeditor-dev#2860]
When I start typing "@..." it doesn't show me my feed item(s), even if I type the whole name. I don't know whats wrong, but I'm missing something. This is my code:

[<template>
   <div>
  
      <vue-ckeditor v-model="content" :config="config" />

</div>
</template>

<script>
import VueCkeditor from 'vue-ckeditor2';

export default {
    name: 'test3',
    components: {
       VueCkeditor
    },
    data() {
        return {
            content:
                    'vue-ckeditor'
                ,
            config: {
                toolbar: [
                    ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']
                ],
                plugins: 'mentions',
                mentions: [
                    { feed: ['Dang Thanh', 'Sinh Hoa Long', 'Tuan Vo'], marker: '@' }
                ],
            },
        }

    }]

**Comment by jacekbogdanski** [comment]
The Vue integration you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the integration author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

**Comment by mlewand** [comment]
Also it make sense for us to create official Vue integration. We'd like to understand if there's a need for it, so @apbln if you're interested in that please add "👍" reaction to the main post in #2861.
