### ISSUE TITLE
Notification close button doesn't work after closing text editor dialogue

### ISSUE THREAD

**Issue by asukamae** [ckeditor/ckeditor-dev#2873]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
We use CKEditor as a dialogue. And a notification needs to be clicked a close button to disappear. 

The problem is that it is impossible to remove a notification clicking “x” close button, after closing the editor dialogue which the notification comes from. 

1. Open a text editor dialogue.
2. Show a warning dialogue which needs to be clicked a close button to disappear.
3. Close the CKEditor dialogue firstly.
4. The warning notification remains on screen, then click the close button. This doesn't work.

### Expected result

The notification is closed, even after closing text editor dialogue. We would like the function to have a conditional which checks if the editor is visible or not before "notification.editor.focus()", like if (!notification.editor.document.$.hidden).

### Actual result

The notification remains waiting for the CKE editor been focused. But it won't happen. And the process is blocked.

## Other details

* Browser: Firefox 65.0.1, Chrome 72.0.3626.119
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: wordcount, notification, htmlwriter

**Comment by f1ames** [comment]
Thanks for reporting @asukamae.

Is this some kind of the custom dialog or a framework (like bootstrap)? Is there any error in the console while trying to close the notification.

Generally, the good idea will be to hide/remove all notifications when editor dialog is closed (since dialog itself is not the part of the editor, it will require some custom code). It can be achieved by listening to [`notificationShow` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-notificationShow) which contains opened notification (so it can be stored for later use) and then when dialog is closed all [visible notifications](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_notification.html#method-isVisible) can be [dismissed](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_notification.html#method-hide).

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
