### ISSUE TITLE
Dynamic data feeding for plugins

### ISSUE THREAD

**Issue by SuperDevGuru** [ckeditor/ckeditor-dev#2880]
## Type of report

Feature request

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*
I want to be able to feed data to plugins (e.g. strinsert) dynamically from api response.

**Comment by jacekbogdanski** [comment]
Hello,

sorry, but I have no idea what do you mean. Could you precise your feature request and add some example use cases?

**Comment by SuperDevGuru** [comment]
So after initialization, can we change the items in dropdown created by strinsert extraplugin in toolbar?

**Comment by jacekbogdanski** [comment]
I get it, you are asking about [StrInsert](https://ckeditor.com/cke4/addon/strinsert) plugin, sorry for the misunderstanding. The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
