### ISSUE TITLE
How to get CKEditor support Hebrew with metions plugin?

### ISSUE THREAD

**Issue by LielZ** [ckeditor/ckeditor-dev#2946]
How to get CKEditor support Hebrew with metions plugin?

Im use mention plugin with CKEditor and I have a problem with the hebrew(i think its because the RTL), when I use english its work fine with hebrew its show me the suggested names but when I starts typing the next word it didn't work its just disappear. I have try to make the sign an hebrew sign that support rtl, but its still dont work.

one image equal to 1000 words :P http://prntscr.com/mv7npv
 
CKEditor version 4.11.3
Browsers: trying all the browsers

Thanks!

**Comment by jacekbogdanski** [comment]
Mentions plugin uses general regex matching English alphabet and popular diacritics (`_a-zA-Z0-9À-ž`) although it doesn't support all possible languages by default. You can easily extend it with your own regex using mentions API, e.g.:

```javascript
config.mentions = [
   {
      feed: feedArray,
      marker: `#`,
      pattern: /#[_a-zA-Z0-9À-ž\u0590-\u05fe]$/
];
```
You can find out more reading our docs, especially https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_mentions_configDefinition.html#property-pattern

Note that I just used the first match when googling for Hebrew regex in my example, so its untested and may require some adjustments.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore if it won't resolve your issue, please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by LielZ** [comment]
> Mentions plugin uses general regex matching English alphabet and popular diacritics (`_a-zA-Z0-9À-ž`) although it doesn't support all possible languages by default. You can easily extend it with your own regex using mentions API, e.g.:
> 
> ```js
> config.mentions = [
>    {
>       feed: feedArray,
>       marker: `#`,
>       pattern: /#[_a-zA-Z0-9À-ž\u0590-\u05fe]$/
> ];
> ```
> 
> You can find out more reading our docs, especially https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_mentions_configDefinition.html#property-pattern
> 
> Note that I just used the first match when googling for Hebrew regex in my example, so its untested and may require some adjustments.
> 
> Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore if it won't resolve your issue, please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.
> 
> If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

i'll try it, thank you so much.
