### ISSUE TITLE
Incorrect MathJax output format

### ISSUE THREAD

**Issue by shaneikennedy** [ckeditor/ckeditor-dev#2982]
## Type of report

Bug

## Steps to reproduce

1. Insert math formula using mathjax plugin
2. The editor will show the equation

### Expected result

It is expected to see the equation in the output format which is specified in the MathJax config parameter

### Actual result

We see the equation in the preview_html output format (http://docs.mathjax.org/en/latest/output.html?highlight=renderer)

## Other details
This markup is found on the demo page
```html
<span id="preview">What is shown (preview_html output format)</span>
<span id="buffer" style="display: none;">What should be shown (HTML-CSS output format)</span>
```
When you set the display property of the "preview" span to none and remove the `display: none` property from the "buffer" span you are shown the equation with the correct output format
* Browser: Chrome
* OS: MacOS
* CKEditor version: 4.11.3

**Comment by jacekbogdanski** [comment]
Hello,

I'm not sure if I understand you correctly. 

>When you set the display property of the "preview" span to none and remove the display: none property from the "buffer" span you are shown the equation with the correct output format

The styles are copied from the editor to keep MathJax computation styling close to the content. When you switch display properties, you just see unstyled computation:

![mathjax](https://user-images.githubusercontent.com/10279586/55542125-b283b480-56c6-11e9-8993-fad4a315653d.gif)

Could you give more examples where you see incorrect format?

> It is expected to see the equation in the output format which is specified in the MathJax config parameter

What "config MathJax parameter" do you mean? CKEditor allows you to set [mathJaxClass](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-mathJaxClass) and [mathJaxLib](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-mathJaxLib). Are you talking about config passed with `mathJaxLib` library path? If so, could you attach some examples with the current and expected format?

**Comment by shaneikennedy** [comment]
Hey @jacekbogdanski , thanks for getting back to me. You are correct that the proper mathjax output format is being shown. I was confused because the mathjax output is then modified by the styles applied by the editor. Is there a way to prohibit the editor from applying styles to our latex? My use case involves saving the html source from the editor using `window.CKEDITOR.instances.editor.getData();` and then displaying that source on another page where the standard Mathjax library is then ran, and getting a differently styled output.

**Comment by jacekbogdanski** [comment]
Using [`editor.getData`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-getData) results with semantic editor HTML. So in a case like inserting MathJax formula into a header, you will get something like:

```html
<h1>Hello world!<span class="math-tex">\(x = {-b \pm \sqrt{b^2-4ac} \over 2a}\)</span></h1>
```
As you can see styles are not inlined or somethow preserved. Different computation style is based on your page CSS styles, not CKEditor. You could use `math-tex` class or even better your custom [`MathJax class`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-mathJaxClass) to force the same style between wrapping elements on your web page.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore if you have more issues with your own web page styles, leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
