### ISSUE TITLE
Make integrations more visible

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#2990]
## Type of report

Docs

## Provide a description of requested docs changes

Basically, our docs contains a lot of content, and integration guides and example are somewhere between other stuff. If somebody doesn't know what to look for it might be hard to find.

I have two suggestions to make them more visible:

## 1. Add section on the main docs page

The page is https://ckeditor.com/docs/ckeditor4/latest/index.html and with additional section it may look like:

![Screen Shot 2019-03-27 at 11 30 08](https://user-images.githubusercontent.com/1061942/55069459-6ca26d00-5084-11e9-80b6-79531638a283.png)

## 2. Extract integrations to separate category

Now they are split between guides and examples (which generally makes sense because some are guides and some are examples), but maybe could be extracted as a separate main category. However, I'm not sure because then all other integration guides should be moved to keep things consistent (Easy Image, File Managers, jQuery, etc.). Anyway, it could look like:

![image](https://user-images.githubusercontent.com/1061942/55070630-00753880-5087-11e9-9302-497afdd56386.png)

☝️ On the screenshot above it looks quite empty so maybe moving other integrations would not be a bad idea to have more content there.

---

WDYT? cc @AnnaTomanek

**Comment by jacekbogdanski** [comment]
1. :+1: 
2: :+1:
 
Both ideas are fine. It will make integration docs much more visible.

**Comment by wwalc** [comment]
Aren't you afraid that the separate integration section would look quite dumb?

**Comment by jacekbogdanski** [comment]
From my perspective, it shows that we are open for integrations which are always in high demand. I even feel like some users may choose CKEditor4 from different WYSIWYG editors based on available integration for easier implementation, so such information seems important and should be easily visible. Although, pt 1 may be enough to accomplish it.

**Comment by engineering-this** [comment]
1. 👍 
2. no opinion

**Comment by f1ames** [comment]
> Aren't you afraid that the separate integration section would look quite dumb?

I have some doubts, especially if it will be quite empty or mix slightly different topics (e.g. integration with React and Easy Image). From the other hand, for people using frameworks like React or Angular, integration guides are basically "Getting Started" sections from where they should start to read the docs so it should be really easy to find.

**Comment by wwalc** [comment]
Related: https://github.com/cksource/bigbang-ckeditor.com/issues/1441

**Comment by AnnaTomanek** [comment]
I'd probably recommend to start with (1), and with https://github.com/cksource/bigbang-ckeditor.com/issues/1441. 

A separate Integrations section may work, but it would require some thinking over because at the moment the content there is not too consistent: we have both integrations with frameworks (Angular, React, jQuery), but also integrating CKEditor with things that are essentially plugins (EI, CKF, AC). It actually makes you wonder why these things are not in Functionality Overview if all other plugins are described there.

Another thing is, currently the Guides category is quite crowded but maybe if we extracted the entire Functionality Overview section to a separate Features tab (this was actually a plan a while ago but we first waited for porting the SDK and then forgot...), then the Integrations part should be easier to find.

Additionally, integrations are something that could be linked from a few places, like the Quick Start Guide. Or actually, the Quick Start Guide should be rewritten to mention that there are other modern installation methods, including `npm` and React/Angular integrations. This guide was written when downloading the zip package was still a thing, even before we had the CDN (this section was added later) 😱 .

**Comment by f1ames** [comment]
Extracted tasks with integrations section (#2998) and updating `Getting Started` page (#2999).

**Comment by jacekbogdanski** [comment]
I'm also thinking about adding information about angular and react integrations into npm description https://www.npmjs.com/package/ckeditor
It would be easier to discover both integrations directly from npm. WDYT?

**Comment by f1ames** [comment]
> I'm also thinking about adding information about angular and react integrations into npm description https://www.npmjs.com/package/ckeditor
It would be easier to discover both integrations directly from npm. WDYT?

I had a similar idea about npm readme and readme in `ckeditor-dev` repo, so 👍from me.

Related issue #3085.

**Comment by f1ames** [comment]
Closing as both #2999 and #2998 are already done.
