### ISSUE TITLE
Add integrations section on the main docs page

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#2998]
## Type of report

Docs

## Provide a description of requested docs changes

Extracted from #2990.

The main docs page (https://ckeditor.com/docs/ckeditor4/latest/index.html) should have additional integrations section (mentioning Angular, React and maybe also other integrations) like on the screenshot below:

![Screen Shot 2019-03-27 at 11 30 08](https://user-images.githubusercontent.com/1061942/55069459-6ca26d00-5084-11e9-80b6-79531638a283.png)

**Comment by wwalc** [comment]
Just a comment that since we plan to add also the Vue.js integration we may already include it in the documentation. Later on we can just update the documentation with the progress of the issue, or at the very beginning with an information that it is planned / under development. Thanks to that we'd have one more item more there and for anyone interested in Vue.js integration the status of it would be clear.

**Comment by f1ames** [comment]
I think we can already link here to Vue integration section too (which will be added with #3090).

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor-docs/commit/adffd612a473340de7a1b704e61f687879808389.
