### ISSUE TITLE
How Can I check the Uniqueness of CKEditor field?  

### ISSUE THREAD

**Issue by akshaybajpei92** [ckeditor/ckeditor-dev#3002]
## Steps 
Note: I want to identify the similarity in in Ckeditor output source which gets stored in database.
1. I have a field for storing Html in my database which is linked to CKEditor.
2. When user stores the data it is stored as new filed.
3. I want if there is already the same data in my coloum, then it should inform me, Can it be possible?

### Expected result

*I must be aware that same data already exists in my table, so I can link it rather than adding to avoid redundancy and repetition!*

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 4
* Installed CKEditor plugins: Standard Editor

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
