### ISSUE TITLE
How to get cursor pointer to a ckeditor on basis of id provided to a ckeditor?

### ISSUE THREAD

**Issue by Neha7777** [ckeditor/ckeditor-dev#3009]
I am not able to set focus to the ckeditor on basis of id. Please help me out I am stuck on this from past 2 month.
I have tried javascript setfocus() and focus() methods too but those didn't helped me.
And also tried this.But didn't worked for me
var selection = editor.getSelection();
  var ranges = selection.getRanges();
  var range = ranges[0];

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
