### ISSUE TITLE
Form Elements - Can't add a new form element after you edit an already existing form element

### ISSUE THREAD

**Issue by Deedubsy** [ckeditor/ckeditor-dev#3013]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Add text box to screen
2. Double click on the textbox
3. Change nothing and click ok
4. Try to add another textbox

### Expected result

A new textbox should appear

### Actual result

It is editing the previously edited textbox

## Other details

This happens to all form elements

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.11.3
* Installed CKEditor plugins: Forms

**Comment by f1ames** [comment]
Hello @Deedubsy,
from what I can see a new textbox can be inserted the way you have described. The thing here is that when you double click the textbox to open the dialog (step 2) and then close the dialog (step 3) the focus is still on the same textbox (however, it seems to be invisible in Chrome) and when you open the dialog again you are editing this textbox.

To insert the new one you need to move selection after the textbox (by mouse click or using arrow keys).

**Comment by Deedubsy** [comment]
Hi @f1ames 
I've tried clicking on other parts of the page and it still seems to hold the previously selected dialog box in focus when trying to add a new one.

**Comment by jacekbogdanski** [comment]
Hello, it seems like the issue is caused by **not moving** selection outside form control as already wrote @f1ames, however, keeping a selection on currently editing element is expected behavior. Please, see how form control element is correctly inserted when I moved selection outside the previously inserted text input.

![form](https://user-images.githubusercontent.com/10279586/60804660-49588500-a17e-11e9-9a93-edac941b8896.gif)
