### ISSUE TITLE
emoji plugin i18n

### ISSUE THREAD

**Issue by qwwdezone** [ckeditor/ckeditor-dev#3021]
I try to add lang file in emoji plugin lang folder, but the translate file can't work. 
this is my language file. please add.
[https://9gag-1252458227.cos.ap-chengdu.myqcloud.com/zh-cn.js](url)

**Comment by f1ames** [comment]
Hello @qwwdezone,

If you would like to contribute your translations, we're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings. Please send your contribution there, so that we can pull it into upcoming release.

If you are trying to edit plugin only for your needs, you may refer to [Plugin SDK docs](https://ckeditor.com/docs/ckeditor4/latest/guide/plugin_sdk_intro.html) and also [`pluginDefinition.lang` property](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_pluginDefinition.html). One more hint, you need to use dev/source version of CKEditor (the build one have all language files bundled into one file).
