### ISSUE TITLE
how do i stop to change place of  tags in edit mode  

### ISSUE THREAD

**Issue by Devang-stapin** [ckeditor/ckeditor-dev#3053]
## Type of report

The task in my system I have two screen 
1) insert page content into ckediter
2) edit that page content who enter into 1 screen in ckeditor

problem: when I am in 2 screen without edit any word ckeditor change tags place into source 
kindly help me

## Provide a description of the task

*What steps should be taken to fulfill the task?*

## Other details

* Browser:…
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
