### ISSUE TITLE
how can I get the css file of document editor in demo?

### ISSUE THREAD

**Issue by LouisMing** [ckeditor/ckeditor-dev#3076]
## Type of report

Docs
how can I get the css file of document editor in demo?
And how to config it ?

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
