### ISSUE TITLE
Undefined variable when removing event listener that was attached twice

### ISSUE THREAD

**Issue by jackwickham** [ckeditor/ckeditor-dev#3078]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
When you call `editor.on`, it returns an object with a method `removeListener` which removes this event listener. If you call `editor.on` twice with the same event type and listener, the listener is not attached multiple times, and the returned object throws an exception if you try to call `.removeListener`.

```js
function(editor) {
    this.respond = function(e) {
        // This method is only called once, because the event listener was only attached once
        this.listener.removeListener(); // this will fail
    }

    editor.on( 'change', this.respond, this);
    this.listener = editor.on( 'change', this.respond, this);
}
```

### Expected result

Calling `this.listener.removeListener()` should successfully remove the listener.

### Actual result

An exception is thrown because the method tries to use variable `me` which is not initialised if this is the second (or later) call to `editor.on` with the same event and listener.

## Other details

* Browser: any
* OS: any
* CKEditor version: at least 4.10.0
* Installed CKEditor plugins: any

This issue is fixed by #2967

**Comment by jacekbogdanski** [comment]
CKEditor4 event listeners are recognized by delegation rather than value, so writing something like 
```javascript
function foobar() {
    console.log( 'foobar' );
}

editor.on( 'change', foobar );
editor.on( 'change', foobar' );
```

will register only the single listener for `foobar` function, and this behavior is correct.

Nevertheless, I see that calling `removeListener` twice on the same listener doesn't throw an error, so it seems like a bug. Just take caution to **not fix** correct behavior accidentally :smile:

**Comment by jacekbogdanski** [comment]
Actually, after the second thought, I would consider this issue by design. You shouldn't attach the same delegate twice and such error message gives you information that something is incorrectly implemented in your application. I would rather improve the error message during the attachment process than fix issue coming from incorrect usage.

It's rather a subjective opinion, @f1ames would like to know if you agree or would like to discuss it / reopen the issue.

**Comment by f1ames** [comment]
> Actually, after the second thought, I would consider this issue by design. You shouldn't attach the same delegate twice and such error message gives you information that something is incorrectly implemented in your application. I would rather improve the error message during the attachment process than fix issue coming from incorrect usage.

Yes, I agree that this is an intended behavior. For me, it makes sense to throw an error when the same delegate is attached more than once. Also the result of such call (depending if an error will be only logged or throwed to break code execution), should be probably an empty object or null to not further confuse the developers.

**Comment by jackwickham** [comment]
For what it's worth, the actual code which was triggering this issue on my site can be reduced to something like this:
```js
function listenerA() {
    setTimeout(() => {
        editor.removeListener('change', listenerA);
        this.listener = editor.addListener('change', listenerB, this);
    });
}
function listenerB() {
    this.listener.removeListener();
}
editor.addListener('change', listenerA, this);
```
If listenerA is called multiple times before the async code is executed, it breaks `this.listener`. This can be refactored to be fixed, but it isn't obvious that it would need to be, especially because it's a race condition that only occurs occasionally. The actual code is of course a bit more subtle.
