### ISSUE TITLE
Fix bad JSON parse ckeditor/plugins/emoji/emoji.json file

### ISSUE THREAD

**Issue by davidromani** [ckeditor/ckeditor-dev#3080]
## Type of report

Task

## Provide description of the task

Bad JSON parse result after execute `yarn encore dev` command (Webpack manager)

## Other details

* Browser: Safari 12.1
* OS: macOS 10.14
* CKEditor version: 4
* Installed CKEditor plugins: all

<img width="1420" alt="Captura de Pantalla 2019-04-29 a les 17 42 26" src="https://user-images.githubusercontent.com/698779/56908350-6d288c00-6aa6-11e9-874b-901ba2620bcf.png">

**Comment by jacekbogdanski** [comment]
Emoji JSON file seems to be correctly formatted with RFC 4627 standard. CKEditor4 is written to support older browsers without recompilers, so it should be added directly to the page instead of using Webpack (eventually with some kind of external dependency). You can see examples in [our docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html), this information is also available on npm "[Getting started](https://www.npmjs.com/package/ckeditor#getting-started)".
