### ISSUE TITLE
Unit pickers in cell properties have different width

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor-dev#3098]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor4/latest/examples/table.html
2. Right-click on any cell in table and choose `Cell -> Cell properties`

### Expected result

`Width` and `Height` boxes should be the same width

### Actual result
Boxes has different width, which leads to different unit pickers width (to be introduced in #3075 - https://github.com/ckeditor/ckeditor-dev/pull/3075#pullrequestreview-236110294):

<img width="355" alt="Screenshot 2019-05-13 at 11 43 44" src="https://user-images.githubusercontent.com/10883184/57612266-ceeff800-7574-11e9-9748-c4433ad25b21.png">

<img width="366" alt="Screenshot 2019-05-13 at 11 43 54" src="https://user-images.githubusercontent.com/10883184/57612273-d44d4280-7574-11e9-9b8f-3cde82bc2c64.png">

## Other details

Both elements have exactly the same styling. It may seem that the problem is caused by longer label for `Height` than `Width`, but changing it doesn't resolve the issue (image from #3075 mentioned above):
<img width="228" alt="Screenshot 2019-05-13 at 10 44 02" src="https://user-images.githubusercontent.com/10883184/57612443-24c4a000-7575-11e9-9bd0-e3da47ec079b.png">
 

* Browser: every
* OS: macOS
* CKEditor version: 4.11.4, at least as old as 4.7.0
* Installed CKEditor plugins: `tabletools`

**Comment by engineering-this** [comment]
It's some quirk of table layout which we use in our dialog.
There is spacing element between columns, removing it seems to solve the problem.
![Screenshot 2019-05-13 at 11 57 51](https://user-images.githubusercontent.com/23366849/57613095-5c801780-7576-11e9-88eb-87b5249b42d1.png)
IMHO there are better ways to add space between elements (`margin-right`), however adding general CSS rule might affect other dialogs, so some research is needed here. Also condition shouldn't match the last element. Depending on allowed content Cell Properties dialog may have only one column.

**Comment by engineering-this** [comment]
The actual cause of this issue is invisible label for select field. Label has style `visibility:hidden`, so it takes space and makes cell containing it wider.

I've removed this style to show how much space it takes:

![Screenshot 2019-05-15 at 11 21 56](https://user-images.githubusercontent.com/23366849/57767921-caf5de80-770a-11e9-86b0-bf24d4319d44.png)
![Screenshot 2019-05-15 at 11 24 47](https://user-images.githubusercontent.com/23366849/57767923-ccbfa200-770a-11e9-935d-1a2088b5871e.png)

Note, there is added label for width type.

This issue can be fully fixed by adding `display:block;width:0;` and I think we can do it in #3075
