### ISSUE TITLE
getting blank post using CKEditor

### ISSUE THREAD

**Issue by vinay158** [ckeditor/ckeditor-dev#3121]
When i m using some words like "select" or "from"  in ckeditor-4 content i m getting blank post. sometimes it's works but sometimes return me blank post in PHP.

**Comment by f1ames** [comment]
It's most probably the issue with the integration on the backend. Please check what [`editor.getData()`](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_savedata.html#retrieving-data-from-ckeditor) returns. If it returns expected content it means the data is lost somewhere along the way.

**Comment by vinay158** [comment]
yes it returns expected content, but i still cant find actual issue and getting empty POST. please suggest.

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
