### ISSUE TITLE
filebrowser plugin does not work

### ISSUE THREAD

**Issue by razmazka** [ckeditor/ckeditor-dev#3139]
http://prntscr.com/nuup7w
OpenCart 2.0.1.0
After installing the full package CKEditor v4.11.4, the filebrowser plugin does not work.
Did as written in the instructions:

Enable the plugin using the extraPlugins configuration option. Sample:
config.extraPlugins = 'filebrowser';

Now the config .js file looks like this:
/ **
  * @license Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
  * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
  * /

CKEDITOR.editorConfig = function (config) {
// Define changes to default configuration here. For example:
// config.language = 'fr';
// config.uiColor = '# AADC6E';
         // config.extraPlugins = 'filebrowser';
};

config.extraPlugins = 'filebrowser';

Please help.

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
