### ISSUE TITLE
Selecting text in a paragraph and change the format to heading changes the whole paragraph to heading

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#3145]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Write a paragraph in ckeditor.com demo page.
2. Select some text and choose "Heading1" from drop down.
3. The whole paragraph changes to Heading1.

### Expected result

Only the selected text should change to Heading.

### Actual result

The whole paragraph changes to heading. I understand the heading is a block format which is expected. But our Program manager's expectation is just selected text changes to heading. 

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.11.4
* Installed CKEditor plugins: not relevant.

**Comment by jacekbogdanski** [comment]
> I understand the heading is a block format which is expected. 

The statement is right and it's working by design. I cannot imagine heading as an inline element for web page, it would change its purpose as content navigation, especially for screen readers.

You may want to take a look into [`CKEDITOR.config.styleSet`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_stylesSet.html). You could use a styled inline element as a header.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
