### ISSUE TITLE
How should limit file type of image upload , i want user only select image

### ISSUE THREAD

**Issue by Dolov** [ckeditor/ckeditor-dev#3237]
## Type of report

Task

## Provide description of the task

How should limit file type of image upload , i want user only select image

## Other details

* Browser: …Chrome
* OS: …mac
* CKEditor version: …4.12.1 (Standard)
* Installed CKEditor plugins: …image2,uploadimage

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
