### ISSUE TITLE
CKEditor Icons Disappear When Presentation is Changed

### ISSUE THREAD

**Issue by bethwhitmer** [ckeditor/ckeditor-dev#3259]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

The icons in the CKEditor disappear after a user applies a custom user style sheet in Internet Explorer 11. This can be done by going to Tools > Internet Options > Accessibility > Format documents using my style sheet. See attached screenshot. Let me know if you need a copy of the custom user style sheet we are using. 

WCAG Success Criterion 1.3.1 Info and Relationships requires that "information and relationships that are implied by visual or auditory formatting are preserved when the presentation format changes. For example, the presentation format changes when the content is read by a screen reader **or when a user style sheet is substituted for the style sheet provided by the author."**

### Expected result

When Windows High Contrast Mode is enabled, the icons are replaced with fallback text. This is documented here: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_a11y.html#high-contrast-mode. We would expect a similar result for when a custom user style sheet is defined. 

### Actual result

Currently the icons for the various editor buttons (e.g. Bold, Italic, Underline, etc.) disappear when a custom user style sheet is applied in Internet Explorer 11. 

## Other details

* Browser: Internet Explorer 11
* OS: Windows 7
* CKEditor version: 4
* Installed CKEditor plugins: None that I know of
![CKEditorUSS](https://user-images.githubusercontent.com/29867095/60932685-28328a00-a28d-11e9-92a5-8cb02c58dc79.png)

**Comment by f1ames** [comment]
Hello @bethwhitmer,
can you provide the stylesheet you are using which causes this issue?

**Comment by bethwhitmer** [comment]
@f1ames hello! It's actually also happening if I disable images in Internet Explorer 11 by going to Tools > Internet Options > Advanced > Show Pictures
![CKEditorNoImages](https://user-images.githubusercontent.com/29867095/60984743-370b5200-a30a-11e9-87da-55749bc746cc.png)

**Comment by f1ames** [comment]
> It's actually also happening if I disable images in Internet Explorer 11 by going to Tools > Internet Options > Advanced > Show Pictures

Do you mean it's also happening or disabling images is the only cause (and not spreadsheet changing)?

Since buttons icons are images it's expected behaviour that they will disappear when images are blocked. I don't see any way it could be detected and handled by CKEditor itself🤔 Also keep in mind that buttons have labeling (and aria attributes) so it should be a browser job to show proper text instead (however, I assume this is not what blocking images should do).

**Comment by bethwhitmer** [comment]
@f1ames It's happening in both scenarios...if we apply a user style sheet and if images are removed in the browser.

**Comment by f1ames** [comment]
@bethwhitmer thank you for clarification, we will recheck this issue 👍

**Comment by f1ames** [comment]
From what I can see, the setting which breaks CKEditor icons, is not stylesheet itself but `Ignore colors specified on webpages`:

Only stylesheet added (no changes due to higher specificity of the webpage CSS rules):
<img width="871" alt="Screenshot 2019-07-11 at 08 37 47" src="https://user-images.githubusercontent.com/1061942/61028159-4d6fe700-a3b8-11e9-9015-7e92bce134fc.png">

Stylesheet added + `Ignore colors specified on webpages` on:
<img width="890" alt="Screenshot 2019-07-11 at 08 38 05" src="https://user-images.githubusercontent.com/1061942/61028240-7bedc200-a3b8-11e9-91e1-e4133b4bc59e.png">

Only `Ignore colors specified on webpages` on:
<img width="821" alt="Screenshot 2019-07-11 at 08 38 22" src="https://user-images.githubusercontent.com/1061942/61028214-6aa4b580-a3b8-11e9-8f29-50b5099583e0.png">

Which means the **WCAG Success Criterion 1.3.1**

> ... or when a user style sheet is substituted for the style sheet provided by the author.

is still fulfilled.

**Comment by bethwhitmer** [comment]
@f1ames thanks for researching. We aren't using the "ignore colors specified on webpages" option. I need to confirm I have clearance to share our custom user style sheet and then will comment back.

**Comment by f1ames** [comment]
Thanks @bethwhitmer, maybe you have some specific styles which breaks CKEditor button icons. It will be useful if you could provide a stylesheet (or just a part of it).

**Comment by bethwhitmer** [comment]
@f1ames Attached is our user-defined style sheet. The rationale is that some people have contrast sensitivity so they might apply a style sheet like this with lower contrast to avoid eye strain. They apply the background color that works for them and this overrides the background color on the site. The images for the CKEditor buttons do not show up when the USS is applied. 

[custom_user_styles_light.zip](https://github.com/ckeditor/ckeditor-dev/files/3398419/custom_user_styles_light.zip)

**Comment by f1ames** [comment]
@bethwhitmer thanks for sharing your stylesheet.

> The rationale is that some people have contrast sensitivity so they might apply a style sheet like this with lower contrast to avoid eye strain.

I understand, it makes perfect sense. However, when overriding styles, there always may be a rule which breaks something somewhere. Looking at your stylesheet, the rule which breaks CKEditor buttons is:

```css
*, html, body {
  background: #AB9B79 !important;
}
```

because it overrides all `background-*` rules for all document elements:

![image](https://user-images.githubusercontent.com/1061942/61808511-d288e080-ae3b-11e9-9dc4-b197c8db0c3e.png)

when changed to:

```css
*, html, body {
  background-color: #AB9B79 !important;
}
```

it works fine (tested on Chrome):

![image](https://user-images.githubusercontent.com/1061942/61808633-14b22200-ae3c-11e9-91cb-d9643c014f8e.png)

---

I noticed the comment in your stylesheet which seems to be the reason of `background` only rule:

> set the background to Tan (NOTE: setting just background-color: #000 !important did not work in Firefox so this declaration was changed to just background)

But works fine for CKEditor on FF ():
