### ISSUE TITLE
h-card drag and drop not working in ipad

### ISSUE THREAD

**Issue by rpapillo** [ckeditor/ckeditor-dev#3268]
Bug
Implemented drag and drop with h-card ckeditor version 4.3

The h-card elements can be dragged and dropped into the ckeditor area.

h-card elements are disabled in iPad

* Browser: iPad safari, Android iPad browser
* CKEditor version: 4.3
* Installed CKEditor plugins:h-card, justify, sourcedialog

**Comment by engineering-this** [comment]
Hello

`h-card` plugin is a third-party one and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

Additional note: Touch devices doesn't emit drag and drop events, so it can't work out of the box. Drag and drop could be somehow polyfilled for such devices based on touch events, however this would be a big feature request.
