### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasFocus' of undefined

### ISSUE THREAD

**Issue by plecos** [ckeditor/ckeditor-dev#3285]
## Type of report

Issue

## Provide detailed reproduction steps (if any)

Used the build option on the website to get a basic build of ckEditor
Added to web application 
<head>
...
<script src="~/ckeditor/ckeditor.js" type="text/javascript"></script>
</head>
<body>
....
<textarea id="ScopeOfWork" name="ScopeOfWork" width="100%" rows="10">Some Text</textarea>
                <script type="text/javascript">
                    CKEDITOR.replace('ScopeOfWork');
                </script>

### Expected result

The textarea should have become a ckEditor and worked

### Actual result

I see the editor, but no text in it, and no buttons work.  If I click on something, I get:

Uncaught TypeError: Cannot read property 'hasFocus' of undefined
    at $.showBlock (ckeditor.js:759)
    at b.show (ckeditor.js:780)
    at ckeditor.js:960

The sample included works.

## Other details

* Browser: Google Chrome v75.0.3770.100 & Internet Explorer v11.1268.16299.0
* OS: Windows 10
* CKEditor version: 4.12.1
* Installed CKEditor plugins: clipboard,dialog,image,link,magicline,pastefromword,scayt,specialchar,table,tableselection,tabletools,widget,wsc

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
