### ISSUE TITLE
Plugin 'find' loses its plugin.js during build process

### ISSUE THREAD

**Issue by ConnorSinnott** [ckeditor/ckeditor-dev#3286]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Clone this repository
`git clone https://github.com/ckeditor/ckeditor-dev.git`
2. Run build
`bash ckeditor-dev/dev/builder/build.sh`
3. Examine plugin 'find'
`ls ckeditor-dev/dev/builder/release/ckeditor/plugins/find/`

### Expected result
`dialogs/  icons/  lang/  plugin.js*`

### Actual result
`dialogs/`

## Other details

* CKEditor version: 4.13.0

**Comment by ConnorSinnott** [comment]
I can work around this issue by manually copying the find plugin into the release's plugin directory.

**Comment by jacekbogdanski** [comment]
CKE4 release builder takes care of some optimization where smaller plugins seem to be merged with the bundle directly to limit server querying. If you open the builder output sample or just initialize CKEditor using the release version, you will see that `find` plugin works fine.

If you need to modify some plugin files, please, do it before running builder, otherwise, you will get release version which is not supposed to be modified.
