### ISSUE TITLE
How to configure sharedspace and wordcount plugins? Is it compatible?

### ISSUE THREAD

**Issue by christinetlse** [ckeditor/ckeditor-dev#3288]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …When I install sharedspace plugins, it functions. When I install wordcount plugin, it functions. But When I want both, wordcount doesn't function. 
2. …
3. `<script type="text/javascript">
    CKEDITOR.replace('texte-nouvelle',{
        width   : '600px',
        height  : '1200px',
        toolbar : 'MyToolbar_user',
        wordcount: {
            showParagraphs: false,
            showWordCount: false,
            showCharCount: true,
            countSpacesAsChars:true,
            countHTML:false,
            maxWordCount: -1,
            maxCharCount: 7000
        },
       extraPlugins: 'sharedspace',
        sharedSpaces: {
            // Configure the editor instance to place the toolbar in the div id='top'.
            top: 'top',
    }});
</script>`

### Expected result
The both function.
*What is the expected result of the above steps?*

### Actual result
Only sharedspace `functions.`
*What is the actual result of the above steps?*

## Other details

* Browser: …Google chrome
* OS: …
* CKEditor version: 4-12 …
* Installed CKEditor plugins: …sharedspace and wordcount

**Comment by Dumluregn** [comment]
[Word Count & Char Count Plugin](https://ckeditor.com/cke4/addon/wordcount) you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

Also please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
