### ISSUE TITLE
trigger onHover event for ckeditor buttons

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor-dev#3289]
I want to know whether the ckeditor supports the following features ,If it supports how to do it

1.Can we give a popup onHover on any of the ckeditor buttons

2.can we add additional text in the dialog box that appears when we click any ckeditor button

**Comment by Dumluregn** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

Also it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we will be unable to have a closer look at your problems in the future.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and when you want to open a new issue use the according template.
