### ISSUE TITLE
Conflict with ADBlocker plugin in Edge browser

### ISSUE THREAD

**Issue by edge75** [ckeditor/ckeditor-dev#3297]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. In Edge browser (User agent is Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134) try to insert a link
2. If AdBlock extension is installed if you click the "Ok button" on link popup nothing happens
3. In the console the following error is logged: Unable to get property 'collapsed' of undefined or null reference (link.js, line 25)

### Expected result

The expected result is that you can add a link

### Actual result

Nothing happens if you press OK

## Other details

* Browser: Edge
* OS: Windows 10
* CKEditor version: 4
* Installed CKEditor plugins: clipboard, links, forms, pbckcode, richcombo, font

**Comment by Dumluregn** [comment]
Hello, I can't reproduce the issue you described - I tried with Edge 17.17134 and [this Adblock extension](https://www.microsoft.com/store/productId/9NBLGGH4RFHK), but links can be still normally inserted: 
![linkEdge](https://user-images.githubusercontent.com/10883184/61858025-8da98c00-aec5-11e9-9493-c9e14af920fb.gif)
Could you share more details about the issue, like specific version of CKEditor you are using? Also please check if you are able to reproduce described behaviour using one of our default builds, e.g. [here](http://cdn.ckeditor.com/4.12.1/full-all/samples/). If that will work then the problem may be caused by a third-party plugin `pbckcode` which is not a CKSource product and we can't fix issues with code that doesn't belong to us.
Looking forward to hear from you if you managed to reproduce or solve an issue.

**Comment by f1ames** [comment]
The issue may be also caused by ADBlocker itself which may be blocking some CKEditor resources, manipulate page DOM or override some JS native functions.

**Comment by Dumluregn** [comment]
Yeah, I was going to mention that too but forgot, thats @f1ames

**Comment by edge75** [comment]
The issue was due to the interaction with the PBCKcode plugin. Thank you
