### ISSUE TITLE
Add MathType documentation and sample

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-dev#3307]
Demo: http://www.wiris.com/plugins/demo/ckeditor4/php/
Description: https://ckeditor.com/cke4/addon/ckeditorwiris
Docs: https://docs.wiris.com/en/mathtype/mathtype_web/integrations/html/ckeditor

**Comment by f1ames** [comment]
We already have `Mathematical Formulas` [features](https://ckeditor.com/docs/ckeditor4/latest/features/mathjax.html) and [examples](https://ckeditor.com/docs/ckeditor4/latest/examples/mathjax.html) pages, so we may think of adding additional section there or just create entire new pages dedicated for MathType (in the second scenario naming pages in menu will require some adjustments).

While extending existing example page should be straightforward as there is only one section now, extending features page may require thinking it over since there are few different sections on configuring MathJax, setup and so on - here it might be easier to go with separate page.

**Comment by wwalc** [comment]
A dedicated one may be better as both features are delivered by separate plugins and are quite complex to describe.=, so we'd end up with too long docs.

**Comment by Comandeer** [comment]
Docs were merged into `stable`.
