### ISSUE TITLE
CKEDITOR.replace is not a function only when using Source (Big N’Slow) ckeditor 4.12.1

### ISSUE THREAD

**Issue by madhurirode21** [ckeditor/ckeditor-dev#3312]
## Type of report

Bug

## Steps done

1. From https://ckeditor.com/cke4/builder : Choose 'Customize Online Builder'
2. By choosing proper skin and plugin, **if I choose 'Source(Big N Slow) option** and download 
ckeditor 4.12.1

![image](https://user-images.githubusercontent.com/40823392/62416361-fb3c8180-b656-11e9-8ae3-ffc63fab9728.png)

3. In code I am using 

textarea.replaceWithRTEListner = function(elemId, toolbarConfig, appliedMask, locale){

                  // replace the regular text area with a WYSIWYG object
                   var editor = CKEDITOR.replace(elemId, {
                         height: '200',
                         width: '650',
                         skin: 'kama',
                          toolbar: toolbarConfig || ""
                   });
                    CKEDITOR.on('instanceReady', function(evt) {
                             textarea.CKEDITORInstanceReadyListener(evt,elemId,appliedMask);
                     });
};

4. On UI side, textArea is not getting replaced with CKEditor and giving error as : 
**CKEDITOR.replace is not function**

******If I download same ckeditor version 4.12.1 with 'Optimized'  option from step 2, then same code from step 3 working fine. (textarea is getting replaced with ckeditor)**

![image](https://user-images.githubusercontent.com/40823392/62416359-ec55cf00-b656-11e9-8761-c2c266129bb6.png)

Please help me to resolve this issue as soon as possible.
How to replace ckeditor by using replace method with textarea when ckeditor builder is used with Source(Big and Slow).

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
