### ISSUE TITLE
is there the possibility of having only the media selector

### ISSUE THREAD

**Issue by MagnusDot** [ckeditor/ckeditor-dev#3335]
## Type of report

Docs

## Provide a description of requested docs changes

I would like to have only the media selector of ckeditor in a button for custom an input is it possible?
it would be nice and useful knowing that it already exists. it would be very convenient for many different cases

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
