### ISSUE TITLE
The cursor does not come out of the table when using Edge browser

### ISSUE THREAD

**Issue by v-bharts** [ckeditor/ckeditor-dev#3345]
## Type of report
The cursor does not come out of the table when using Edge browser

## Provide detailed reproduction steps (if any)

1. In the editor, select "Insert Table" and add the table to the body.
2. Press down arrow key or click outside the table.
3. The cursor does not go out of the table.

### Expected result
The cursor should move out of the table

### Actual result
Cursor is not moving outside the table

## Other details
Editor is behaving differently on different browser. In Chrome pressing the down arrow key from last cell moves the cursor out of the table but in Edge it does not.

* Browser: Edge
* OS: WIndows 10
* CKEditor version: 4
* Installed CKEditor plugins:

**Comment by engineering-this** [comment]
Hi.

This is how the browser works, the very same behaviour can be seen without CKEditor with plain `contenteditable`.

<details>
<summary>You can test with following HTML</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
</head>
<body>
<div style="padding: 10px; border: solid 1px black" contenteditable="true"><table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	</tbody>
</table></div>
</body>
</html>

```

</details>

CKEditor provides plugin [magicline](https://ckeditor.com/cke4/addon/magicline) that allow users to create paragraphs in such places that you can't put caret into because of browser limitation. See [demo](https://ckeditor.com/docs/ckeditor4/latest/examples/magicline.html)

If you don't want to use magicline plugin as a workaround you might report the issue to the browser vendor.
