### ISSUE TITLE
Cannot use Justify plugin in Inline configuration

### ISSUE THREAD

**Issue by Portekoi** [ckeditor/ckeditor-dev#3400]
## Type of report

The plugin `Justify` do not appear in `Inline` Mode.

## Provide detailed reproduction steps (if any)

1. Download load the full version [here](https://ckeditor.com/cke4/builder) (and check `Justify` plugin is in the left list)
2. Take a sample code CKEditor and try to add the `Justify` plugin's options

My example here : 
http://portekoi.com/LGI/PDF/editor.html

### Expected result

`Justify` plugin should be visible in the ToolBar like here : 
![image](https://user-images.githubusercontent.com/1560754/64610172-f5ad2680-d3ce-11e9-9561-c3278d90cd69.png)

### Actual result

`Justify` plugin is not visible : 

![image](https://user-images.githubusercontent.com/1560754/64610224-170e1280-d3cf-11e9-8fd7-b9a99fd58c7e.png)

## Other details

* Browser: Firefox and Chrome
* OS: Windows
* CKEditor version: 4
* Installed CKEditor plugins: all of them

**Comment by Comandeer** [comment]
This is caused by the fact that editor is initialised inside `p` element. Such placement disallows usage of block elements. Justify plugin works by adding block element with appropriate styles. Therefore the plugin works as intended in such situation: blocks can't be created inside the editor, so the justify plugin can't be used.

To be able to use Justify plugin, you have to wrap your paragraph with content in a `div` element.

**Comment by Portekoi** [comment]
Thanks a lot !
