### ISSUE TITLE
Bug - Internet Explorer - Place Cursor at Line Start

### ISSUE THREAD

**Issue by BorisFeuerpeil** [ckeditor/ckeditor-dev#483]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Use Internet Explorer 11
2. Write several Lines
3. Try to place the Cursor at Line Start 

### Expected result

The cursor should be placed, even if i click 3 milimeters before the first char in the line.

### Actual result

 in chrome it will be placed correctly, in internet explorer it does not. it only place at line start when i click directly on the first char.

## Other details

* Browser: Internet Explorer
* OS: Windows 10
* CKEditor version: 4.6
* Installed CKEditor plugins: nothing special

**Comment by mlewand** [comment]
This comes from a different implementation in IE and the rest of the browsers. Caused by the fact that Chrome, Firefox when clicked in the margin area, will attempt to put the caret inside the editable area, you can [test it in the example](https://codepen.io/mlewand/pen/RgrpOY?editors=1010#0).

### Workaround

There's a simple workaround for that: you could simply set `margin` to `0`, and add `padding: 20px` in [`body` styles in contents.css file](https://github.com/ckeditor/ckeditor-dev/blob/3b7f188/contents.css#L18). However we can't do this as this will break margin collapsing, elements inside the body to have unexpected mnargin, thus breaking experience for some of our users.

### What can be done?

The best call is to report this issue to Microsoft bug tracker. However remember that Microsoft support for IE11 is limited to security fixes, so the enhancement will land only for Microsoft Edge. Still, that would be nice!

If you report the issue, please drop a link here, as we'd love to support it!
