### ISSUE TITLE
Error using html5audio plugin

### ISSUE THREAD

**Issue by pmassu** [ckeditor/ckeditor-dev#492]
## Are you reporting a feature or a bug?

Bug
![screen shot 06-09-17 at 12 01 pm](https://user-images.githubusercontent.com/15627951/26970922-65933004-4d0b-11e7-8c3c-3e80e305fc5c.PNG)

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Insert an audio file (uploading it or defining the url) in a document

### Expected result

Audio plugin appears in the document and i can hear the audio.
I can save the document.

### Actual result

Audio plugin appears in the document and i can hear the audio.
It is impossible to save the document. Attached the error message i obtain.

## Other details

* Browser: Chrome
* OS: Debian
* CKEditor version: 4.5.7
* Installed CKEditor plugins: save,filebrowser,colorbutton,panelbutton,html5audio,widget,lineutils,clipboard,widgetselection

**Comment by mlewand** [comment]
`html5audio` plugin is not maintained by CKEditor team, please report the issue to it's developer so that they can see the issue https://github.com/iametza/ckeditor-html5-audio/issues

You can always find the proper tracker under "Issues tracker" link on plugin's page in our [Addons page](http://ckeditor.com/addon/html5audio).
