### ISSUE TITLE
How to remove unclosed tags(e.g. <strong>) in ckeditor? When I put any unclosed tag within a tag, its closed automatically before closing parent tag.

### ISSUE THREAD

**Issue by bisw** [ckeditor/ckeditor-dev#511]
## Are you reporting a feature or a bug?
How to remove unclosed tags(e.g. ) in ckeditor? When I put any unclosed tag within a tag, its closed automatically before closing parent tag. e.g. below my code before render

<div>
  <strong>Test unclosed tag 
  <p>
    <span>Hey this is test content to check unclosed tag 
      <a href="google.com">Google</a>
    </span>
  </p
  ><span>Processing...</span>
</div>

But after saving content, render content looks like below code

<div>
 <strong>Test unclosed tag </strong>
   <p><strong><span>Hey this is test content to check unclosed tag 
     <a href="google.com">Google</a></span></strong>
   </p>
  <strong><span>Processing...</span></strong>
</div>

So what I want, if any unclosed tag are there, they should be stripped and remain the content of the tag as plain like below code

<div>
  Test unclosed tag 
  <p>
    <span>Hey this is test content to check unclosed tag 
      <a href="google.com">Google</a>
    </span>
  </p
  ><span>Processing...</span>
</div>

Note: I do not know its an issue, may be its change request.

Any help or suggestion is much appreciated.

**Comment by mlewand** [comment]
I'm sorry but this is a place for reporting CKEditor bugs and not place for seeking advice or support.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

Just to comment on your issue it looks that the problem is coming from a different place - if you have a wrong markup as the input it clearly shows that the problem is in the logic before CKEditor kicks in.
