### ISSUE TITLE
Widgets can not be properly pasted into a table cell

### ISSUE THREAD

**Issue by drunklol** [ckeditor/ckeditor-dev#520]
## Are you reporting a feature or a bug?

bug

https://codepen.io/anon/pen/PjWVZW (inline)
http://sdk.ckeditor.com/samples/captionedimage.html (replace)

reproduction steps 

1. copy image (crtl + c)
2. paste into a table cell
3. reapeat

### Expected result

properly pasted images which can be resized, selected and deleted with DEL / ctrl + x

### Actual result

images are missing the drag and drop handler + resize handler 
and alot of other unexpected behaviour like unable to write anything inside the table.

## Other details

* Browser: chrome
* OS: win 10
* CKEditor version: 4.7
* Installed CKEditor plugins: enhanced image plugin

**Comment by wojtekw92** [comment]
regression is in version 4.7.0

**Comment by wojtekw92** [comment]
The problem occurs in tableselection plugin. This plugin has own `afterPaste` event handler. When we are pasting widget, this part of handler will work:
```javascript
// Handle mixed content (if the table is not the only child in the tmpContainer, we
// are probably dealing with mixed content). We handle also non-table content here.
if ( tmpContainer.getChildCount() > 1 || !pastedTable ) {
    selectedCells[ 0 ].setHtml( tmpContainer.getHtml() );
    editor.fire( 'saveSnapshot' );
    return;
}
```
# There are two problems:
1. Because of return we will never propagate `afterPaste` event
2. We are never making `initOn` on widget. Widget is listening i.a. for `afterInsertHtml` and initialise himself on this event.

## Solutions:
1. We should propagate event in all cases.
2. Maybe we should use `insertHtmlIntoRange` instead of `setHtml`?

**Comment by wojtekw92** [comment]
unit tests in branch: https://github.com/ckeditor/ckeditor-dev/tree/t/520
