### ISSUE TITLE
How to get Code Snippet style onto separate element

### ISSUE THREAD

**Issue by isaac2004** [ckeditor/ckeditor-dev#561]
## Are you reporting a feature or a bug?

**Bug/Feature** Is it possible to get the styled code snippet from the plugin in way for it to be injectable into another dom element?

### Expected result

To be able to make separate DOM element look like contents of Editor Window

### Actual result

Source from Editor for snippet looks like
````
<pre>
<code class="language-cs">var foo = new List&lt;string&gt;();</code></pre>

<p>&nbsp;</p>
````
When this is put in the DOM, it has no styling

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.7.0
* Installed CKEditor plugins: Code Snippet

**Comment by msamsel** [comment]
Hi,

unfortunately this issue is neither bug nor feature request. Your problem touching some specific situation related to CKEditor implementation. We encourage to discuss this kind of problems on stackoverflow, where other users can also get benefits from presented solutions. It's also possible that someone already had similar issue and will be able to help you with this case.
