### ISSUE TITLE
CKEditor doesn't work in a SPA

### ISSUE THREAD

**Issue by salmonb** [ckeditor/ckeditor-dev#601]
CKEditor works only on first visit, then any SPA navigation makes it stop working.

More details here: https://stackoverflow.com/questions/42442743/ckeditor-in-a-spa-freezes-when-navigating-back-to-the-editor-page.

Reproducer here: https://jsfiddle.net/ykspc3mo/

Thanks

**Comment by f1ames** [comment]
Hello @salmonb,

unfortunately this issue is neither a bug nor a feature request. Your problem is touching some specific situation related to CKEditor implementation. We encourage to discuss this kind of problems on stackoverflow, where other users can also benefit from presented solutions.

As you already posted your question on stackoverflow some time ago, I took a chance to answer it :)

Hope it will help to solve the problem.
