### ISSUE TITLE
how to destroy ckeditor in Angular2 application?

### ISSUE THREAD

**Issue by Willworkgogogo** [ckeditor/ckeditor-dev#604]
## Are you reporting a feature or a bug?

Question

## Provide detailed reproduction steps (if any)

1. i'm using the ckeditor4 in my Angular2 application. when i toggle page， the console warning like this: 
[CKEDITOR] Error code: editor-destroy-iframe.
ckeditor.js:21 [CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-destroy-iframe

2. i don't know how to solve it. Please Help me. Thank u very much!

## Other details

* Browser: Chrome
* OS: 
* CKEditor version: 4.x
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Hello @Willworkgogogo,

unfortunately this issue is neither a bug nor a feature request. Your problem is touching some specific situation related to CKEditor implementation. We encourage to discuss this kind of problems on stackoverflow, where other users can also benefit from presented solutions.

Anyway, take a look at [destroy](http://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-destroy) method.

**Comment by Willworkgogogo** [comment]
@f1ames i already solved it. Thank u for your suggestion and help!

**Comment by Natali0073** [comment]
> @f1ames i already solved it. Thank u for your suggestion and help!

Hello, how do you solve it? I also have this problem.
