### ISSUE TITLE
Inline widget does not preserve trailing space

### ISSUE THREAD

**Issue by gfox1984** [ckeditor/ckeditor-dev#605]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Create a widget plugin for an inline element (eg: `span`)
2. Load some data in CKEditor with a trailing space inside the element to be converted to a widget (eg: `<span>lorem </span>ipsum` )

see JSFiddle here: https://jsfiddle.net/cf5d457L/5/

### Expected result

The following text to be displayed: `lorem ipsum`

### Actual result

The following text is displayed (notice the missing space): `loremipsum`

## Other details

* Browser: all
* OS: all
* CKEditor version: latest (4.7.0)
* Installed CKEditor plugins: the Full preset together with all other plugins created by CKSource

**Comment by gfox1984** [comment]
While waiting for a fix, I wrote a work around that forces the last trailing space to be replaced with a non breaking space when upcasting the widget, and then replace it again with a space when downcasting it.

Updated fiddle here: https://jsfiddle.net/tuk1y92j/

**Comment by beatadelura** [comment]
It's happening because every white space and trailing space each inline element is removed. It's when inline element has css `white-space` set to `normal`, `nowrap`, `pre-line`. While `white-space` set to `pre` or `pre-wrap` cause all white characters in the source are preserved.

To read more, click [link](https://www.w3.org/TR/CSS21/text.html#white-space-model).

**Comment by beatadelura** [comment]
There is one case which will not be fixed with this issue because it's related to core code. Please see #791.
