### ISSUE TITLE
Difference between full download and full composer

### ISSUE THREAD

**Issue by robibi78** [ckeditor/ckeditor-dev#609]
## Are you reporting a feature or a bug?
Bug 

### Expected result
When I download the full version of CKEditor, there are differences when I use composer with dev-full/4.7.x. The plugins are differents and the skins too. 

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.7.1
* Installed CKEditor plugins:

**Comment by msamsel** [comment]
Hi,

I'm not sure what you compare. Could you describe a little bit more what do you mean by "use composer with dev-full/4.7.x." and with what full version do you compare it?
I would like to reproduce situation where I get 2 packages of CKEditor in this same way as you.
I would also appreciate if you could describe why you consider it as a problem? CKEditor is highly customized software, where you can create own package which includes all necessary plugins. You can check it here: http://ckeditor.com/builder.

**Comment by robibi78** [comment]
Hello, sorry for the lack of information. 
I used to download (with a direct link) the full package. The 4.7 version has the moono-lisa skin and somes plugins. 
Now I would like to use composer to download CKEditor. 
So I use composer with : 
"ckeditor/ckeditor": "dev-full/4.7.x"

And I think there are less plugins and the skins are differents.

Is it clear ? Maybe I do something wrong

**Comment by msamsel** [comment]
I'm still have problem with understanding which 2 version you compare. I still don't know what versions you have.

Could you provide me step by step guide how to obtain both versions, together with information what tool and setting you are using. I would like to get clear instruction which I could reproduce to obtain those 2 versions of CKEditor on my computer.

**Comment by robibi78** [comment]
Ok.

**Before**
I used this link http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.7.1/ckeditor_4.7.1_full.zip
ckeditor/plugins : 26 plugins
ckeditor/skins : moono-lisa

**Now**
I use composer
Composer.json
"require": {   
    "ckeditor/ckeditor": "dev-full/4.7.x"
  }
composer update

ckeditor/plugins : 71 plugins
ckeditor/skins : kama / moono / moono-lisa

----------------------------------------------
Maybe I did something wrong, but I thought I had the same result. Why this difference ?

**Comment by msamsel** [comment]
Thank you for this description. I made those steps and as result I get this same amount of folders in `ckeditor/plugins`. It seems that from some reason your package in composer is not minified. :(

About amount of directories in plugins folder (because I assume this was source of this issue).
When CKEditor package is build then we try to minify code and combine plugins with `ckeditor.js` file. Only plugins with some assets are not minified.

So if you wish to compare actual plugins in specific package you need to check it in real instance. To do so you can use **sample** provided together with package. Simple steps which can allow on checking plugins when you use our repository package set are below:
1. Open downloaded package with CKEditor. There should be `samples` folder in it.
1. Run some simple http server in **main** directory, or copy-paste this package on some http server
1. Then visit page with address like this: http://localhost:8080/samples/, where `localhost:8080` is address of server where CKEditor folder is available.
1. Open browser console
1. Check for currently loaded plugins `CKEDITOR.instances.editor.plugins`

This will list you all plugins which are loaded in current instance of the editor. You can also repeat similar steps for your project instance so you will be able to check what plugins are loaded directly in your project.

I hope it clears out, why there is smaller amount of folders in plugins directory, and why it's not related with amount of plugin available in editor.
