### ISSUE TITLE
ul element jumps out of DIV when inserting

### ISSUE THREAD

**Issue by ComvationAG** [ckeditor/ckeditor-dev#621]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

(No existing issue founded)

## Provide detailed reproduction steps (if any)

1. Open the following link
http://sdk.ckeditor.com/samples/fullpreset.html
2. Switch to sourcecode mode in the CKEditor
3. Insert the following code
```html
<h3 class="foo title">title</h3>
<div class="foo content">Lorem ipsum dolor sit amet, consetetur ...</div>
```
4. Switch back to WYSIWIG mode
5. Place the mousecursor behind the _lorem ipsum..._ text
6. Add a line-break with the "enter" key
7. Press the "ul" icon in the editor to generate an ul list and add some content to the first list item.
8. Switch back to sourcecode mode
9. Now you see the UL-list "jumped" out the div-element
```html
<h3>title</h3>
<div class="foo content">Lorem ipsum dolor sit amet, consetetur ...</div>
<ul>
<li>asdfsadf</li>
</ul>
```

### Expected result

The ul list should by stay inside the div and don't jump out of it.

### Actual result

The inserted ul list jump out of div.

## Other details

Detail Browser Info: http://whatsmybrowser.org/b/5B2ALEE

* Browser: Google Chrome - Version 59.0.3071.115 (Official Build) (64-Bit)
* OS: Windows 8.1
* CKEditor version: latest - _CKEditor 4.7.1 (Full) (revision 08ffd39) | CKEditor 4.7.1 (Full) (revision 08ffd39_)
* Installed CKEditor plugins: NO - default setup on demo page

**Comment by wojtekw92** [comment]
hi,
This is an expected behaviour to add list outside paragraphs.

**Comment by ComvationAG** [comment]
Hi @wojtekw92 

Thank you for your feedback.

But my example don't contain a paragraph.
I will insert the list inside a div element. The inserting of list in a div should work from my point of view.
Then the div element is made to group sub elements - like a list.

**Comment by ComvationAG** [comment]
@wojtekw92, could you please reopen this issue and check the problem again?

Thx!

**Comment by Reinmar** [comment]
Hi @ComvationAG,

I'm afraid this can't work as you'd expect. At least, not by default. You're expecting a very special and specific behaviour from the editor which is close to "web page building", while CKEditor is focused on content creation.

So, what's the rule which the editor follows? The content is made out of blocks. Paragraph is a block, list is a block, heading is a block. You can't nest blocks within each other. You can't have heading inside a paragraph or list inside a heading. CKEditor 4 breaks this rule in some cases (you may create headings inside list items) but this is a cause of huge headaches that we have.

In your case, both of the divs are understood as blocks. Why? Because they contain text. Divs are tricky. Some people expect them to behave like paragraphs (hence the div enter mode) and some as containers for block content.

CKEditor 4 tries to implement both so it needs to differentiate between those two cases using a heuristic which I mentioned.

So, if you want your `<div class="foo content">` to behave like a container, not a block, put paragraph inside it. E.g:

```html
<div class="foo content"><p>foo</p></div>
```

Now, if you click the list button the list will be created inside the div, not outside.

However, I really recommend you to split all this into two separate editors. Have the heading separately and the content separately. The way you want to use CKEditor is not recommended because it leads to a lot of problems. Use it well and you'll have much better control and results.

**Comment by ComvationAG** [comment]
Hi @wojtekw92 

Thank you for your well writen and helpful explanations.
That help me a much to understand the behaviour of CKEditor.

Thank you mentioned "trick", to force CKEditor to behave like a container, I found a solution for my current project.

And yes I understand, the "correct way" is to start for each sub element a new editor instance.

Have a nice day & best regards
