### ISSUE TITLE
Form is removed in divarea editor

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#649]
## Are you reporting a feature or a bug?

BUG

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/12508

## Provide detailed reproduction steps (if any)

A workaround has been provided in ticket 12508 but it doesn't cover a case when initial data with form is loaded. In such case form is removed.

### Expected result

Form is left.

### Actual result

Form is removed.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: N/A

**Comment by mlewand** [comment]
This is not a bug, inline editor does what it says so the content stays in it's original postion. Per HTML spec you must not nest one `form` element within the other, so browser does the right thing by removing a nested form.

There are many ways to workaound it:
* Use the classic editor (so that it is sandboxed from outter document),
* Wrap given content with a form when outputing that content,
* Use a workaround code provided in the [origin Trac issue](https://dev.ckeditor.com/ticket/12508).
