### ISSUE TITLE
Editor disappears in Modal

### ISSUE THREAD

**Issue by benepfist** [ckeditor/ckeditor-dev#688]
## Are you reporting a feature or a bug?

**Bug**

## Provide detailed reproduction steps (if any)

We do use the ckeditor in a Modal (remodal.js).

If the user opens the modal and switches to the fullscreen mode, the editor
and the modal dissapear.

![image](https://user-images.githubusercontent.com/1907795/28678496-db16d352-72f0-11e7-9d1b-4e509624d799.png)

![image](https://user-images.githubusercontent.com/1907795/28677946-53fb220c-72ef-11e7-8669-7276a80d1ad6.png)

![image](https://user-images.githubusercontent.com/1907795/28677997-77d16c18-72ef-11e7-8c35-6ab2f9429d13.png)

Here is an example on jsfiddle.

https://jsfiddle.net/9uhgtz7z/2/

## Other details

 - CKEditor version: version:"4.7.1",

**Comment by msamsel** [comment]
Hi,

your question is support type, not bug. It seems that you have troubles with integration CKEditor with some 3rd party tool. Without this `remodal` library, full-screen mode works fine. In such cases please use Stack Overflow, maybe someone in the community had already such problem and will be able to help you.
Little tip: There might be some problems with CSS, but this is **just a guess** from short look into behaviour of your example, because I'm not familiar with `remodal`library.
