### ISSUE TITLE
Add option in config.fillEmptyBlocks that keeps html untouched

### ISSUE THREAD

**Issue by fernandomm** [ckeditor/ckeditor-dev#691]
## Are you reporting a feature or a bug?

Feature request

## Provide detailed reproduction steps (if any)

config.fillEmptyBlocks accepts a boolean or a function that should return a boolean. In both cases CKEditor doesn't offer a way to simply keep html untouched:

* If the block is empty, keep it empty.
* If the block contains a `&nbsp;`, keep the `&nbsp;`

What happens currently is that:

- If you set it to true, it will fill all empty blocks.
- If you set it to false, it will remove `&nbsp;` from empty blocks, even if it was intentionally placed there.

Some advanced users, when using source code mode, may want to fill some empty blocks and leave others empty.

**Comment by beatadelura** [comment]
@fernandomm Did you try to specify a function with an element as a parameter for `fillEmptyBlocks`? There is a possibility to pass an element for which filler will be used or not. I think, by using this you can achieve what you need. See [CKEditor docs](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-fillEmptyBlocks).

**Comment by fernandomm** [comment]
@beatadelura yes, I tried it. But if i return false, it will remove `&nbsp;` from **all** blocks of the matched element, even if i manually added one there.

See the following HTML below:

```
<table>
  <tr>
    <td>&nbsp;</td>
    <td></td>
  </tr>
</table>
```

I would like to keep the `&nbsp;` in the first td and keep the second td empty, without `&nbsp;`. Looks like in the current version of CKEditor, it's not possible to do this. 

I know that I can add a class to the second td and change fillEmptyBlocks callback to handle that but I'm looking for a generic solution that doesn't require changes in CKEditor options.

The solution that i'm looking is to simply let my users choose this on their own. In other terms, keep this part of their HTML untouched.

**Comment by mlewand** [comment]
Reason why we are doing this is that without it one can not put the selection inside such elements (be it table, blocks etc). This is a fundamental part of CKE.

If someone really wants to customize it, the only way is a function mentioned before. There's no way to tell the difference between `nbsp` generated by CKE and user-created `nbsp` using source mode because in the end it's just a regular text.

**Comment by vargasd** [comment]
I'm having this issue, too. The problem is that when the `fillEmptyBlocks` function runs, the element passed as the argument does not match the element from the actual HTML. For instance, in the example above, when `fillEmptyBlocks` runs on both `<td>`s, they look exactly the same. I would expect `element.children.length === 1` for the first and `element.children.length === 0` for the second. Is there any way around that?

**Comment by naxtell** [comment]
I know this is an old issue but it is the exact problem that still exists and a custom function does not seem to solve the problem. I have the following to allow an empty `<div>` or `<p>` on their own.
`config.ignoreEmptyParagraph = false;`

I then have this function in an attempt to allow instances of `nbsp` manually added to stay, but have the CKE add the value itself.
```
config.fillEmptyBlocks = function (element) {
    console.log('fillEmptyBlocks element');
    console.log(element);
    if (element.children.length == 0)
        return false;
};
```
If I enter `<div>&nbsp;</div>` in Source view and toggle Source view off and back on, I see that `element` has 0 children. 
If I enter at least two, `<div>&nbsp;&nbsp;</div>`, I see `element` reflects 2 children.
Is there anything other setting that would strip a single `nbsp`?
