### ISSUE TITLE
[bug?] createBookmark() with a widget focused creates empty spans

### ISSUE THREAD

**Issue by dryoma** [ckeditor/ckeditor-dev#701]
Hello,

## Are you reporting a feature or a bug?

Possibly bug.

## Provide detailed reproduction steps (if any)

1. Add a widget plugin, create a widget (block level, such as div etc), add its button to a toolbar.
    Even the simplest demo plugin from [the official tutorial](http://docs.ckeditor.com/#!/guide/widget_sdk_tutorial_1-section-full-source-code) seems to work.
2. Create a widget instance somewhere. For example,
    ```html
    <p>I'm a usual paragraph</p>
    
    <figure class="widget-name">
      <img .. some attrs />
      <figcaption>edit me...</figcaption>
    </figure>
    
    <p>I'm a usual paragraph</p>
    ```
3. Get the widget focused. The widget itself, not any of its editables.
4. Call
    ```js
    editor.getSelection().getRanges()[0].createBookmark();
    ```

### Expected result

Not sure.

### Actual result

Two empty hidden spans with `data-cke-bookmark` appear before and after a widget. Since they are on the root of the edited area, after reiniting the editor (either after goint to Source and then wysiwyg again, or by saving a content, and then reopening) they get wrapped in `<p>` tags, or whatewer is the default Normal format tag, and eventually there are only those empty p tags around the widget.

```html
<p>I'm a usual paragraph</p>

<p>&nbsp;</p> <!-- extra paragraph -->

<figure class="widget-name">
  <img .. some attrs />
  <figcaption>edit me...</figcaption>
</figure>

<p>&nbsp;</p> <!-- extra paragraph -->

<p>I'm a usual paragraph</p>
```

Originally the issue happened with the use of the `textselection` plugin, and I initially created a ticket [there](https://github.com/w8tcha/CKEditor-TextSelection-Plugin/issues/28). But it happens even *without that plugin*, with vanilla CKEditor. And I looked in the source of createBookmark which [says it's a deliberate choice](https://github.com/ckeditor/ckeditor-dev/blob/3b7f188ce4222fb0795674e052b4117caa87dc40/core/dom/range.js#L696). So I concluded I'd better discuss the issue here.

## Other details

* Browser: Firefox latest, Chrome latest
* OS: Windows 7, Windows 10
* CKEditor version: 4.7.1, 4.5.
* Installed CKEditor plugins: The full bundle downloaded from the source + `widget` (and my custom plugin).

Thanks,

### Update: how exactly it works

**Comment by msamsel** [comment]
Hi,

please get familiar with description of method `createBookmark`, this is way how it works: http://docs.ckeditor.com/#!/api/CKEDITOR.dom.range-method-createBookmark
Your description seems to cover a way how this method work (it's "intruisive" way), or have I missed something?

**Comment by dryoma** [comment]
> please get familiar with description of method `createBookmark`
Sure, I have. And I understand, what is happening and why. Yet the empty paragraphs created can be a disturbance, and they do get created, for example, when a user goes to Source mode with widget focused - within the `textselection` plugin that utilizes the `createBookmark` (please see my original post, I have added code samples).

Widgets are a really cool new thing (well, relatively :) ) in CKEditor. So I wonder if anything can be done in CKEditor itself to address the work on this method with widgets.

**Comment by msamsel** [comment]
Hi,

I'm sorry that take it so long to confirm this issue. Unfortunately `textselection` plugins is not developed by CKSource. In such case you need to contact with an author.

About `createBookmark`, it's clearly described that this method modify DOM elements inside editor. If you are using it, you should be aware that such elements will be added to editor. And because of that, you should handle removing them from editor.
We cannot change way how `createBookmark` work, because this behaviour is used in many cases.

I hope it clears out a little bit this case.

**Comment by dryoma** [comment]
Ok, got it. I have already contacted the plugin's author. But since it uses CKEditor's  built-in function that apparently doesn't play well enough with widgets, I figured I should probably ask what you guys think. Well, in any case a negative result is a result too :) Thanks for you time.

**Comment by msamsel** [comment]
@dryoma I would not agree, that CKEditor doesn't play well with widgets.
There are 2 methods allowing for making bookmarks:
- [`createBookmark`](https://docs.ckeditor.com/#!/api/CKEDITOR.dom.range-method-createBookmark)
- [`createBookmark2`](https://docs.ckeditor.com/#!/api/CKEDITOR.dom.range-method-createBookmark2)

One is **intruisive** way, where second one is **non-intruisive** way for preparing bookmarks. Both methods has some benefits and drawbacks. It is plugin's author who decides, what is necessary in case of her/his plugin. From your description it seems that author decide to use first method but doesn't predict some specific case where used bookmarks behave wrongly.
We cannot change behaviour of those bookmarks, because current approach is used in many other plugins in CKEditor.
That's why I asked to contact with plugin's author with this case, because from our side we can't do much. Adding empty `<span>` with `data-cke-bookmark` is a way how `createBookmark` mark work.

**Comment by dryoma** [comment]
Sure, I understand. What I needed was your resolution on that, so that there is a final "not a CKEditor issue"/"work with the plugin", and since you guys obviousely know the subject far better than I do :)
