### ISSUE TITLE
Wrong position of contextmenu in image selector.

### ISSUE THREAD

**Issue by dineshtavant** [ckeditor/ckeditor-dev#715]
## Are you reporting a feature request or a bug?

BUG

## Provide detailed reproduction steps (if any)

1- Select the "Image" icon in the CK Editor.
2-Select "Browse Server".
3-Make sure there are enough images for the scroll bar to appear , else shrink the page size so that the vertical scroll bar could appear and then scroll Down.
4-Select an image and right click on that,

### Expected result

The context menu should open on the selected image at the clicked point.

### Actual result

Context menu can be seen in wrong position.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.4.6
* Installed CKEditor plugins: Yes

**Comment by msamsel** [comment]
Hi,

I'm not able to reproduce your steps. Can you check if problem exists in actual version of CKEditor (4.7.1)? And if yes then prepare some code snippet on page like codepen.io, jsfiddle, itp.?

**Comment by dineshtavant** [comment]
Here are some images to help you understand the problem

1- Click on the browse server.

![ckeditor-1](https://user-images.githubusercontent.com/30646422/28916411-bfcef0ec-785f-11e7-8ef2-05cae07b19aa.PNG)

2- If there are a large no of images present , then once you scroll down the context menu opens in the wrong place. In the screen shot given below , it can be seen that the context menu is placed way above the selected image . 

![ckeditor error](https://user-images.githubusercontent.com/30646422/28916447-d8cba108-785f-11e7-9b13-9bdf1fb0e5cc.png)

**Comment by msamsel** [comment]
Hi,

thank you for those screenshots. I can see is, that is a menu inside CKFinder not in CKEditor, that's why issue seems to not be related directly with CKEditor.
I tried to reproduce your problem here: http://ckeditor.com/ by uploading images from server but here finder behave correctly and menu was displayed as it should.

What I can recommend is to update CKFinder to newest version in your project and check if problem disappear. If problem will be still present, then please use https://github.com/ckfinder/ckfinder project repository to report this issue.
