### ISSUE TITLE
Is there a way to modify upload functionality of ckeditor?

### ISSUE THREAD

**Issue by flashery** [ckeditor/ckeditor-dev#755]
I was trying to use the upload feature in CKEditor with CKFinder.

However, the current functionality of this is that you need to first click the "Send it to the server" button. In order for the image to be uploaded to the server. I wan't it to be remove and when I click the OK button it will upload the image and added to the content automatically no more resizing or whatsoever. 

Is there anyway to implement this feature?

**Comment by msamsel** [comment]
Hi,

currently in CKEditor described behaviour is not possible to obtain. Generally I see 2 options here:
1. We can treat it as feature request. In such case it would be nice to have better description. What is status now, what is expected behaviour, what are requirements for the feature (maybe in some form of a bullet point), etc. Please be also aware that such functionality is not our top priority, so it can take a while when might be made.
2. Another option is to make custom development, where you can prepare your own plugin by yourself and share it with others here: https://ckeditor.com/addons/plugins/all.

**Comment by flashery** [comment]
Hello 

Here is the update to my issue.

https://stackoverflow.com/questions/45653570/cannot-read-property-getdialog-of-undefined-ckeditor

Can you take a look? Maybe you can help.

**Comment by msamsel** [comment]
Hi,

I hope that someone will be able to help you with this case on Stack Overflow. In mean time I encourage you to get familiar with our [docs](https://docs.ckeditor.com/). It has quite extensive description of CKEditor. It might be helpful to check our guid to creating plugins for CKEditor: https://docs.ckeditor.com/#!/guide/plugin_sdk_sample.

**Comment by NingerJohn** [comment]
@flashery did you find the solution for the requirement as you said? I need the same functionality....
