### ISSUE TITLE
CKEditor 4.7.1: Using ACF to remove table formatting

### ISSUE THREAD

**Issue by WrathOfZombies** [ckeditor/ckeditor-dev#797]
Pasting a table from Excel/Word has a lot of spans created to retain formatting. What we want to achieve is to remove the formatting from the tables, there by retaining the barebones table structure. Basically the ACF equivalent of `pasteFromWordRemoveStyles`. Could you point to an example on how to achieve this?

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.7.1
* Installed CKEditor plugins: pasteFromWord, table, tableselection

**Comment by mlewand** [comment]
There are couple of ways to achieve this. First, the simplest, adjust global editor ACF rules with `allowedContent` or `disallowedContent` (to list only the elements that you don't want to see).

Above obviously will affect both, content in the editor, and content pasted from Word, however you should prefer having a common rules across the editor features.

If you're determined to do custom stuff for pastes from Word only, there's a nice [`afterPasteFromWord`](https://docs.ckeditor.com/#!/api/CKEDITOR.editor-event-afterPasteFromWord) event for that. You can use to filter out stuff that you don't want to. Note that it stores the pasted content as a string, so you'll have to convert it into our data format (to use our filtering utilities such as `CKEDITOR.filter`, and work on DOM rather than on raw string) and then save it back as a string.

We were thinking about adding a config option for a filter for Word content only, but decided to wait to see if there's a demand for that from the community. In this case, it sounds like a good fit for your problem - if so we can convert this issue to a feature request for such config option.

**Comment by WrathOfZombies** [comment]
@mlewand Thanks for the explanation. While the config option sounds nice for the future, I think for now we are ok with going with a solution that works based off of allowedContent.

As an example here's a file that shows the current behavior of formatted pastes: https://github.com/cksource/ckeditor-dev/blob/f3ac54af653b16efb14174cace404805d2f54ebb/tests/plugins/pastefromword/generated/_fixtures/Table_text_attributes/Cell_text/expected.html

How do we use the global rules to strip out the span tags inside of the table. I dont see examples that show how to target nested elements. Targetting spans with those classes may end up removing them from a regular pasted text and we don't want to do that.

**Comment by WrathOfZombies** [comment]
@mlewand Just pinging.. Could you help with the above?

**Comment by WrathOfZombies** [comment]
@mlewand I am looking into using the `afterPasteFromWord` event and wanted to confirm if by "*so you'll have to convert it into our data format*" you meant using the CKEditor.HtmlParser?

**Comment by mlewand** [comment]
@WrathOfZombies sorry for the delay, had a busy time recently. You're correct! You can do that for instance using [`CKEDITOR.htmlParser.fragment.fromHtml`](https://docs.ckeditor.com/#!/api/CKEDITOR.htmlParser.fragment-static-method-fromHtml).

 I think that in this case one code listing will be worth even more than a thousand words 🙂

I have created an example codepen that shows exactly how to use `afterPasteFromWord` event.

https://codepen.io/mlewand/pen/oeaZrV

However note that it reuses `filter.clone()` method that is to be added in CKEditor 4.7.3. This method was added as a part of https://github.com/ckeditor/ckeditor-dev/pull/803

**Comment by WrathOfZombies** [comment]
@mlewand No worries. Sorry I was in a hurry to complete an important bug. That said thank you for the codepen. That helps and now I can clean up my fix with the right approach.

Closing this issue.
