### ISSUE TITLE
Image Plugin adds extra characters after <img> tag in Chrome

### ISSUE THREAD

**Issue by georgeLoney** [ckeditor/ckeditor-dev#914]
This is a bug.
Plugin Image, Chrome (Mac), ckeditor 4.7.2 
The image string that is inserted in the html has extra characters at the end of the <img src...> tag.
Incorrect string value: '/xE2/x80/x8B/xE2/x80/x8B...'
This does not occur in FireFox.

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

clean <img> tag

### Actual result

Invalid characters follow the <img> tag.

## Other details

* Browser: Chrome
* OS: Mac
* CKEditor version: 4.7.2
* Installed CKEditor plugins: full

**Comment by mlewand** [comment]
I don't see anything like that. I'm checking [Enhanced Image sdk demo](https://sdk.ckeditor.com/samples/captionedimage.html):

1. Removing all the content except the image.
1. Changing the image type to non-captioned, non-aligned image (so that it makes a `<img>` element).
1. Call `CKEDITOR.instances.editor1.getData()`.

Returned value does not include anything like in the original report.

Also please pay attention to fill the according to the template.

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
