### ISSUE TITLE
Sign + not working

### ISSUE THREAD

**Issue by Ange7** [ckeditor/ckeditor-dev#956]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

/

## Provide detailed reproduction steps (if any)

I have textarea ckeditor with AJAX request and save result in MySQL database serialized text

When i type plus sign (+) it's not saved. 

### Expected result

save sign plus

### Actual result

sign plus is removed

## Other details

* Browser: All
* OS: All
* CKEditor version: 4
* Installed CKEditor plugins: No

**Comment by msamsel** [comment]
Hi,
please provide example using JS+HTML (you can use websites like: codepen.io, jsfiddle.net, jsbin.com) which reproduce your problem. I'm not able to repeat this problem on our [sample](https://cdn.ckeditor.com/4.7.3/full-all/samples/).

**Comment by Ange7** [comment]
Code here : 
https://pastebin.com/sfnPvwRF

Thank you

**Comment by msamsel** [comment]
Hi,

thank  you for the information. You problem seems to be related to custom development of CKEditor plugin and seems to be not present in CKEditor. Please take a look at [my example](https://codepen.io/msamsel/pen/WZRyPZ?editors=1010), `+` sign is obtained properly there.
If you feel that problem is in CKEditor, please provide steps to reproduce it, without third party plugins. From my perspective your question is rather support case, please take a look on [this information](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/SUPPORT.md).

**Comment by msamsel** [comment]
I close issue for now. Still, feel free provide requested feedback, so I can reopen this issue in such case.
